### PR TITLE
Add CPU_STATE_* constants

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by JohnTitor** [comment]
Are they macOS-specific? I cannot find any reference on other BSDs.

**Comment by GuillaumeGomez** [comment]
Actually it seems to be mac only: http://fxr.watson.org/fxr/ident?v=xnu-792.6.70;im=bigexcerpts;i=CPU_STATE_USER

Updating the PR then.

**Comment by GuillaumeGomez** [comment]
Moved to apple. Let's say if the CI is happier now. 😄

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!
@bors r+

**Pull request merged**
