### PR TITLE
Update Ubuntu images to 20.04

### PR DESCRIPTION
**Pull request by JohnTitor**
I'd like to wait until the actual release date (Apr. 23) and the image is updated but it'd be nice to find any failures before then.

### CODE REVIEW

**Comment by JohnTitor** [comment]
log from x86_64-unknown-linux-gnu:

```
cargo:warning=/checkout/target/x86_64-unknown-linux-gnu/debug/build/libc-test-564f8688fcb7d9a9/out/main.c: In function '__test_fn_gettimeofday':
cargo:warning=/checkout/target/x86_64-unknown-linux-gnu/debug/build/libc-test-564f8688fcb7d9a9/out/main.c:37923:24: error: returning 'int (*)(struct timeval * restrict,  void * restrict)' from a function with incompatible return type 'int (*)(struct timeval *, struct timezone *)' [-Werror=incompatible-pointer-types]
cargo:warning=37923 |                 return gettimeofday;
cargo:warning=      |                        ^~~~~~~~~~~~
cargo:warning=/checkout/target/x86_64-unknown-linux-gnu/debug/build/libc-test-564f8688fcb7d9a9/out/main.c: In function '__test_field_type_ipc_perm_mode':
cargo:warning=/checkout/target/x86_64-unknown-linux-gnu/debug/build/libc-test-564f8688fcb7d9a9/out/main.c:42827:28: error: returning '__mode_t *' {aka 'unsigned int *'} from a function with incompatible return type 'short unsigned int *' [-Werror=incompatible-pointer-types]
cargo:warning=42827 |                     return &b->mode;
cargo:warning=      |                            ^~~~~~~~
cargo:warning=/checkout/target/x86_64-unknown-linux-gnu/debug/build/libc-test-564f8688fcb7d9a9/out/main.c: At top level:
cargo:warning=cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
cargo:warning=cc1: all warnings being treated as errors

```

**Comment by JohnTitor** [comment]
It seems [glibc changed `gettimeofday` to take *void](https://sourceware.org/git/?p=glibc.git;a=blob;f=time/sys/time.h;hb=319d2a7b60cc0d06bb5c29684c23475d41a7f8b7#l66). Also the definition of `ipc_perm` was changed/removed and `mode` field now takes `mode_t` on some targets.

**Comment by JohnTitor** [comment]
`SOMAXCONN` was updated by [this commit](https://sourceware.org/git/?p=glibc.git;a=commit;f=sysdeps/unix/sysv/linux/bits/socket.h;h=96958e2700f5b4f4d1183a0606b2b9848a53ea44).

**Comment by JohnTitor** [comment]
Hm, it's a strange result on i686-unknown-linux-gnu:
```
running 5 tests
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/libstd/sys/unix/time.rs:349:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: test failed, to rerun pass '--test cmsg'
```

**Comment by JohnTitor** [comment]
Okay, now CI is green, though we're skipping i686-unknown-linux-gnu. I'm going to land this now since it doesn't affect actual code and the image should be stable enough.

**Comment by iav** [comment]
got 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/libstd/sys/unix/time.rs:349:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
on armv7, after command ` cargo install --git "https://git.koesters.xyz/timo/conduit.git"` in docker container.
how to workaround it?

**Pull request merged**
