### PR TITLE
Add linux ioctl constansts: BLKSSZGET and BLKPBSZGET

### LINKED ISSUE #2500: Add `BLKSSZGET` and `BLKPBSZGET` ioctl arguments
Linux-only ioctl arguments that provide the virtual or physical block size of a block device.
Unfortunately, despite being present since kernel [2.20 BLKSSGET](https://github.com/util-linux/util-linux/blob/4a346e6b64ead1e7fe93d72e4f2bd740973b6079/lib/blkdev.c#L188) and [2.6.32 BLKPBSZGET](https://github.com/util-linux/util-linux/blob/23e51a5f6054041844d4b6c5c54e0e81db97c53d/lib/blkdev.c#L213), both lack proper documentation, [if not for the kernel source.](https://lkml.org/lkml/2013/11/3/128)
Luckily for us, linux rarely, if ever, breaks or changes userspace, meaning that once implemented they should require little to no maintenance, even without documentation.

### PR DESCRIPTION
**Pull request by Mek101**
Fixes #2500

### CODE REVIEW

**Comment by JohnTitor** [comment]
Aren't they arch-independent? If so, we can simply put it on `linux/mod.rs`.

**Comment by Mek101** [comment]
They're arch indipendent minus sparc

**Review by JohnTitor — APPROVED** [review]
Alright, thanks!

**Comment by Mek101** [comment]
El Psy Kongroo

**Comment by Mek101** [comment]
Noto really sure why it failed?

**Comment by devnexen** [comment]
pb lies there it seems for the mips arch

`RUNNING ALL TESTS
bad BLKSSZGET value at byte 3: rust: 0 (0x0) != c 32 (0x20)
bad BLKPBSZGET value at byte 3: rust: 0 (0x0) != c 32 (0x20)`

**Comment by Mek101** [comment]
I'm not sure why it fails on mips: I tried fiddling with the arch on [Compiler explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:2,endLineNumber:10,positionColumn:2,positionLineNumber:10,selectionStartColumn:2,selectionStartLineNumber:10,startColumn:2,startLineNumber:10),source:'%23include+%3Cfcntl.h%3E%0A%23include+%3Csys/ioctl.h%3E%0A%23include+%3Clinux/fs.h%3E%0A%23include+%3Cstdio.h%3E%0A%0Aint+main()+%7B%0A++++printf(%22BLKPBSZGET+syscall+code:+%25u%5Cn%22,+BLKPBSZGET)%3B%0A%0A++++printf(%22BLKSSZGET+syscall+code:+%25u%5Cn%22,+BLKSSZGET)%3B%0A%7D'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cmips564,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'',selection:(endColumn:12,endLineNumber:28,positionColumn:6,positionLineNumber:14,selectionStartColumn:12,selectionStartLineNumber:28,startColumn:6,startLineNumber:14),source:1,tree:'1'),l:'5',n:'0',o:'MIPS64+gcc+5.4+(C,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4), however the constants seem to be correct.

**Comment by Mek101** [comment]
Plus, if it's caused by a different value, then it should fail on sparc, since it's the only one with a different constant value

**Comment by Mek101** [comment]
Rebasing magic fixed it

**Comment by Mek101** [comment]
Could this be related to mips being big-endian? The constants definitions include some bit-shift that should be bit-edianess independent. The byte representation may not change between the architectures, but the numeric value does change form one endianess to the other.

Are there any """#define""" to change the constant value based off the arch endianness?

**Comment by Amanieu** [comment]
There is `#[cfg(target_endian = "big")]` and `#[cfg(target_endian = "little")]`.

**Comment by Mek101** [comment]
Another big-endian arch. Gotta check 'em all

**Comment by Mek101** [comment]
Sparc already has it's own different constants, so I guess it's fine(?)

**Comment by Mek101** [comment]
Could someone run the tests, please?

**Comment by Mek101** [comment]
Test timeout. Not sure if it means it passed

**Comment by Mek101** [comment]
Doesn't seem to have launched anything

**Comment by Mek101** [comment]
Yey!

**Pull request merged**
