### PR TITLE
Add ETH_* constants on Android

### PR DESCRIPTION
**Pull request by kristate**
Adding ETH_* constants that were found here on Linux but not on Android.

Source Reference is [linux/if_ether.h](https://android.googlesource.com/platform/bionic/+/master/libc/kernel/uapi/linux/if_ether.h) on Google OpenSource.

Thank-you.

/cc nix-rust/nix#865

### CODE REVIEW

**Comment by kristate** [comment]
By the way, I was going to add a test case in libc-test/test/build.rs but I saw this commit (5ea536a0a0502adcac8194ce92d7e8fbcfa40a9f) and it appears that that header file has already been included for android (https://github.com/rust-lang/libc/commit/5ea536a0a0502adcac8194ce92d7e8fbcfa40a9f#diff-747c41e91bd79d9208c2953b72047176R255). Is this correct?

**Comment by faern** [comment]
@kristate I'm working on fixing the errors related to `NFT_*_MAXNAMELEN` at the moment over in #922

**Comment by kristate** [comment]
Looking at the failed CI, these headers don't seem to be included yet:

```
ETH_P_ERSPAN
ETH_P_IBOE
ETH_P_NSH
ETH_P_IFE
ETH_P_MAP
```
A [blame against `linux/if_ether.h` for android](https://android.googlesource.com/platform/external/kernel-headers/+blame/master/original/uapi/linux/if_ether.h#71) shows that these constants were all defined by @cferris1000 in a [2017 commit](https://android.googlesource.com/platform/external/kernel-headers/+/25981136fb13bcacf5f475f3e0ec750341e1e671).

I am assuming we are working with an older version of Android, so I temporarily remove them from the commit. What is the best practice in this case?

**Comment by kristate** [comment]
Build seems to compile on android but fails due to some constants outside of this scope. ref: https://github.com/rust-lang/libc/pull/922#issuecomment-368273323

> @kristate I'm working on fixing the errors related to NFT_*_MAXNAMELEN at the moment over in #922 

So, I am waiting on #922 and then I will rebase.

**Comment by kristate** [comment]
r? @alexcrichton
Thanks!

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
