### PR TITLE
Add some aarch64-specific PROT_* constants for Linux.

### PR DESCRIPTION
**Pull request by pcc**

### CODE REVIEW

**Comment by pcc** [comment]
> Seems we should tweak libc-test to recognize it:
> 
> ```
>   cargo:warning=/checkout/target/aarch64-unknown-linux-gnu/debug/build/libc-test-583cc776ead9cd23/out/main.c:10123:58: error: 'PROT_BTI' undeclared here (not in a function)
>   cargo:warning=10123 |             static const int __test_const_PROT_BTI_val = PROT_BTI;
>   cargo:warning=      |                                                          ^~~~~~~~
>   cargo:warning=/checkout/target/aarch64-unknown-linux-gnu/debug/build/libc-test-583cc776ead9cd23/out/main.c:10129:58: error: 'PROT_MTE' undeclared here (not in a function); did you mean 'IPPORT_MTP'?
>   cargo:warning=10129 |             static const int __test_const_PROT_MTE_val = PROT_MTE;
>   cargo:warning=      |                                                          ^~~~~~~~
>   cargo:warning=      |                                                          IPPORT_MTP
>   cargo:warning=cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
> ```

I'm not getting these test failures on my aarch64 machine. Instead I get some different errors:
```
  cargo:warning=/home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c: In function ‘__test_field_type_sockaddr_vm_svm_zero’:
  cargo:warning=/home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c:23209:28: error: returning ‘unsigned char (*)[3]’ from a function with incompatible return type ‘uint8_t (*)[4]’ {aka ‘unsigned char (*)[4]’} [-Werror=incompatible-pointer-types]
  cargo:warning=23209 |                     return &b->svm_zero;
  cargo:warning=      |                            ^~~~~~~~~~~~
  cargo:warning=In file included from /usr/include/bits/local_lim.h:81,
  cargo:warning=                 from /usr/include/bits/posix1_lim.h:161,
  cargo:warning=                 from /usr/include/dirent.h:233,
  cargo:warning=                 from /home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c:5:
  cargo:warning=/home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c: At top level:
  cargo:warning=/home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c:42672:70: error: initializer element is not constant
  cargo:warning=42672 |             static const size_t __test_const_PTHREAD_STACK_MIN_val = PTHREAD_STACK_MIN;
  cargo:warning=      |                                                                      ^~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/include/signal.h:328,
  cargo:warning=                 from /usr/include/sys/param.h:28,
  cargo:warning=                 from /usr/include/resolv.h:56,
  cargo:warning=                 from /home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c:35:
  cargo:warning=/home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c:48606:61: error: initializer element is not constant
  cargo:warning=48606 |             static const size_t __test_const_SIGSTKSZ_val = SIGSTKSZ;
  cargo:warning=      |                                                             ^~~~~~~~
  cargo:warning=/home/pcc/rust-libc/target/debug/build/libc-test-b2754e4d9f14745a/out/main.c:48612:64: error: initializer element is not constant
  cargo:warning=48612 |             static const size_t __test_const_MINSIGSTKSZ_val = MINSIGSTKSZ;
  cargo:warning=      |                                                                ^~~~~~~~~~~
  cargo:warning=cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
  cargo:warning=cc1: all warnings being treated as errors
```

I guess the root cause is that the kernel headers on the CI are too old. What's the normal fix for this type of situation?

> Also could you add them to semver list? See https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md for the instructions.

Done.

**Comment by JohnTitor** [comment]
@pcc Friendly-ping, could you address the failure?

**Comment by JohnTitor** [comment]
Closing for inactivity, feel free to submit a new PR when you get some time to work on, thanks for contributing!

**Pull request closed without merging**
