### PR TITLE
Add EAI_SYSTEM getaddrinfo error code.

### PR DESCRIPTION
**Pull request by tmiasko**
This is useful to decide if value returned from getaddrinfo is actual
error or you should look at errno instead.

### CODE REVIEW

**Comment by bvinc** [comment]
This is needed for rust-lang/rust#36546.  I was looking at this earlier.  Looks good to me.

**Comment by semarie** [comment]
bitrig and openbsd definitions could be factorized in `src/unix/bsd/netbsdlike/openbsdlike/mod.rs`

**Comment by tmiasko** [comment]
@semarie moved OpenBSD and Bitrig changes into common openbsdlike mod, thanks.

@bvinc  indeed, the issue rust-lang/rust#36546 was original motivation for this change.

**Comment by alexcrichton** [comment]
Thanks!

**Comment by tmiasko** [comment]
Rebased.

**Pull request merged**
