### PR TITLE
android: add readahead

### PR DESCRIPTION
**Pull request by vauradkar**

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you edit the corresponding semver file?

**Comment by vauradkar** [comment]
> Could you edit the corresponding semver file?

Done

**Comment by JohnTitor** [comment]
You have to edit the related files under https://github.com/rust-lang/libc/tree/main/libc-test/semver. Once it's done please squash commits into one.

**Comment by JohnTitor** [comment]
Friendly-ping @vauradkar, could you check the above comment? Thanks!

**Pull request closed without merging**
