### PR TITLE
Add ALG_SET_DRBG_ENTROPY and ALG_SET_KEY_BY_KEY_SERIAL constants

### PR DESCRIPTION
**Pull request by rzimmerman**
`ALG_SET_KEY_BY_KEY_SERIAL` was added in Linux 6.2:
https://elixir.bootlin.com/linux/v6.2.16/source/include/uapi/linux/if_alg.h#L54

Also adding `ALG_SET_DRBG_ENTROPY` for completeness.

### CODE REVIEW

**Comment by rzimmerman** [comment]
Regarding the test failures, I think the jammy package for linux-headers is still tied to kernel version 5.15, so this constant is missing.

**Comment by JohnTitor** [comment]
We recently updated Ubuntu images to 23.10, please rebase onto main.
Note that our musl header is old and you would have to tweak https://github.com/rust-lang/libc/blob/main/libc-test/build.rs.

**Comment by tgross35** [comment]
@rzimmerman are you able to rebase to finish this?

**Comment by tgross35** [comment]
@rzimmerman this should just need a rebase if you are able to get it over the line

**Comment by tgross35** [comment]
Actually this should be all set, https://github.com/rust-lang/libc/pull/3404 added these constants. Closing since I don't think there is anything remaining here.

**Pull request closed without merging**
