### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by chloefeal**
I hope my corrections will help you. Thank you for your work.

### CODE REVIEW

**Comment by tgross35** [comment]
Thanks for the PR, could you provide a link to the headers where these are defined?

**Comment by chloefeal** [comment]
Sorry, maybe I am disunderstand.

**Comment by tgross35** [comment]
The correction is definitely welcome if it makes things more consistent with NTO's sources, but if they have that typo then I think we unfortunately need to keep the same typo.

**Comment by chloefeal** [comment]
@tgross35 Agree with you. It's better to make fix to upstream.

**Pull request closed without merging**
