### PR TITLE
FD_ISSET does not need to be mutable

### PR DESCRIPTION
**Pull request by Susurrus**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Tagging as 1.0-brekage, but it's also worth noting that [this isn't how these functions are prototyped](http://pubs.opengroup.org/onlinepubs/7908799/xsh/select.html).

**Comment by Susurrus** [comment]
@alexcrichton What do you mean? Those functions look correct to me.

**Comment by alexcrichton** [comment]
The prototype is:

```c
int FD_ISSET(int fd, fd_set *fdset);
```

not

```c
int FD_ISSET(int fd, const fd_set *fdset);
```

**Comment by Susurrus** [comment]
Sure, so you're saying all pointer function arguments within libc should be `mut` unless they've been explicitly labeled as `const`? So even though in this case this function shouldn't modify the argument, we can't assume that since the original API didn't declare that?

**Comment by alexcrichton** [comment]
What I'm saying is that we're not the one making the API decisions here, libc is. These are macros in libc so all we have to go off is the opengroup specification, which is what these APIs *would* look like (in theory) if they were actual functions.

**Comment by Susurrus** [comment]
Roger dodger. Then let's go ahead and close this.

**Pull request closed without merging**
