### PR TITLE
Use `build-std=core` instead of `build-std` alone

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Should help with https://github.com/rust-lang/libc/issues/3289.

### CODE REVIEW

**Comment by jyn514** [comment]
have you tested locally that `cargo doc-Zbuild-std=core` works? please don't test by publishing, i only have limited time to help.

**Comment by GuillaumeGomez** [comment]
Yes, tested with two targets just in case:

```
$ cargo doc -Zbuild-std=core --target=arm-linux-androideabi
    Updating crates.io index
   Compiling compiler_builtins v0.1.92
   Compiling core v0.0.0 (/home/imperio/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling libc v0.2.147 (/home/imperio/rust/libc)
   Compiling rustc-std-workspace-core v1.99.0 (/home/imperio/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
 Documenting libc v0.2.147 (/home/imperio/rust/libc)
    Finished dev [unoptimized + debuginfo] target(s) in 9.69s

$ cargo doc -Zbuild-std=core --target=aarch64-linux-android
   Compiling compiler_builtins v0.1.92
   Compiling core v0.0.0 (/home/imperio/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling libc v0.2.147 (/home/imperio/rust/libc)
   Compiling rustc-std-workspace-core v1.99.0 (/home/imperio/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
 Documenting libc v0.2.147 (/home/imperio/rust/libc)
    Finished dev [unoptimized + debuginfo] target(s) in 8.47s
```

Do you want me to test something else just in case?

**Comment by jyn514** [comment]
that seems fine - but just fyi most of the failures i mentioned https://github.com/rust-lang/libc/issues/3289#issuecomment-1622230892 are probably going to continue to be issues

**Comment by GuillaumeGomez** [comment]
It's fine for now. I can take a look at them later on, it's less pressing than the current state. ^^'

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by GuillaumeGomez** [comment]
> eyes Test was successful, but fast-forwarding failed: 422 Changes must be made through a pull request.

Anything I need to do about this?

**Comment by JohnTitor** [comment]
The commit was pushed anyway so we don't have to do anything (I believe this is a bug/weird behavior of bors, I remember seeing this message on the rust repo).

**Comment by GuillaumeGomez** [comment]
Noted, thanks for checking! Don't hesitate if I need to fix something.

**Pull request merged**
