### PR TITLE
Move constants from linux/magic.h out of gnu and uclibc

### PR DESCRIPTION
**Pull request by jirutka**
These constants are provided by Linux (`linux/magic.h`), not libc.

/cc @kaniini

### CODE REVIEW

**Comment by jirutka** [comment]
Why do you test alpine targets on Ubuntu instead of Alpine?

**Comment by Amanieu** [comment]
Alpine doesn't help in this case since we need a cross-toolchain for a different arch.

If you look at ci/docker/mips-unknown-linux-musl/Dockerfile you will see that we are actually using a MIPS musl toolchain from openwrt for the specific CI builder that is failing. The kernel headers in that toolchain seem to predate binderfs support in the kernel.

You could try updating the toolchain used in CI, which should resolve this failure.

**Comment by Amanieu** [comment]
Superseded by #2639.

**Pull request closed without merging**
