### PR TITLE
Define fdatasync on FreeBSD.  It was introduced in FreeBSD 11.1.

### PR DESCRIPTION
**Pull request by asomers**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like CI may be failing?

**Comment by asomers** [comment]
It looks like your QEMU image is still based on FreeBSD 10.  This PR will fail until you update that image.

**Comment by alexcrichton** [comment]
Unfortunately this can't land until CI is green :(

**Comment by asomers** [comment]
Then what's the procedure to upgrade the QEMU image, and is there any reason to hold it back?  The concerns around FreeBSD 12 compatibility don't apply here.

**Comment by alexcrichton** [comment]
There should be some documentation in the `ci` folder about how it was originally created, and IIRC the result is just a QEMU image file which once you get working locally I can upload and the URLs here can get updated.

**Comment by myfreeweb** [comment]
Just add it to `skip_fn` in ` libc-test/build.rs`

**Comment by wezm** [comment]
@asomers the CI image has been updated to 11.1 so this might pass now.

**Comment by asomers** [comment]
Thanks @wezm !  You have generously rewarded my laziness.

**Pull request merged**
