### PR TITLE
Add powerpc64-unknown-freebsd

### PR DESCRIPTION
**Pull request by MikaelUrankar**
FreeBSD review: https://reviews.freebsd.org/D18367

### CODE REVIEW

**Comment by gnzlbg** [comment]
@bors: r+ 

--- 

Please ping me in the rust-lang/rust PR where you upstream the aarch64 and powerpc64 freebsd targets. Its hard to make sure we don't break these if we can't even build the targets.

**Comment by gnzlbg** [comment]
@MikaelUrankar thank you for updating this PR, is the unsigned char added somewhere ? 

cc @asomers

**Comment by MikaelUrankar** [comment]
> @MikaelUrankar thank you for updating this PR, is the unsigned char added somewhere ?

It's in the pull req, I hope it's ok.

**Comment by gnzlbg** [comment]
> Should I be worried about the failure on TARGET=x86_64-pc-windows-msvc?

Appears unrelated.

@bors: r+

**Pull request merged**
