### PR TITLE
Upgrade the glibc toolchain to get newer headers

### PR DESCRIPTION
**Pull request by g2p**

### CODE REVIEW

**Comment by g2p** [comment]
All relevant targets are green.

**Comment by alexcrichton** [comment]
Can you describe what this is doing? I'm not sure what these ppa commands are personally.

**Comment by g2p** [comment]
It adds a newer version of the glibc toolchain, including newer linux headers.
This fixes missing C defines in #673; current tests require all flags defined in Rust to be defined in C headers.
The packages come from Canonical: https://wiki.ubuntu.com/ToolChain#PPA_packages

**Comment by alexcrichton** [comment]
Is there documentation for what this is doing? The string "artful" doesn't show up in the link you gisted. Also can this be combined with #673 instead of separate to ensure it actually fixes the errors seen?

**Comment by g2p** [comment]
Artful is Ubuntu 17.10.
I'm adding the repository as a PPA, so that its GPG key is registered, then I add it as a full Apt line so that the Ubuntu 17.10 headers (for Linux 4.11) are used everywhere.

**Comment by g2p** [comment]
I've rebased #673 on top of this to make a combined pull request.

**Comment by alexcrichton** [comment]
Could the docker images just be changed to `FROM ubuntu:17.10`?

**Comment by g2p** [comment]
I guess. I'll try that.

**Comment by g2p** [comment]
The base image upgrade is in https://github.com/rust-lang/libc/pull/677

**Comment by alexcrichton** [comment]
Can these changes happen directly on https://github.com/rust-lang/libc/pull/673?

**Comment by g2p** [comment]
Sorry. Done.

**Pull request closed without merging**
