### PR TITLE
Add missing constants for Android

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
These constants are also available in Android (but not emscripten).

This is a follow-up of https://github.com/rust-lang/libc/pull/3515.

CI might fail a few times before I figure out if I need to ignore these new constants in the tests or not...

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Sorry but could you rebase onto main? We're in the middle of the merge queue migration and the CI config of the base branch here doesn't trigger full CI.

**Comment by GuillaumeGomez** [comment]
No problem, done!

**Comment by JohnTitor** [comment]
Thanks! Now CI on PRs will be triggered by every push, could you make it green?

**Comment by GuillaumeGomez** [comment]
Oh that's convenient! Will make it much easier for you. Thanks for telling me. :)

**Comment by GuillaumeGomez** [comment]
Just like for linux, it's weird it doesn't find them as they're all present in [include/linux/sched.h](https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/include/linux/sched.h#1744). Oh well.

**Comment by JohnTitor** [comment]
Maybe it's related that our Android SDK/NDK is too old 🤔(I tried to update but it's quite complex and it hasn't been still a thing: https://github.com/rust-lang/libc/pull/3439)
Anyway let's skip tests as you did, thanks!

**Pull request merged**
