### PR TITLE
Add vm_size_t

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by gnzlbg** [comment]
@GuillaumeGomez Thank you for the PR, why do you need this? I would prefer to stop exposing mach headers in libc, deprecate what we expose, and recommend people to use the `mach` crate instead.

**Comment by gnzlbg** [comment]
Ah wait, nvm, this is for all *BSDs, for some reason I thought this was only for macosx. 

@bors: r+

**Comment by GuillaumeGomez** [comment]
Just like you said. ;)

**Comment by semarie** [comment]
this type doesn't exist on OpenBSD: `error: use of undeclared identifier 'vm_size_t'`

**Pull request merged**
