### PR TITLE
Attempt to fix musl build.

### PR DESCRIPTION
**Pull request by clarcharr**
Follow-up to #685 and #700.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks good to me, but CI is failing?

**Comment by clarcharr** [comment]
Fixed the style errors; waiting for Travis again.

**Comment by clarcharr** [comment]
It appears to be passing!

**Comment by alexcrichton** [comment]
@bors: r- retry

er actually, can you verify this works in the rustc repo?

**Comment by clarcharr** [comment]
I made a PR for the rustc repo to test it out; I think that's how this is supposed to work?

**Comment by clarcharr** [comment]
@alexcrichton it seems to work in the PR I made, so, I think this is okay to merge?

**Comment by alexcrichton** [comment]
Er what I mean is to actually test this. For example actually build libstd for these targets and make sure it works.

One error, for example, is that `stdbuild` is no longer a thing. For example this PR as-is should break linkage on all these targets.

**Comment by marioidival** [comment]
@clarcharr you can fix the conflict? 
@alexcrichton after conflict, need more changes here?

**Comment by alexcrichton** [comment]
Ah I think I'll close for inactivity for now, but this'll just need to be tested against rust-lang/rust before merging.

**Pull request closed without merging**
