### PR TITLE
Fixed a typo in the #[cfg()] of gettimeofday.

### PR DESCRIPTION
**Pull request by JasonSmith**
The #[cfg()] was looking for 'arget_os' instead of 'target_os'.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Possibly needs restarting of job: https://travis-ci.org/rust-lang-nursery/libc/jobs/107422617

**Comment by alexcrichton** [comment]
Oops, thanks! Can you rebase and re-push as well? (just merged another PR)

**Comment by alexcrichton** [comment]
Oh looks like this picked up a few extra commits, perhaps a rebase is in order?

**Comment by alexcrichton** [comment]
also feel free to ping the PR whenever you update, unfortunately github doesn't send out notifications for events like that

**Comment by JasonSmith** [comment]
@alexcrichton Rebased the pull request. Please merge this if you can.

**Comment by alexcrichton** [comment]
Hm looks like there are still some stray commits here? Perhaps a `reset --hard` to what's currently on master plus a `cherry-pick` of the relevant commit?

**Pull request merged**
