### PR TITLE
Add CPU_COUNT

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Looks like some CI is failing though?

**Comment by kubo39** [comment]
I'm not sure why, but error message shows `error: '__cpu_mask' undeclared` in musl-libc.
I'll try to fix!

**Comment by Susurrus** [comment]
@kubo39 You still interested in driving this PR? I think the solution is to just not expose this on `musl` targets.

**Comment by alexcrichton** [comment]
I'm going to close this due to inactivity, but feel free to resubmit with fixed tests!

**Pull request closed without merging**
