### PR TITLE
add net/if_arp.h definitions

### PR DESCRIPTION
**Pull request by canndrew**
This is based on the contents of include/net/if_arp.h on my Linux system.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like there may still be one failure remaining?

**Comment by canndrew** [comment]
Still working on it...

How important is it to match the C headers exactly? eg. The headers on my linux system use `unsigned short` and `unsigned char` in places where they should really be using `u16` and `u8` to describe the format of an ARP packet. I guess in practice there's no difference, but I noticed the netbsd headers do this correctly. So is it okay to have one `arphdr` definition for all unix platforms?

**Comment by canndrew** [comment]
Any idea what could be causing this on rumprun-netbsd?

    bad arphdr align: rust: 2 (0x2) != c 1 (0x1)

The definition of `arphdr` is

    pub struct arphdr {
        pub ar_hrd: u16,
        pub ar_pro: u16,
        pub ar_hln: u8,
        pub ar_pln: u8,
        pub ar_op: u16,
    }

**Comment by alexcrichton** [comment]
Perhaps on rumprun it's repr(packed)?

**Comment by canndrew** [comment]
I'll try adding repr(packed). Once I get this working let me squash the commits down before merging.

**Comment by canndrew** [comment]
CI malfunctioned.

**Comment by canndrew** [comment]
@alexcrichton This is ready to be merged if it gets your stamp of approval.

**Pull request merged**
