### PR TITLE
android add handful lock free stdio calls

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by JohnTitor** [comment]
Seems your branch is old against the master, could you check?

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Fails on ARM, could you check?
@rustbot author

**Comment by devnexen** [comment]
tests seem to pass, issues seem not related but to the VM itself.

**Comment by JohnTitor** [comment]
No, see the error:
```
CANNOT LINK EXECUTABLE "/data/local/tmp/main-d0545fbd84760f34": cannot locate symbol "fflush_unlocked" referenced by "/data/local/tmp/main-d0545fbd84760f34"...
```

**Comment by devnexen** [comment]
ah thanks for correcting me I missed that. fixing.

**Pull request merged**
