### PR TITLE
Adds many socket related constants

### PR DESCRIPTION
**Pull request by berkowski**
Started off adding a few constants to help cleaning up some `nix-rust/nix` issues.  Went a little.. further.

Adds lots of socket-related constants (`PF_*`, `MSG_*`, `AF_*`, `SO_*`, `SOL_*`, etc.) to linux/bsd flavors.  

Added constants to `bsd/frebsdlike/dragonfly` for completeness, though they aren't covered by CI.  Did not touch `notbsd/linux/s390x.rs`

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Nice!

**Comment by semarie** [comment]
constants like AF_MAX, PF_MAX, NET_RT_MAXID, NET_MAXID, ... aren't intent to be exported as public symbols. As soon a new element is added, the constant will change, and it will requires a major bump for libc.

FreeBSD code has comment on that for already included constants that are waiting for libc major crank to be removed.

**Comment by alexcrichton** [comment]
Changing the values of constants over time should be fine (that's what happens in C after all) but changing the type is what's a breaking change which I don't think changes in these cases?

**Comment by berkowski** [comment]
@semarie I had noticed that comment in the FreeBSD portion and thought it was limited to just the `*_MAXID` defines (though I see I missed `NET_RT_MAXID`).  I can remove `AF_MAX`, `PF_MAX` or follow the example and set them `#[doc(hidden)]`

**Comment by berkowski** [comment]
Just realized I never did AppleBSD.  I'll get that working while AWS sorts itself out.

**Comment by kamalmarhubi** [comment]
@berkowski is this good to go? I'm planning to send a release bump PR but this looks like it's ready and was just blocked on various outages.

**Comment by berkowski** [comment]
@kamalmarhubi Yup, ready to go on my end baring any revisions requested by maintainers.

**Comment by alexcrichton** [comment]
@bors: r+

Oh oops sorry!

**Pull request merged**
