### PR TITLE
Add SIGEMT (for apple) and SIGINFO (for bsd).

### PR DESCRIPTION
**Pull request by fiveop**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I'll work on getting CI fixed and then we can merge

**Comment by alexcrichton** [comment]
Ok, if you want to rebase on master that should pick up the fixes and CI should be able to run

**Comment by fiveop** [comment]
Can we get a version bump in the near future?

**Comment by alexcrichton** [comment]
Yeah once this is merged I can bump

**Comment by fiveop** [comment]
There still seems to be an infrastructure problem.

**Pull request merged**
