### PR TITLE
Add missing elements in freebsd

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like ci is failing?

**Comment by alexcrichton** [comment]
To verify those you'll probably want to edit `libc-test/build.rs` to not test the struct but only test the fields of the outer struct.

**Comment by GuillaumeGomez** [comment]
Ok, I'll do this first. I'll need to check for the remaining structs why it can't find them.

**Comment by GuillaumeGomez** [comment]
@alexcrichton: I think I'm done here, however I don't understand why the freebsd test is failing. Do you have any extra information by any chance?

**Comment by alexcrichton** [comment]
The errors look like:

```
bad racct size: rust: 184 (0xb8) != c 176 (0xb0)
bad field size r_rule_links of racct: rust: 16 (0x10) != c 8 (0x8)
bad KI_NSPARE_INT value at byte 0: rust: 4 (0x4) != c 7 (0x7)
```

Sorry I don't know much about FreeBSD

**Comment by GuillaumeGomez** [comment]
Ah thanks! Well, I understand what the errors are about. But I don't know where you got the errors. Well anyway, I'll update accordingly.

**Comment by GuillaumeGomez** [comment]
@alexcrichton: Any logs about this failure please? :)

**Comment by alexcrichton** [comment]
Sorry but your guess is as good as mine

**Comment by GuillaumeGomez** [comment]
Is it normal if there isn't any failure? :laughing:

**Comment by alexcrichton** [comment]
I'm gonna close this now due to inactivity, but it can of course be resubmitted!

**Pull request closed without merging**
