### PR TITLE
Upgrade crate version to 0.2.100

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @Amanieu

### CODE REVIEW

**Review by JohnTitor — CHANGES_REQUESTED** [review]
Could you also update libc-test crate version like https://github.com/rust-lang/libc/commit/520dd7df61b9b966ec64514ed58462d1ca77289b?

**Comment by JohnTitor** [comment]
(Btw, the patch version has finally reached 100 🎉)

**Comment by GuillaumeGomez** [comment]
Yeay for 100! \o/

And thanks for the pointer, I always forget to update libc-test... Anyway, updated!

**Comment by GuillaumeGomez** [comment]
@JohnTitor Updated!

**Comment by JohnTitor** [comment]
Okay, the merge queue has been cleaned up. I'll r+ tomorrow as it's late here.

**Comment by JohnTitor** [comment]
Or @Amanieu, if you have some time, feel free to take over.

**Comment by JohnTitor** [comment]
Let's go ahead :)
@bors r+

**Comment by JohnTitor** [comment]
Published on crates.io: https://crates.io/crates/libc/0.2.100

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
