### PR TITLE
Add gettid() for Linux

### LINKED ISSUE #2076: Add gettid() for Linux
I'm using x86_64-unknown-linux-gnu. I need to use `gettid()` in Rust, and it's not in this crate yet. It's got a simple signature:

https://man7.org/linux/man-pages/man2/gettid.2.html

It is Linux-specific. I could probably add it if it would help, but I'm not positive where to add it. From searching, it seems gnu, musl, uclibc, and Android include it, but I don't think Emscripten does (not sure).

I suppose it needs added in either

https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/mod.rs

or in both

https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/android/mod.rs
https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/mod.rs

And it seems like the tests are automatic so they wouldn't need changed?

### PR DESCRIPTION
**Pull request by TheDoctor314**
Fixes #2076

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!
@bors r+

**Comment by JohnTitor** [comment]
Failed on musl, we should skip tests for now as it requires a recent kernel.

**Comment by TheDoctor314** [comment]
Hello,
To be honest, I am a bit lost here what the next steps from me should be.
I apologize for any inconvenience.

**Comment by JohnTitor** [comment]
Okay, no worries! Could I push some commits to your branch to tweak tests?

**Comment by TheDoctor314** [comment]
Yeah, sure! Go for it!

**Comment by JohnTitor** [comment]
Emscripten doesn't seem to have it actually, moved the declaration under Linux and Android.
@bors r+

**Pull request merged**
