### PR TITLE
Add net interface device flag

### PR DESCRIPTION
**Pull request by LuoZijun**
Add net interface device flag for all platforms.

### CODE REVIEW

**Comment by LuoZijun** [comment]
@alexander255 
 the failing is about [libc/ci/style.rs](https://github.com/rust-lang/libc/blob/master/ci/style.rs#L55)

like some lines longer than 80 chars, maybe we turn off `panic` and use one `rustfmt.toml`  ?

**Comment by alexander255** [comment]
@LuoZijun I take it you were talking to @alexcrichton, not me? 🙂

**Comment by LuoZijun** [comment]
@alexander255 Oh ... mistake :D

**Comment by alexcrichton** [comment]
@LuoZijun for now let's stick with `style.rs`, it in theory shouldn't be too too hard to adhere to. Eventually we can use rustfmt when it's ready

**Pull request closed without merging**
