### PR TITLE
Add support for building with static glibc

### PR DESCRIPTION
**Pull request by joshtriplett**
This will need corresponding changes in rust-lang/rust to activate, but
this will make it possible to make those changes.

Note that despite the apparent redundancy in config directives, the link
directives cannot be simplified any further. Attempting to factor out
the checks for `target_feature = "crt-static"` does not work.

### CODE REVIEW

**Comment by joshtriplett** [comment]
Currently working on the corresponding changes in rust-lang/rust. It would really help to have a libc release with this PR included.

**Comment by joshtriplett** [comment]
Still WIP, need to do something similar for the link lines for `dl` and `util` buried inside Linux-specific code.

**Comment by joshtriplett** [comment]
OK, this should work now.

**Comment by joshtriplett** [comment]
Update: had to reverse the order of the libraries so that symbol resolution worked correctly when linking statically.

**Comment by joshtriplett** [comment]
Both of the failures seem entirely unrelated to this PR.

**Comment by joshtriplett** [comment]
Also, as far as I can tell, this change (together with some corresponding changes in rust-lang/rust) will noticeably speed up linking of all Rust binaries on `linux-gnu` targets, by reducing the amount of work the linker needs to do, since it won't need to process some libraries twice. I've tested this by manually re-invoking the linker and timing it, and overall, eliminating repeated libraries seems to provide a ~5% improvement in link time for a "hello world" Rust program.

**Comment by JohnTitor** [comment]
Thanks for the work and sorry for the delay! Looks great to me, let's re-trigger CI to make sure it.

**Review by JohnTitor — APPROVED** [review]
The failure is due to timeout and it was green previously so I'd ignore here. Thanks!

**Pull request merged**
