### PR TITLE
Add support for SIGSYS in signalfd

### PR DESCRIPTION
**Pull request by smibarber**
Linux 4.18 added support for SIGSYS info in signalfd. Add the new
fields to signalfd_siginfo.

While the kernel has support for these new fields now, no libc has
shipped a release with the new signalfd fields.

### CODE REVIEW

**Comment by gnzlbg** [comment]
@smibarber thank you for the PR! It seems that the android builds are breaking, could you take a look? 

```
argo:warning=                     return &b->ssi_ptr;
cargo:warning=                     ^
cargo:warning=/checkout/target/aarch64-linux-android/debug/build/libc-test-a8b4e1091355aa7f/out/main.c: In function '__test_field_type_signalfd_siginfo_ssi_utime':
cargo:warning=/checkout/target/aarch64-linux-android/debug/build/libc-test-a8b4e1091355aa7f/out/main.c:10455:21: error: return from incompatible pointer type [-Werror]
cargo:warning=                     return &b->ssi_utime;
cargo:warning=                     ^
cargo:warning=/checkout/target/aarch64-linux-android/debug/build/libc-test-a8b4e1091355aa7f/out/main.c: In function '__test_field_type_signalfd_siginfo_ssi_stime':
cargo:warning=/checkout/target/aarch64-linux-android/debug/build/libc-test-a8b4e1091355aa7f/out/main.c:10469:21: error: return from incompatible pointer type [-Werror]
cargo:warning=                     return &b->ssi_stime;
cargo:warning=                     ^
cargo:warning=/checkout/target/aarch64-linux-android/debug/build/libc-test-a8b4e1091355aa7f/out/main.c: In function '__test_field_type_signalfd_siginfo_ssi_addr':
cargo:warning=/checkout/target/aarch64-linux-android/debug/build/libc-test-a8b4e1091355aa7f/out/main.c:10483:21: error: return from incompatible pointer type [-Werror]
cargo:warning=                     return &b->ssi_addr;
cargo:warning=                     ^
cargo:warning=cc1: all warnings being treated as errors
```

Sadly the error message does not appear to mention the pointer types involved =/

**Comment by smibarber** [comment]
Yikes, I copied the entire struct to keep it consistent, but it does look like the Android NDK wanted those uint64_t fields as unsigned long long. I'll upload a commit to change the Android version back.

**Comment by gnzlbg** [comment]
Thank you! And sorry for the delay! Feel free to ping me next time once CI is green!

**Pull request merged**
