### PR TITLE
Add `pthread_mutex_timedlock`

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like this may not exist on OSX?

**Comment by apasel422** [comment]
Yeah, I have to investigate further.

**Comment by apasel422** [comment]
What's the proper organization for including this in Linux and BSD but not OSX or iOS?

**Comment by alexcrichton** [comment]
It's fine to duplicate the definition in the non-apple BSD modules

**Pull request merged**
