### PR TITLE
Fix cmsg(3) bugs for musl and OSX

### PR DESCRIPTION
**Pull request by asomers**
This PR fixes bugs in the cmsg(3) family of functions for Linux/musl and OSX, introduced by PR #1098 and PR #1212 .  It also adds an integration test which hopefully will validate these functions on every platform.

### CODE REVIEW

**Comment by gnzlbg** [comment]
Thank you for working on this @asomers. It appears that the tests are failing on some targets, maybe some more fine tuning is necessary.

**Comment by asomers** [comment]
I'm pretty sure that the s390x and sparc64 failures are not my fault.  On s390x the test program hangs.  On sparc64, it gets SIGILL.  In both cases, the problem happens before it invokes the first cmsg test function.  It's not Travis's fault; I can duplicate the problem locally.  It might be QEMU bugs.  If nobody else has a better idea, I'll disable the test for those architectures.

**Comment by asomers** [comment]
The two Android failures looks spurious; somebody should restart them.  However, the s390x and sparc64 failures are more serious.  They seem to be failing early in the test harness.  Cargo doesn't provide a way to disable the entire test program on a per-target basis.  So I'm stuck.  If the decision were up to me; I would just remove those platforms from the test matrix.

**Comment by gnzlbg** [comment]
@asomers could you fill in a bug in rust-lang/rust about the sparc64 and s390x failures ? We are able to run a lot of tests in other rust-lang repos like packed_simd, jemallocator, etc. in these platforms, so I find it weird that they fail for something "this simple".

**Comment by gnzlbg** [comment]
@bors: r-

(let me know when you rebase / squash)

---

We should definitely figure out why these particular tests break on those targets (maybe a qemu bug, maybe a rustc/llvm bug), but we don't have to do that here. I don't think disabling all testing on those targets makes things better for these targets. So skipping these tests until we figure things out seems reasonable to me.

**Comment by asomers** [comment]
Ok, now there's an ACTUAL failure on sparc64.  But given how much time I've already spent on this, I'm inclined just to skip that test on sparc64 and open an issue for it.  I'll let somebody who actually uses sparc64 and/or Linux fix it.

The android failures are a trivial mistake.  I'm locally investigating the s390x failure now.

**Comment by asomers** [comment]
Ok @gnzlbg everything's passing now.  I only had to disable the cmsg test on s390x and sparc64.  Let me know when you're satisfied review-wise and I'll squash things.

**Comment by gnzlbg** [comment]
The Cargo.lock needs updating. @alexcrichton should we just remove the `Cargo.lock` ?

**Pull request merged**
