### PR TITLE
Add AIX support

### PR DESCRIPTION
**Pull request by EGuesnet**
Minimal PR to build std library with AIX as a target. This target is not yet official in rust.

### CODE REVIEW

**Comment by Amanieu** [comment]
I don't feel familiar enough with libc to review this.

r? @JohnTitor

**Comment by JohnTitor** [comment]
Hey, thanks for the PR!
Could you clarify the context here? And if you have a custom std build, maybe it's enough to have a "patched" libc dependency.

**Comment by EGuesnet** [comment]
I am porting Rust to AIX. I have cross-compil libstd, libcore... on Linux with AIX as a target.
It is hard to reproduce because it needs a patched LLVM (all patchs are reported), a patched Rust compiler (not cleaned enough to be reported yet), an AIX server and some patched Rust libraries.

I report my patches about Rust libraries. This PR contains all libc patches I use to cross-compil std to AIX.

**Comment by JohnTitor** [comment]
So, you're currently compiling std and related stuff fine with your own patched libc, right? If you have a plan to add an official target, then you should follow the step like rust-lang/rust#86191.

**Comment by EGuesnet** [comment]
Thanks.
I plan to add an official target, but I need LLVM 13 at least (in October 2021), or probably LLVM 14.
I also have some compiler workaround, too ugly to be reported now.

If you want PR to be accepted in the same time for libc and compiler, I propose to transform this one as a draft. So, it is public if someone searches information about RUST on AIX.

**Comment by JohnTitor** [comment]
> If you want PR to be accepted in the same time for libc and compiler, I propose to transform this one as a draft. So, it is public if someone searches information about RUST on AIX.

Yeah, sounds good.

**Comment by bzEq** [comment]
Hi any progress on supporting rust on AIX? Looks it's not updated for couple of months and LLVM-13.0.0 is released.

**Comment by EGuesnet** [comment]
> Hi any progress on supporting rust on AIX? Looks it's not updated for couple of months and LLVM-13.0.0 is released.

Hi,
I have not made any progress on the Rust port. My team is no longer working on Rust anymore. I will give news on who will be working on this as soon as I know.

**Comment by danieu-il** [comment]
Hi, I have also a project where I need to use rust on AS400 or AIX, but stucked with no option. There is any news?

**Comment by EGuesnet** [comment]
Hi @danieu-il,
Sorry, but Rust port on AIX is totally frozen as far as I know. If you have a contract with IBM, you can contact them.
You can also contact the AIX OpenSource team on https://community.ibm.com/community/user/power/communities/community-home?CommunityKey=10c1d831-47ee-4d92-a138-b03f7896f7c9 .

**Comment by ecnelises** [comment]
Hi @EGuesnet , I proposed change (https://github.com/rust-lang/compiler-team/issues/553 ) to add AIX support in Rust toolchain. Since your focus are not on this any more, can we take over this PR and proceed by future patches?

**Comment by EGuesnet** [comment]
Hi @ecnelises,
You can take over this PR. I think this one is clean and mostly OK.
I wish you the best to achieve porting Rust to AIX!

**Comment by ecnelises** [comment]
I submitted #2894 as successor to this one. Thanks!

**Comment by JohnTitor** [comment]
Closing in favor of #2278

**Pull request closed without merging**
