### PR TITLE
Add network interface flag constants for all platforms

### PR DESCRIPTION
**Pull request by LuoZijun**
Add network interface flag constants for all platforms.

old PR: https://github.com/rust-lang/libc/pull/839

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Loks like there's some CI errors though?

**Comment by LuoZijun** [comment]
@alexcrichton this error from [libc/ci/style.rs](https://github.com/rust-lang/libc/blob/master/ci/style.rs#L55) , the master branch can not pass too, not my `patch-1` branch.

**Comment by faern** [comment]
@LuoZijun What if you remove all the formatting and make the PR contain only the new constants? Try that. Even if it does not make the tests pass more it at least makes the PR focused more on the feature, and not on formatting.

**Comment by LuoZijun** [comment]
@faern 

i'm sry, i found that problem is my sublime setting ( ` "format_on_save": true` ).

**Pull request merged**
