### PR TITLE
Release 0.2.98

### LINKED ISSUE #2275: Release 0.2.98
Could we have a new release for https://github.com/rust-lang/libc/pull/2237 please? The nix crate uses it and thus currently use libc as a git dependency, I would like to change that.

### PR DESCRIPTION
**Pull request by JohnTitor**
Closes #2275

### CODE REVIEW

**Comment by JohnTitor** [comment]
Holding off a bit to see the CI status of #2276.

**Comment by nox** [comment]
Seems like CI is green over there :)

**Comment by JohnTitor** [comment]
Let's go ahead!
@bors r+

**Comment by JohnTitor** [comment]
Published on crates.io: https://crates.io/crates/libc/0.2.98

**Pull request merged**
