### PR TITLE
add renameat2 and flags

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by Mic92** [comment]
this syscall only has a musl libc wrapper.

**Comment by phi-gamma** [comment]
Is there any obstacle to merging this now? Glibc received a proper wrapper for
``renameat2(2)`` with version 2.28 in 2018.

References:

- https://sourceware.org/git/?p=glibc.git;a=commit;h=d6da5cb6a8e0e8a9ce92b7d951a254cf325248d7
- https://sourceware.org/git/?p=glibc.git;a=blobdiff;f=NEWS;h=154ab22d7ca065af5233406927302bb7f6a66890;hp=d809f9393db00f1d6f3805d0599d89ebb8169921;hb=3c03baca37fdcb52c3881e653ca392bba7a99c2b;hpb=74939c83d03167d968000eba98f67aa37358d2dc

**Comment by gnzlbg** [comment]
This branch has been deleted, so I can reopen a PR and just check :/ 

Do you mind submitting a new PR with this ? IIRC we do support glibc 2.28 now.

**Comment by Mic92** [comment]
@phi-gamma feel free to cherry-pick my commit to a new PR.

**Comment by gnzlbg** [comment]
The branch has been deleted :/

**Comment by Mic92** [comment]
Yeah but

```
$ curl https://github.com/rust-lang/libc/commit/5d1b49634af9a797927cc96bff272fac33afa647.patch | git am -
```

works

**Comment by phi-gamma** [comment]
@Mic92: Already on it ;)

@gnzlbg: ``git fetch upstream pull/554/head:renameat2``  works regardless.

**Pull request closed without merging**
