### PR TITLE
Unify some of BSD flags

### PR DESCRIPTION
**Pull request by equal-l2**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like CI is failing though?

**Comment by equal-l2** [comment]
I don't have any idea about the CI failing.
Maybe should I simply copy `O_NONBLOCK` value to `O_NDELAY`, instead of assigning?

**Comment by equal-l2** [comment]
@alexcrichton Any thought?

**Comment by equal-l2** [comment]
I've found that all I need is unification of BSD flags.
I'll make another PR for that.

**Pull request closed without merging**
