### PR TITLE
Redox CI

### PR DESCRIPTION
**Pull request by jackpot51**
This does the following:

- Fix compilation on Redox
- Add Redox (x86_64-unknown-redox) to the tier2 CI targets
- Bump version to 0.2.59, so that the broken version 0.2.58 is superseded

### CODE REVIEW

**Comment by gnzlbg** [comment]
There appear to still be lots of errors even when using ctest 0.2.14. Do the tests pass for you locally?

**Comment by gnzlbg** [comment]
If the tests don't pass, you might want to add this CI job to the allowed_failures list for the moment, and once things are fixed upstream, try to get the test passing here.

**Comment by gnzlbg** [comment]
Triggering a new CI-build. This still had lots of CI errors last time. Would you mind fixing those?

**Comment by mati865** [comment]
I think it's blocked on https://github.com/rust-lang/rust/pull/60547

**Comment by newpavlov** [comment]
Can you also add this [fix](https://github.com/redox-os/liblibc/pull/3)?

**Comment by mati865** [comment]
It won't be necessary after rust-lang/rust#60547

**Comment by newpavlov** [comment]
Right now `libc` is completely unusable for Redox targets. And we don't know how long it will take for the rust-lang PR to get merged, while this PR can be merged relatively soon after the CI issues get fixed. Plus, even with the merged PRs, you will still have this bug on current and previous stable releases.

**Comment by gnzlbg** [comment]
This needs rebasing.

**Comment by gnzlbg** [comment]
@jackpot51 any chance of getting back to this soon ? It would be great if you could run libc-test on redox, and update this to be "ABI compliant".

**Comment by jackpot51** [comment]
Yes, I am very interested in that too. I'm just busy with trying to get rustc running on Redox

**Comment by JohnTitor** [comment]
I'm going to close this as inactive, feel free to re-open it or submit another PR when you find some time to work on (I've made some progress on #1934 so _rebooting_ should be simple).

**Pull request closed without merging**
