### PR TITLE
use new openbsd-6.0 qcow2 image

### PR DESCRIPTION
**Pull request by semarie**
this version is using `openbsd-6.0-without-pkgs` image.

### CODE REVIEW

**Comment by semarie** [comment]
I am unsure if travis will use the commit for CI.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
Looks like travis may still be red?

**Comment by semarie** [comment]
`gzip: stdin: not in gzip format`
it downloads the file with `.gz` and it isn't a gzip image...

it seems the openbsd-6.0 image introduced some heterogenity in QEMU processing

**Comment by semarie** [comment]
@alexcrichton there are two possibilities:
  - gzip the qemu image of openbsd (useless gzip layer as qcow2 image is compressed)
  - remove the gzip layer on freebsd image
    - convert the freebsd image to use compressed qcow format: `qemu-img convert -c freebsd.qcow2.gz -O qcow2 freebsd.qcow2`
   - remove the `gunzip` pipe in image download

**Comment by semarie** [comment]
my last commit will break freebsd as the image is qcow2.gz, but I will be able to check if openbsd build is fine.

**Comment by semarie** [comment]
now (as expected) only freebsd target is failing.

**Comment by alexcrichton** [comment]
Hm unfortunately we can't land this until all platforms are working, perhaps there could be two code paths? Could I compress/gzip the openbsd image to help?

**Comment by semarie** [comment]
@alexcrichton add additionnal gzip layer on openbsd images is a waste of CPU. I move to manage two different code paths, depending the `QEMU` name (ends with `.gz` or not).

**Comment by alexcrichton** [comment]
@bors: r+

ok cool, thanks!

**Pull request merged**
