### PR TITLE
Add constants from linux/keyctl.h

### LINKED ISSUE #1674: keyctl syscall constants missing
As a follow up to #1663, I've done more research into the matter and see that there is a `keyctl` raw syscall as outlined [here](http://man7.org/linux/man-pages/man2/keyctl.2.html) and the syscall number is even already supported by the libc crate. It does seem like many of the constant values are missing from the libc crate however. I would like to add the constants referenced in `/usr/include/linux/keyctl.h`. Would a PR to add these be of interest?

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #1674

### CODE REVIEW

**Comment by JohnTitor** [comment]
CI had some unrelated failures and they are fixed in master, could you rebase?

**Comment by JohnTitor** [comment]
Also it'd be great if you could squash :)

**Comment by jbaublitz** [comment]
Sure thing!

**Comment by jbaublitz** [comment]
@JohnTitor It looks like I need to add the header to `libc-test/build.rs`. I'll update and squash again.

**Comment by jbaublitz** [comment]
CI seems to be giving me a hard time. Going to throw up some commits and I'll squash once CI passes.

**Comment by JohnTitor** [comment]
:+1:, you can ignore semver check failures, I'll take a look later.

**Comment by jbaublitz** [comment]
Okay great. It looks like the failure is unrelated to my changes and is just in the android test. This seems to happen inconsistently because the last change I made did not have this failure. Does that seem consistent with what you've seen?

**Comment by JohnTitor** [comment]
Hm, it seems weird. Anyway the change looks good to me, could you squash again so that we can re-run CI?

**Comment by jbaublitz** [comment]
@JohnTitor Okay, squashed and pushed again. I'll keep an eye on the CI.

**Pull request merged**
