### PR TITLE
Declare statfs MAGIC constants as c_uint on s390x

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
Hi, I work in container development on Linux on Z at IBM.
On s390x (IBM Z) in GNU/Linux, a statfs `f_type` is 4 bytes wide, contrary to 8 bytes on most architectures.
This is already implemented in libc:
```sh
$ grep -r f_type src/unix/linux_like/linux/gnu/b64 | uniq
src/unix/linux_like/linux/gnu/b64/sparc64/mod.rs:        pub f_type: ::__fsword_t,
src/unix/linux_like/linux/gnu/b64/aarch64/mod.rs:        pub f_type: ::__fsword_t,
src/unix/linux_like/linux/gnu/b64/powerpc64/mod.rs:        pub f_type: ::__fsword_t,
src/unix/linux_like/linux/gnu/b64/riscv64/mod.rs:        pub f_type: ::c_long,
src/unix/linux_like/linux/gnu/b64/mips64/mod.rs:        pub f_type: ::c_long,
src/unix/linux_like/linux/gnu/b64/s390x.rs:        pub f_type: ::c_uint,             # s390x is uint
src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs:        pub f_type: ::__fsword_t,
```
However, the `*_MAGIC` constants (such as `EXT4_SUPER_MAGIC`) in `src/unix/linux_like/linux/gnu/mod.rs` are defined as `c_long`, when they should be `c_uint` on s390x.
This ends up biting me [here](https://github.com/kata-containers/cgroups-rs/blob/master/src/hierarchies.rs#L231).
Thus, I suggest the attached change to only define these constants for architectures other than s390x and instead define them as uint for s390x.
This is safe since none of the constants are any wider than 32bit.
Please let me know if you think this could be done more elegantly.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Makes sense!

> Please let me know if you think this could be done more elegantly.

You could use `cfg_if` macro for that case.

**Comment by Jakob-Naucke** [comment]
@JohnTitor more like this?

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
> more like this?

Yeah, thanks!

@bors r+

**Comment by Jakob-Naucke** [comment]
It would be good for this fix to be released to fix [Kata Containers](https://github.com/kata-containers/kata-containers/issues/1204) on s390x. @JohnTitor can I create a bump or do you feel the change is too insignificant?

**Comment by JohnTitor** [comment]
@Jakob-Naucke You can create a PR to make a release following the contributing guide: https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md#releasing-your-change-to-cratesio
But there are some PRs that are waiting for review and I may be unavailable during this holiday season.

**Pull request merged**
