### PR TITLE
structs nlmsghdr, nlmsgerr and nlattr added to linux mips musl target

### PR DESCRIPTION
**Pull request by rfael**

### CODE REVIEW

**Comment by xen0n** [comment]
The additions look good; while you're at it, would you mind adding the structs for the `mips64` targets too? This way things are more consistent.

**Comment by rfael** [comment]
I added that struct to mips64 musl target too

**Comment by rfael** [comment]
I filled x86 and arm musl targets too

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
