### PR TITLE
Add constants for memfd_create syscall

### PR DESCRIPTION
**Pull request by Susurrus**

### CODE REVIEW

**Comment by Susurrus** [comment]
Alright, we're green, finally! Should be good to merge.

**Comment by Susurrus** [comment]
@alexcrichton So I left off many of the musl targets because these constants aren't declared there. However, since this is a kernel interface, I'd imagine it's appropriate for those targets as well. Is that a correct understanding?

**Comment by alexcrichton** [comment]
Yeah I think that'd be fine.

**Pull request merged**
