### PR TITLE
Add `_NSGetArgv`, `_NSGetArgc` and `_NSGetProgname` from `crt_externs.h`

### PR DESCRIPTION
**Pull request by madsmtm**
Available in the headers on all Apple platforms.

### CODE REVIEW

**Comment by madsmtm** [comment]
The CI timeout seems to be unrelated

**Comment by tgross35** [comment]
This lgtm, reference here https://opensource.apple.com/source/Libc/Libc-320/include/crt_externs.h.auto.html.

Can you target `main`? We can backport if needed.

@rustbot label +stable-nominated
@rustbot author

**Comment by madsmtm** [comment]
> Can you target `main`

Sure! @rustbot ready

**Comment by tgross35** [comment]
Thanks!

**Review by tgross35 — APPROVED** [review]

**Pull request merged**
