### PR TITLE
several illumos fixes, and some additional termios constants

### PR DESCRIPTION
**Pull request by jclulow**
I wanted to add some of the new baud rate constants that [we added recently](https://www.illumos.org/issues/13975).  On the way there, I had to make a variety of fixes to get the tests to pass on illumos systems.

### CODE REVIEW

**Comment by jclulow** [comment]
With this series of commits, the tests now pass again:

```
$ (cd libc-test && cargo test)
   Compiling libc v0.2.108 (/ws/safari/rust-libc)
   Compiling libc-test v0.2.108 (/ws/safari/rust-libc/libc-test)
    Finished test [unoptimized + debuginfo] target(s) in 11.86s
     Running test/cmsg.rs (/ws/safari/rust-libc/target/debug/deps/cmsg-e194c71fe54543ae)

running 5 tests
test t::test_cmsg_data ... ok
test t::test_cmsg_firsthdr ... ok
test t::test_cmsg_len ... ok
test t::test_cmsg_space ... ok
test t::test_cmsg_nxthdr ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.64s

     Running test/errqueue.rs (/ws/safari/rust-libc/target/debug/deps/errqueue-b3e557442ece5dbc)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running test/linux_elf.rs (/ws/safari/rust-libc/target/debug/deps/linux_elf-c4b83707fea8d930)
PASSED 0 tests
     Running test/linux_fcntl.rs (/ws/safari/rust-libc/target/debug/deps/linux_fcntl-cb3b4167f025e27d)
PASSED 0 tests
     Running test/linux_if_arp.rs (/ws/safari/rust-libc/target/debug/deps/linux_if_arp-3b2a8366b990e987)
PASSED 0 tests
     Running test/linux_ipv6.rs (/ws/safari/rust-libc/target/debug/deps/linux_ipv6-fbd30315413a72f0)
PASSED 0 tests
     Running test/linux_strerror_r.rs (/ws/safari/rust-libc/target/debug/deps/linux_strerror_r-bc924bcb42c264e3)
PASSED 0 tests
     Running test/linux_termios.rs (/ws/safari/rust-libc/target/debug/deps/linux_termios-96062aa19befeba0)
PASSED 0 tests
     Running test/main.rs (/ws/safari/rust-libc/target/debug/deps/main-6989d6271949dcc6)
RUNNING ALL TESTS
PASSED 7119 tests
     Running test/semver.rs (/ws/safari/rust-libc/target/debug/deps/semver-0411189b90229d43)
PASSED 1 tests
     Running test/sigrt.rs (/ws/safari/rust-libc/target/debug/deps/sigrt-55024fdaab592c88)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

A few of these issues would have, I suspect, been caught if folks were running the tests before putting up PRs.  I recognise that there is not currently a CI builder for illumos systems for this project, but I wonder if it would be possible to CC me on future changes to illumos/Solaris files so that I can make sure the tests get run?  Is there a way to volunteer myself and/or perhaps other illumos community members to look at changes that we could help review, etc?

We have also, at Oxide, been experimenting with a GitHub app that can arrange for illumos CI builds of GitHub repositories.  It integrates using check suites/runs like other non-Actions based things; e.g., similar to the Cirrus CI being used for FreeBSD here.  Is that something we could perhaps try for the libc crate some time soon once it's had a bit more soak time?

**Comment by JohnTitor** [comment]
> With this series of commits, the tests now pass again:

Thanks! There are some breaking changes though, can I assume that they currently won't work correctly? If so, I think it's okay as they're not usable anyway.

> A few of these issues would have, I suspect, been caught if folks were running the tests before putting up PRs. I recognise that there is not currently a CI builder for illumos systems for this project, but I wonder if it would be possible to CC me on future changes to illumos/Solaris files so that I can make sure the tests get run? Is there a way to volunteer myself and/or perhaps other illumos community members to look at changes that we could help review, etc?

Sure, opened https://github.com/rust-lang/highfive/pull/366. You'll get a ping like https://github.com/rust-lang/libc/pull/2557#issuecomment-974776504 once it's merged.

> We have also, at Oxide, been experimenting with a GitHub app that can arrange for illumos CI builds of GitHub repositories. It integrates using check suites/runs like other non-Actions based things; e.g., similar to the Cirrus CI being used for FreeBSD here. Is that something we could perhaps try for the libc crate some time soon once it's had a bit more soak time?

Yea, definitely! I would love to see it :)

**Comment by jclulow** [comment]
> Thanks! There are some breaking changes though, can I assume that they currently won't work correctly? If so, I think it's okay as they're not usable anyway.

Yes I believe the breaking changes I made are all to clean up things that looked mostly right but had subtle ABI-ish problems like the `long double` thing that the test suite uncovered.

> Sure, opened [rust-lang/highfive#366](https://github.com/rust-lang/highfive/pull/366). You'll get a ping like [#2557 (comment)](https://github.com/rust-lang/libc/pull/2557#issuecomment-974776504) once it's merged.

Thanks!  That's awesome.

> Yea, definitely! I would love to see it :)

Great!  I'll swing back with a PR once it's ready for public consumption.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Ohhh, sorry! I didn't r+ this one even though I checked your comment... @bors r+

**Comment by JohnTitor** [comment]
Network failure, @bors retry

**Comment by JohnTitor** [comment]
There're some implementations that still use the typo'ed field name:
https://github.com/rust-lang/libc/blob/5e95cbb98319399bb8a7354c95439b75a3382998/src/unix/solarish/x86_64.rs#L89-L103

**Comment by jclulow** [comment]
@pfmooney did some work to clean this up, and I've included his work in this branch and rebased.  The tests now pass again:

```
$ uname -a
SunOS vulcan 5.11 helios-1.0.20799 i86pc i386 i86pc

$ (cd libc-test && cargo test)
   Compiling libc v0.2.116 (/ws/safari/rust-libc)
   Compiling libc-test v0.2.116 (/ws/safari/rust-libc/libc-test)
    Finished test [unoptimized + debuginfo] target(s) in 23.12s
     Running test/cmsg.rs (/ws/safari/rust-libc/target/debug/deps/cmsg-8121aecb845cbb39)

running 5 tests
test t::test_cmsg_data ... ok
test t::test_cmsg_space ... ok
test t::test_cmsg_len ... ok
test t::test_cmsg_firsthdr ... ok
test t::test_cmsg_nxthdr ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.61s

     Running test/errqueue.rs (/ws/safari/rust-libc/target/debug/deps/errqueue-c547c10f8b4f2364)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running test/linux_elf.rs (/ws/safari/rust-libc/target/debug/deps/linux_elf-bd07bbead775f9f6)
PASSED 0 tests
     Running test/linux_fcntl.rs (/ws/safari/rust-libc/target/debug/deps/linux_fcntl-8552d2d6c5d293e5)
PASSED 0 tests
     Running test/linux_if_arp.rs (/ws/safari/rust-libc/target/debug/deps/linux_if_arp-cc3231a8da9b37eb)
PASSED 0 tests
     Running test/linux_ipv6.rs (/ws/safari/rust-libc/target/debug/deps/linux_ipv6-fc3bb8ddc0bc5885)
PASSED 0 tests
     Running test/linux_strerror_r.rs (/ws/safari/rust-libc/target/debug/deps/linux_strerror_r-5cb11314c63e97d5)
PASSED 0 tests
     Running test/linux_termios.rs (/ws/safari/rust-libc/target/debug/deps/linux_termios-e3688047f6791a24)
PASSED 0 tests
     Running test/main.rs (/ws/safari/rust-libc/target/debug/deps/main-f9f9aac89fba0fb8)
RUNNING ALL TESTS
PASSED 7215 tests
     Running test/semver.rs (/ws/safari/rust-libc/target/debug/deps/semver-a5b1ae9ade0f2f3b)
PASSED 1 tests
     Running test/sigrt.rs (/ws/safari/rust-libc/target/debug/deps/sigrt-3c7f8a9f41084872)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by pfmooney** [comment]
> @pfmooney did some work to clean this up, and I've included his work in this branch and rebased. The tests now pass again:

I checked that the tests also pass when the `extra_traits` feature is active, which was relevant to the earlier comment about the (now-fixed) lingering "fpgregs" references.

**Comment by Amanieu** [comment]
Nice work! Would you be interested in adding illumos testing to the CI? At the moment we only check that the crate builds.

@bors r+

**Comment by Amanieu** [comment]
CI is failing on older Rust version (1.24)

**Comment by jclulow** [comment]
> CI is failing on older Rust version (1.24)

Sorry about that!  I've changed the align repr directives to be guarded by `libc_align`, and rebased.  Tests still pass for me locally with a current Rust version.

**Comment by Amanieu** [comment]
Let's give it another try!

@bors r+

**Pull request merged**
