### PR TITLE
Add STATX_DIOALIGN (introduced in linux v6.1)

### PR DESCRIPTION
**Pull request by ETKNeil**
The [STATX_DIOALIGN](https://elixir.bootlin.com/linux/v6.1/A/ident/STATX_DIOALIGN) constant was introduced in linux 6.1

The statx structure thus gained [2 more fields](https://elixir.bootlin.com/linux/v6.1/source/include/uapi/linux/stat.h#L127)

### CODE REVIEW

**Comment by JohnTitor** [comment]
Seems CI still fails, could you check?

**Comment by ETKNeil** [comment]
> Seems CI still fails, could you check?
CI Failed with
```sh
cargo:warning=/checkout/target/x86_64-unknown-linux-gnu/debug/build/libc-test-550781ad693ddf96/out/main.c:44809:73: error: 'STATX_DIOALIGN' undeclared here (not in a function)
```
Which indicates me that the image used in the CI is not linux 6.1+, however I removed STATX_DIOALIGN from the linux.txt list so it shouldn't test it (and I whitelisted it inside the libc-test/build.rs
I have no idea how your CI is setup tho but this shouldn't happen if I refer to other code examples with similar fate (RTNLGRP_BRVLAN for instance)

**Comment by JohnTitor** [comment]
Note that the semver list is different from the libc-test, and you added the const to **the branch for musl/arm** on libc-test/build.rs, that's why it fails. You have to ignore it unconditionally.

**Comment by ETKNeil** [comment]
> Note that the semver list is different from the libc-test, and you added the const to **the branch for musl/sparc64** on libc-test/build.rs, that's why it fails. You have to ignore it unconditionally.

Oh ok, I thought the semver was used to build the main.rs, I see that I got that wrong. I moved the conditional branch to another one, I missed the sparc64 condition, I wanted to put the constant close to something related.

**Comment by JohnTitor** [comment]
> Note CI is broken for freebsd 14

It was fixed on master already, it happens here because the branch is old.

Could you squash commits into one?

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
LGTM, thank you :)

@bors r+

**Comment by JohnTitor** [comment]
Spurious:
```
 error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-1.19.0.toml.sha256' to 'C:\Users\runneradmin\.rustup\tmp\irutc_j7ef6jls9z_file': failed to make network request: error sending request for url (https://static.rust-lang.org/dist/channel-rust-1.19.0.toml.sha256): connection error: An existing connection was forcibly closed by the remote host. (os error 10054): connection error: An existing connection was forcibly closed by the remote host. (os error 10054): An existing connection was forcibly closed by the remote host. (os error 10054)
```

@bors retry

**Comment by JohnTitor** [comment]
No luck, @bors retry

**Pull request merged**
