### PR TITLE
Add time namespace constant

### PR DESCRIPTION
**Pull request by cd-work**
This constant is a possible bitflag argument for `unshare`: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/sched.h?h=v6.6-rc1#n44

I am unsure about its support in Fuchsia, which is why I have not added the constant there.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by cd-work** [comment]
Seems like some tier2 architectures aren't supported, not sure how this is generally handled.

Would the best place to add this be `/src/unix/linux_like/linux/gnu/mod.rs`?

**Comment by JohnTitor** [comment]
Feel free to add to the targets where you want to use the item.

**Comment by JohnTitor** [comment]
Could you squash commits into one?

**Pull request merged**
