### PR TITLE
Make some inline functions like WIFEXITED and WEXITSTATUS const and safe

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Comment by JohnTitor** [comment]
I'm quite not sure if we could allow the safe things here; @alexcrichton if you have some time, could you review this? I assume you're familiar with that.

**Comment by alexcrichton** [comment]
AFAIK this should be fine to do, there's nothing technically preventing this. I believe the original decision for these functions was uniformity in `libc`, but that's not necessarily the best thing to optimize for here.

**Review by JohnTitor — APPROVED** [review]
Thanks, Alex! The macro itself looks good to me, let's go ahead :) And thanks to Josh for implementing it!

**Comment by joshtriplett** [comment]
Awesome, thanks @JohnTitor and @alexcrichton.

**Pull request merged**
