### PR TITLE
Add dladdr1 for GNU/Linux platforms

### PR DESCRIPTION
**Pull request by noproto**
Hey, this is my first pull request in a large open source project. Let me know if I'm missing anything or if you see any compile errors. This addresses dladdr1 missing in the libc library for GNU/Linux platforms.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
This has a style issue but otherwise LGTM.

**Comment by JohnTitor** [comment]
Uhm, looks like you've not allowed maintainers to access your fork and I cannot fix the issue by my hand...

**Comment by noproto** [comment]
@JohnTitor How can I fix it for future PR's including this one? This is what I see (Allow edits by maintainers is checked):
image

**Comment by JohnTitor** [comment]
Hmm, then that's weird. Usually, I can push commits with it checked but this time it's rejected by "permission denied".
Anyway, it's lucky that you're here while we prepare a release :) Could you run `cargo +nighly fmt` and push it (it's ideal to fixup the change)?

**Comment by noproto** [comment]
@JohnTitor cargo fmt completed

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Pull request merged**
