### PR TITLE
Added setpgrp

### PR DESCRIPTION
**Pull request by zethra**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Looks like the CI failures are vaild?

**Comment by zethra** [comment]
Not sure what those CI errors about. Those systems don't seem to be able to find the function.  Any suggestions?

**Comment by zethra** [comment]
Not sure why those few targets failed.  Any suggestions?

**Comment by alexcrichton** [comment]
It looks like this API may not exist on those platforms, perhaps it could be moved farther down in the sourc ehierarchy?

**Comment by semarie** [comment]
additionnally, not all platforms follows strictly POSIX.

under OpenBSD, `setpgrp()` is identical to `setpgid()`, and is retained for calling convention compatibility with historical versions of BSD (see http://man.openbsd.org/2/setpgrp).

**Pull request closed without merging**
