### PR TITLE
<sys/timex.h>

### PR DESCRIPTION
**Pull request by dfoxfranke**
Adds bindings for `ntp_adjtime` & co. for Linux, FreeBSD/NetBSD/Darwin, and Solaris/IllumOS.

### CODE REVIEW

**Comment by dfoxfranke** [comment]
@gnzlbg Integration tests on Linux are currently failing and I'm not sure quite what to do about it. The problem is that Linux's `struct timex` definition ends in a bunch of anonymous fields:

```c
struct timex
{
  unsigned int modes;
  __syscall_slong_t offset;
  __syscall_slong_t freq;
  __syscall_slong_t maxerror;
  __syscall_slong_t esterror;
  int status;
  __syscall_slong_t constant;
  __syscall_slong_t precision;
  __syscall_slong_t tolerance;
  struct timeval time;
  __syscall_slong_t tick;
  __syscall_slong_t ppsfreq;
  __syscall_slong_t jitter;
  int shift;
  __syscall_slong_t stabil;
  __syscall_slong_t jitcnt;
  __syscall_slong_t calcnt;
  __syscall_slong_t errcnt;
  __syscall_slong_t stbcnt;

  int tai;


  int :32; int :32; int :32; int :32;
  int :32; int :32; int :32; int :32;
  int :32; int :32; int :32;
};
```

In the bindings I represented these as `_unused: [i32; 11]` but the integration tests don't like this because there's not field in the C struct named `_unused`. How do I placate the test?

**Comment by dfoxfranke** [comment]
@gnzlbg Nevermind, I've got the Linux tests working now. Going to rebase this and then see if I can get IllumOS working.

**Comment by dfoxfranke** [comment]
This is ready for review. Tests are failing on `i686-apple-darwin` because the rustc nightly is currently broken, but everything else passes.

**Comment by dfoxfranke** [comment]
Ping @gnzlbg. Do you know when you'll get to reviewing this?

**Comment by JohnTitor** [comment]
Could you resolve conflicts and rebase? r? @JohnTitor

**Comment by dfoxfranke** [comment]
@JohnTitor all set.

**Pull request merged**
