### PR TITLE
Test FreeBSD 12 on latest nightly

### PR DESCRIPTION
**Pull request by mati865**
~~Let's see if [libc update](https://github.com/rust-lang/rust/pull/63806) for Rust fixed it.~~

Fixes https://github.com/rust-lang/libc/issues/1489

### CODE REVIEW

**Comment by gnzlbg** [comment]
@bors: r+

Looking good! cc @asomers

**Comment by mati865** [comment]
Windows is borked.
There was new `rustup` release recently, could be the reason:
```
D:\a\1\s>rustup default nightly-x86_64-pc-windows-gnu 
error: could not remove 'setup' file: 'C:\Users\VssAdministrator\.cargo\bin/rustup-init.exe'
info: caused by: Access is denied. (os error 5)
```

**Comment by gnzlbg** [comment]
cc @kinnison does this look familiar ?

**Comment by kinnison** [comment]
@gnzlbg 

If this is a github actions related problem then yes, @alexcrichton and @pietroalbini are both aware of it too and have filed a report with github.

**Comment by mati865** [comment]
@kinnison it's Azure Pipelines.

**Comment by pietroalbini** [comment]
Let me report this to them.

**Comment by kinnison** [comment]
> it's Azure Pipelines error.

Most likely the same sort of thing -- i.e. that their baseline image doesn't allow rustup to self-update.  They either need to pass `--no-self-update` to the toolchain installation step, or else make it permitted to self-update.

**Comment by gnzlbg** [comment]
Is it possible to workaround this here in the meantime ?

**Comment by ethomson** [comment]
This issue is being tracked at https://github.com/microsoft/azure-pipelines-image-generation/issues/1224 - in the meantime, using the `no-self-update` option is recommended.

**Pull request merged**
