### PR TITLE
Add `if_xdp.h` structs and constants and add `SOL_XDP` to musl

### PR DESCRIPTION
**Pull request by arctic-alpaca**
Hi,

this PR adds constants and structs from `if_xdp.h` for use with [`AF_XDP`](https://www.kernel.org/doc/html/latest/networking/af_xdp.html). It also adds `SOL_XDP` to musl which was missing before.

I'm not sure whether the location I added the code is correct, I just edited the files where the `AF_XDP` constant was defined.

Some of the structs were changed between their initial release in the kernel and the current version. For those, `_v1` structs have been added for backwards compatibility.

### CODE REVIEW

**Comment by arctic-alpaca** [comment]
I somehow blanked on the `skip_*()` functions in `build.rs` for a moment. I added the musl skips now.

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by arctic-alpaca** [comment]
I moved the semver changes to the correct file, I hope this is the last fix needed.

**Comment by JohnTitor** [comment]
Let's see if it works fine! @bors r+

**Comment by arctic-alpaca** [comment]
@JohnTitor Thanks for your patience! Is there any timeline for the next planned release?

**Comment by JohnTitor** [comment]
I'm going to make a new release, one sec!

**Comment by arctic-alpaca** [comment]
Thank you very much!

**Pull request merged**
