### PR TITLE
Linux: Add `preadv2` and `pwritev2` and associated constants

### PR DESCRIPTION
**Pull request by wmanley**
These functions are the same as `preadv` and `pwritev` but have a flags
parameter.  `preadv2()` and `pwritev2()` first appeared in Linux 4.6.
Library support was added in glibc 2.26.

See the definition of the constants in [linux/fs.h](https://github.com/torvalds/linux/blob/fcadab740480e0e0e9fa9bd272acd409884d431a/tools/include/uapi/linux/fs.h#L288-L301).

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks good, thanks!

**Comment by JohnTitor** [comment]
Hmm, I think the failure is due to our musl libc version (v1.1.24), the recent version should have them, right?

**Comment by wmanley** [comment]
> Hmm, I think the failure is due to our musl libc version (v1.1.24), the recent musl should have them, right?

Looks like musl doesn't have `preadv2` at all. I suspect the same is true for bionic.  I've moved the existing `preadv2` and `pwritev2` into gnu.

I've also got a fallback generic implementation using `syscall(SYS_preadv2, ...)`, but I'll raise that as a separate PR once this one's gone in as I imagine it will require more discussion.

**Comment by JohnTitor** [comment]
Okay, thanks! Let's give it another try.
@bors r+

**Comment by JohnTitor** [comment]
Ah, consts should be also moved.

**Comment by wmanley** [comment]
Ok, I've moved the consts too now.

**Pull request merged**
