### PR TITLE
Bump to 0.2.130

### PR DESCRIPTION
**Pull request by teamplayer3**
Quick fix for target `riscv32imc-esp-espidf`.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you tweak https://github.com/rust-lang/libc/commit/d0e3ff01a808d429baf925bf0e6e5f2273de1ac0? Read contribution.md how we release the crate.

**Comment by teamplayer3** [comment]
> Could you tweak [d0e3ff0](https://github.com/rust-lang/libc/commit/d0e3ff01a808d429baf925bf0e6e5f2273de1ac0)? Read contribution.md how we release the crate.

Can you please give me a hint what I have to tweak?

**Comment by JohnTitor** [comment]
@Amanieu Seems you released the crate with a recent nightly again, https://github.com/rust-lang/libc/issues/2866 happens on 1.2.130. Could you yank it and release a new version with a stable Cargo?

**Pull request merged**
