### PR TITLE
Add glibc extensions for posix_spawn*.

### PR DESCRIPTION
**Pull request by kosayoda**
This PR adds support for posix spawn extensions implemented by glibc: https://elixir.bootlin.com/glibc/glibc-2.37.9000/source/posix/spawn.h#L201.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by kosayoda** [comment]
As far as I can tell, the `sparc64-unknown-linux-gnu` test is failing because it's using an older version of glibc?

**Comment by JohnTitor** [comment]
> As far as I can tell, the `sparc64-unknown-linux-gnu` test is failing because it's using an older version of glibc?

Yes:
https://github.com/rust-lang/libc/blob/90531f68dcd9e6383f8390eb7f2e34935aa0905e/ci/docker/sparc64-unknown-linux-gnu/Dockerfile#L1-L2

You could skip tests for that arch by tweaking libc-test's build.rs.

**Pull request merged**
