### PR TITLE
Add Android uinput bindings

### PR DESCRIPTION
**Pull request by spencercw**
This is mostly copied from the Linux bindings.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Currently, our CI for Android has been disabled and I'd like to fix it before approving this PR, sorry for the inconvenience!

**Comment by spencercw** [comment]
For what it's worth, I think there might be something wrong with the Android build anyway. I had to comment out these lines in linux_like/android/mod.rs in order to get the tests to run. NDK 21.4.7075529.
```
pub const PTRACE_GETREGS: ::c_int = 12;
pub const PTRACE_SETREGS: ::c_int = 13;
```
Errors from libc-test:
```
warning: /home/chris/projects/rust-libc/target/aarch64-linux-android/debug/build/libc-test-f131c5a89cac3bdb/out/main.c:27230:64: error: use of undeclared identifier 'PTRACE_GETREGS'
warning:             static const int __test_const_PTRACE_GETREGS_val = PTRACE_GETREGS;
warning:                                                                ^
warning: /home/chris/projects/rust-libc/target/aarch64-linux-android/debug/build/libc-test-f131c5a89cac3bdb/out/main.c:27236:64: error: use of undeclared identifier 'PTRACE_SETREGS'
warning:             static const int __test_const_PTRACE_SETREGS_val = PTRACE_SETREGS;
warning:                                                                ^
warning: 2 errors generated.
```
よろしくお願いします

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
> For what it's worth, I think there might be something wrong with the Android build anyway. I had to comment out these lines in linux_like/android/mod.rs in order to get the tests to run. NDK 21.4.7075529.
> 
> ```
> pub const PTRACE_GETREGS: ::c_int = 12;
> pub const PTRACE_SETREGS: ::c_int = 13;
> ```
> 
> Errors from libc-test:
> 
> ```
> warning: /home/chris/projects/rust-libc/target/aarch64-linux-android/debug/build/libc-test-f131c5a89cac3bdb/out/main.c:27230:64: error: use of undeclared identifier 'PTRACE_GETREGS'
> warning:             static const int __test_const_PTRACE_GETREGS_val = PTRACE_GETREGS;
> warning:                                                                ^
> warning: /home/chris/projects/rust-libc/target/aarch64-linux-android/debug/build/libc-test-f131c5a89cac3bdb/out/main.c:27236:64: error: use of undeclared identifier 'PTRACE_SETREGS'
> warning:             static const int __test_const_PTRACE_SETREGS_val = PTRACE_SETREGS;
> warning:                                                                ^
> warning: 2 errors generated.
> ```

Hmm, I guess your setup is different from our CI's? These consts are old enough and I don't think it makes difference.

Anyway, x86_64 CI has been fixed, so let's go ahead. Thanks for the PR!

**Comment by spencercw** [comment]
Corrected `SW_MAX` value

**Comment by spencercw** [comment]
Added missing traits

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Pull request merged**
