### PR TITLE
Add missing consts for Solaris/Illumos

### PR DESCRIPTION
**Pull request by nbaksalyar**
This PR adds several missing structs and constants to the Solaris module that are required by the [nix crate](https://github.com/nix-rust/nix).

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 

Thanks!

**Comment by alexcrichton** [comment]
@bors: r+ 

hm seems like that didn't go through...

**Comment by alexcrichton** [comment]
Hm not sure what's up with bors, but passed all CI, so merging.

**Comment by nbaksalyar** [comment]
Thanks! :)

**Pull request merged**
