### PR TITLE
Add MADV_* constants for Linux

### PR DESCRIPTION
**Pull request by topecongiro**

### CODE REVIEW

**Comment by JohnTitor** [comment]
CI failed, could you also modify the semver file? See the [contribution guide](https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md#adding-an-api) for details.

**Comment by topecongiro** [comment]
@JohnTitor Thanks for the review. Sorry about not paying attention to the contribution guide; I will fix this accordingly.

**Comment by JohnTitor** [comment]
@topecongiro Friendly-ping, could you address the failure?

**Comment by JohnTitor** [comment]
Closing as inactive, feel free to reopen/resubmit if you're still interested in this change. Thank you!

**Pull request closed without merging**
