### PR TITLE
Add more IFLA_ values

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Comment by joshtriplett** [comment]
I'm expecting CI to fail here, due to values not available in headers. Waiting to see the failures, to determine how to address them.

**Comment by joshtriplett** [comment]
OK, this now passes CI, and I'd like to merge it.

**Review by JohnTitor — COMMENTED** [review]
Looks good!

**Comment by joshtriplett** [comment]
Looks that way, sigh. I really wish musl would just use the real kernel headers.

**Pull request merged**
