### PR TITLE
feat: add GSO flags for linux and android

### PR DESCRIPTION
**Pull request by elecm**
Add Generic Segmentation Offload (GSO) flags based on [if_tun.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/if_tun.h#L87) header in Linux  and [if_tun.h](https://android.googlesource.com/platform/bionic/+/HEAD/libc/kernel/uapi/linux/if_tun.h#71) header in Android source code.
Include the `IFF_NO_CARRIER` flag as well (found in the same files mentioned in the previous paragraph).

There is a [PR](https://github.com/rust-lang/libc/pull/3320#issue-1857370692) similar to mine, but that PR doesn't include GSO flags for UDP (`TUN_F_USO4` and `TUN_F_USO6`), and it is only for Linux. And also, I used `c_uint`type for GSO flags because related ioctl function (`#define TUNSETOFFLOAD  _IOW('T', 208, unsigned int)`) get `unsigned int` but that PR uses `c_ushort`.

### CODE REVIEW

**Comment by elecm** [comment]
Continuation of this [PR](https://github.com/rust-lang/libc/pull/3405#issuecomment-1789648681)

**Review by JohnTitor — APPROVED** [review]

**Comment by elecm** [comment]
> 💔 Test failed - [checks-actions](https://github.com/rust-lang/libc/actions/runs/6775951028/job/18416806055)

Added `IFF_NO_CARRIER`, `TUN_F_USO4`, and `TUN_F_USO6` to android  skip_const list. Now it should works.

**Comment by JohnTitor** [comment]
👍 @bors r+

**Pull request merged**
