### PR TITLE
android system prop api update.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Oh, my bad, @bors r-

**Comment by JohnTitor** [comment]
```
   cargo:warning=/checkout/target/i686-linux-android/debug/build/libc-test-ac0f7594ba6b2872/out/main.c:17088:60: error: invalid application of 'sizeof' to an incomplete type 'prop_info' (aka 'struct prop_info')
  cargo:warning=             uint64_t __test_size_prop_info(void) { return sizeof(prop_info); }
  cargo:warning=                                                           ^     ~~~~~~~~~~~
  cargo:warning=/android/ndk-i686/bin/../sysroot/usr/include/sys/system_properties.h:39:16: note: forward declaration of 'struct prop_info'
  cargo:warning=typedef struct prop_info prop_info;
  cargo:warning=               ^
  cargo:warning=/checkout/target/i686-linux-android/debug/build/libc-test-ac0f7594ba6b2872/out/main.c:17092:29: error: field has incomplete type 'prop_info' (aka 'struct prop_info')
  cargo:warning=                  prop_info v;
  cargo:warning=                            ^
  cargo:warning=/android/ndk-i686/bin/../sysroot/usr/include/sys/system_properties.h:39:16: note: forward declaration of 'struct prop_info'
  cargo:warning=typedef struct prop_info prop_info;
  cargo:warning=               ^
  cargo:warning=/checkout/target/i686-linux-android/debug/build/libc-test-ac0f7594ba6b2872/out/main.c:17106:24: error: incomplete result type 'prop_info' (aka 'struct prop_info') in function definition
  cargo:warning=             prop_info __test_roundtrip_prop_info(
  cargo:warning=                       ^
  cargo:warning=/android/ndk-i686/bin/../sysroot/usr/include/sys/system_properties.h:39:16: note: forward declaration of 'struct prop_info'
  cargo:warning=typedef struct prop_info prop_info;
  cargo:warning=               ^
  cargo:warning=/checkout/target/i686-linux-android/debug/build/libc-test-ac0f7594ba6b2872/out/main.c:17107:28: error: variable has incomplete type 'prop_info' (aka 'struct prop_info')
  cargo:warning=                 prop_info value, int32_t rust_size, int* error, unsigned char* pad
  cargo:warning=                           ^
  cargo:warning=/android/ndk-i686/bin/../sysroot/usr/include/sys/system_properties.h:39:16: note: forward declaration of 'struct prop_info'
  cargo:warning=typedef struct prop_info prop_info;
  cargo:warning=               ^
  cargo:warning=/checkout/target/i686-linux-android/debug/build/libc-test-ac0f7594ba6b2872/out/main.c:17110:33: error: invalid application of 'sizeof' to an incomplete type 'prop_info' (aka 'struct prop_info')
  cargo:warning=                int size = (int)sizeof(prop_info);
  cargo:warning=                                ^     ~~~~~~~~~~~
  cargo:warning=/android/ndk-i686/bin/../sysroot/usr/include/sys/system_properties.h:39:16: note: forward declaration of 'struct prop_info'
  cargo:warning=typedef struct prop_info prop_info;
  cargo:warning=               ^
  cargo:warning=5 errors generated.
```

I'm looking at the definition of `prop_info` but it seems quite special.

**Comment by flxo** [comment]
@devnexen Thanks for the PR. Any change to add 

* `__system_property_serial`
* `__system_property_area_serial`
* `__system_property_wait`

on the fly?

**Comment by JohnTitor** [comment]
Feel free to do a try build (`@\bors try`) if the next fails.
@bors r+ delegate+

**Comment by JohnTitor** [comment]
Note: Force-pushing will cancel a try build.

**Pull request merged**
