### PR TITLE
Add FIONCLEX and other FIO* constants for Linux, DragonFly and OpenBSD

### PR DESCRIPTION
**Pull request by tormol**
[OpenBSD header](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/sys/filio.h?annotate=1.5) | [DragonFly header](http://gitweb.dragonflybsd.org/dragonfly.git/blame/refs/heads/master:/sys/sys/filio.h) | [Linux search](https://github.com/torvalds/linux/search?q=FIONCLEX+FIOQSIZE&unscoped_q=FIONCLEX+FIOQSIZE&type=Code)
For Linux I've used [godbolt compiler explorer](https://godbolt.org/z/h-C7qM) to get final values where possible.

Wile this crate has FIOCLEX for Fuchsia, Emscripten and Redox, I've not added FIONCLEX for them because those targets appear to support neither.
I started adding FIOASYNC, FIOSETOWN and FIOGETOWN for all the Linux architectures, but gave up when I realized FIOASYNC is kind of deprecated and the other two useless without more symbols. If anybody is interested I have a [branch with how far I got](https://github.com/tormol/rust-libc/tree/sigio).

### CODE REVIEW

**Comment by gnzlbg** [comment]
Needs rebasing.

**Comment by tormol** [comment]
Done.

**Comment by gnzlbg** [comment]
@tormol three targets are failing, the failures look real.

**Comment by tormol** [comment]
Yes, I didn't check back yesterday, but I've started fixing them.

**Comment by tormol** [comment]
I've dropped the FIOQSIZE commit due to #1391 and the mistake making me doubt the values for the architectures that aren't tested.

I feel more certain about FIONCLEX as the value is similar to FIOCLEX.

**Comment by tormol** [comment]
Github didn't really show it, but I peeled off / removed the commit that added FIOQSIZE, and CI is now green.

**Pull request merged**
