### PR TITLE
Add killpg

### PR DESCRIPTION
**Pull request by SanchayanMaity**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like this may have a [different name on 32-bit OSX](https://travis-ci.org/rust-lang/libc/jobs/318169242)?

**Comment by SanchayanMaity** [comment]
@alexcrichton Do I need to put a cfg_attr to prevent this from being exposed on  i686  darwin?

**Comment by alexcrichton** [comment]
That could work, although it may just need a different `link_name` perhaps? There's a few other examples of doing this in `unix/mod.rs` which may indicate what the name should be?

**Comment by marioidival** [comment]
@alexcrichton this PR can be merged?

**Comment by alexcrichton** [comment]
@bors: r+

Indeed! Sorry for the delay!

**Pull request merged**
