### PR TITLE
apple: Add TIOC* constants

### PR DESCRIPTION
**Pull request by m4rw3r**
From `sys/ioctl.h`.

Extracted on OS X 10.11.3.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like some 32-bit values may have some different values? Otherwise looks good to me!

**Comment by alexcrichton** [comment]
Thanks! Also feel free to ping PRs when they're updated, unfortunately github doesn't send out notifications for those events :(

**Comment by m4rw3r** [comment]
@alexcrichton All windows builds fail on the `winapi` crate which seems to be unrelated.

**Pull request merged**
