### PR TITLE
Add some TCP constants

### PR DESCRIPTION
**Pull request by Fensteer**
Add some TCP constants according to the sources : https://github.com/freebsd/freebsd/blob/master/sys/netinet/tcp.h#L164

### CODE REVIEW

**Comment by asomers** [comment]
Did you check the DragonflyBSD sources?  I bet that many of these symbols are defined identically there.  If so, they belong in  `src/unix/bsd/freebsdlike/mod.rs`.  Unless, of course, NetBSD and OpenBSD also define them identically, in which case they can go in `src/unix/bsd/mod.rs`.

**Comment by Fensteer** [comment]
I tried to put it in `src/unix/bsd/mod.rs` but darwin targets failed: https://travis-ci.org/rust-lang/libc/builds/459839121
Dragonfly doesn't defined the same constants: https://github.com/DragonFlyBSD/DragonFlyBSD/blob/e7ab884bd49753f8884eb597d10d6569a08fa0df/sys/netinet/tcp_var.h#L164

**Comment by asomers** [comment]
That's the wrong file.  You want tcp.h, not tcp_var.h.  Dragonfly does define some of the same constants.
https://github.com/DragonFlyBSD/DragonFlyBSD/blob/e7ab884bd49753f8884eb597d10d6569a08fa0df/sys/netinet/tcp.h

**Comment by Fensteer** [comment]
Thanks for the file. I factor common TCP variables between different OS.
Sources: 
https://github.com/DragonFlyBSD/DragonFlyBSD/blob/master/sys/netinet/tcp.h#L156
https://github.com/freebsd/freebsd/blob/master/sys/netinet/tcp.h#L164
https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/netinet/tcp.h
https://github.com/openbsd/src/blob/master/sys/netinet/tcp.h#L126
https://github.com/bitrig/bitrig/blob/master/sys/netinet/tcp.h

**Comment by Fensteer** [comment]
Done, I tried to add TCP_CA_NAME_MAX but it's not available in userspace so I removed it.

**Comment by gnzlbg** [comment]
Could you rebase ?

**Comment by semarie** [comment]
FYI, it broke the build on OpenBSD (there is no CI). I am working on unbreak it

**Comment by gnzlbg** [comment]
Damn. Would it be possible to contribute an OpenBSD build bot to CI similar to how the FreeBSD build bot works ?

**Comment by asomers** [comment]
@gnzlbg Are you thinking of Nix's buildbot?  libc doesn't use buildbot, only Travis.  libc's FreeBSD builder runs in QEMU on Travis.  AFAIK the same technique should be possible for OpenBSD.

**Comment by semarie** [comment]
for FreeBSD, the CI does a crosscompilation from linux to freebsd, and run the executable via qemu. Last time I tried to do crosscompilation from linux to openbsd it was really difficult. Maybe it could be tested again as now we recently switched to clang + ld.lld.

**Comment by gnzlbg** [comment]
@asomers no I was thinking of what @semarie mentions, cross compiling from linux to OpenBSD and then running the binaries under qemu.

**Pull request merged**
