### PR TITLE
Fix getgrgid_r to accept gid_t.

### LINKED ISSUE #1320: `getgrgid_r` should accept gid_t instead of uid_t
https://linux.die.net/man/3/getgrgid_r

### PR DESCRIPTION
**Pull request by crlf0710**
Closes #1320.

### CODE REVIEW

**Comment by gnzlbg** [comment]
What are the types of `gid_t` and `uid_t` on each of the modified architectures?

**Comment by crlf0710** [comment]
````
L:\ThirdParty\rust\libc>rg type | rg gid_t
src\wasi.rs:pub type gid_t = u32;
src\fuchsia\mod.rs:pub type gid_t = u32;
src\redox\mod.rs:pub type gid_t = c_int;
src\unix\mod.rs:pub type gid_t = u32;

L:\ThirdParty\rust\libc>rg type | rg uid_t
src\wasi.rs:pub type uid_t = u32;
src\fuchsia\mod.rs:pub type uid_t = u32;
src\redox\mod.rs:pub type uid_t = c_int;
src\unix\mod.rs:pub type uid_t = u32;
src\unix\bsd\freebsdlike\dragonfly\mod.rs:pub type uuid_t = ::uuid;
````
Consistent!

**Comment by gnzlbg** [comment]
So this doesn't change any type, only the type alias used right?

**Comment by crlf0710** [comment]
Yes, i think so.

**Pull request merged**
