### PR TITLE
Add rtnetlink.h, if_link.h, if_addr.h to Android

### PR DESCRIPTION
**Pull request by tiann**
Here is the NDK header:

[rtnetlink.h](https://android.googlesource.com/platform/prebuilts/ndk/+/dev/platform/sysroot/usr/include/linux/rtnetlink.h)
[if_link.h](https://android.googlesource.com/platform/prebuilts/ndk/+/dev/platform/sysroot/usr/include/linux/if_link.h)
[if_addr.h](https://android.googlesource.com/platform/prebuilts/ndk/+/dev/platform/sysroot/usr/include/linux/if_addr.h)

It is the same with Linux header, so i copied it from:https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/mod.rs

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you squash commits into one?

**Review by JohnTitor — APPROVED** [review]
Thanks!

**Comment by tiann** [comment]
There are two problems:

1. `if_addr.h` header seems not included in x86 CI ? (I don't known how the CI generated the main.c, but i have checked the header, it is the same with aarch64...) All the IFA_* variable are not exist..
2. the CI used ndk is `ndk-21d`, the header `if_link.h` doesn't contain: `IFLA_PROP_LIST`, `IFLA_ALT_IFNAME`, `IFLA_PERM_ADDRESS`, `IFLA_PROTO_DOWN_REASON`

So i remove the if_addr.h temporarily, and i remove the four IFLA_* variable. There are two things to do:

1. upgrade the CI ndk toolchains.
2. fix if_addr.h

But i think the upgrade may occur other issues, after i fixed it, i will make another PRs

**Comment by JohnTitor** [comment]
You could tweak the test here to include additional headers:
https://github.com/rust-lang/libc/blob/f292633ab23ce415f270cd7908ff58863fcc6dbd/libc-test/build.rs#L1472

**Comment by tiann** [comment]
> You could tweak the test here to include additional headers:
> 
> https://github.com/rust-lang/libc/blob/f292633ab23ce415f270cd7908ff58863fcc6dbd/libc-test/build.rs#L1472

Thank you, i have updated the header

**Pull request merged**
