### PR TITLE
Add TIOCSBRK and TIOCCBRK

### PR DESCRIPTION
**Pull request by Susurrus**

### CODE REVIEW

**Comment by Susurrus** [comment]
Got a few errors on some platforms that just say "bash error XXX", so force-repushing to trigger a CI rerun. We'll see what happens.

**Comment by Susurrus** [comment]
Looks like fetching some packages is failing on some builds, not really certain why or if it's a temporary thing (I would assume so). I'll let it sit a couple of days and rerun again.

**Comment by gnzlbg** [comment]
@Susurrus can you take a look at the failure?

**Comment by Susurrus** [comment]
Don't know why that last one failed; couldn't tell what the error was. Force repushed to trigger a new CI run.

**Comment by Susurrus** [comment]
So it's failing due to timing out, but the platforms that didn't get tested that last time were passing earlier so I think this is ready to merge, just needs some playing with CI flakiness.

**Comment by Susurrus** [comment]
So, I've force-pushed twice and I'm still getting the same CI time-out failures. Don't know what to do to push this forward.

**Comment by Susurrus** [comment]
Anything I can do to keep this moving forward?

**Comment by Susurrus** [comment]
Anything I can do to keep this moving forward?

**Comment by Susurrus** [comment]
Looks like it's still failing, but looks like a package is failing to install on one of the builds. However, it's been rerun several times now, and I think it's all been the same failure. Is this affecting other PRs or what can we do to resolve this?

**Comment by Susurrus** [comment]
So now that `i686-apple-darwin` is not a Tier 1 target, that target fails in CI, but it's because the Rust installation fails, not due to this PR.

And `BuildChannelsOSX nightly` fails due to the `armv7-apple-ios` Rust target not being installed correctly. Is anyone actively working on resolving these failures? If not, is an appropriate fix to remove these targets, if so I can do that in this PR.

**Comment by Susurrus** [comment]
Only failing on `arm-linux-androideabi` with what looks to be an unrelated failure.

**Comment by JohnTitor** [comment]
The failure should be fixed by #1754, could you rebase?

**Comment by Susurrus** [comment]
CI finally passed!

**Pull request merged**
