### PR TITLE
Add a bunch of constants and functions which were missing on Android

### PR DESCRIPTION
**Pull request by qwandor-google**
These are all based on the latest corresponding Bionic headers, from https://cs.android.com/android/platform/superproject/+/master:bionic/.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Thanks for the PR! According to CI, it seems that we should also tweak libc-test to import header files (semver check can be ignored, we should fix that check but I have no bandwidth to do so currently, sorry!).

**Comment by qwandor-google** [comment]
Thanks. I've added the missing headers, though some of the errors from CI don't seem to be related to that so there may still be some issues. Unfortunately I haven't been able to get the tests to run locally, sorry for the spam.

**Comment by qwandor-google** [comment]
There is one remaining issue I haven't figured out yet, with sigtimedwait on aarch64 only. I can't see why this arch would be different. The symbol is in signal.h, so shouldn't be arch-specific. It was introduced in API version 23, and android-install-ndk.sh sets version 24 on all Arm architectures or 28 on x86 architectures. Any idea what's going wrong here?

**Comment by JohnTitor** [comment]
> There is one remaining issue I haven't figured out yet, with sigtimedwait on aarch64 only. I can't see why this arch would be different.

Possibly related to #1765, I'd skip test for aarch64 at this point as it's obviously safe to ship, I think. Other stuff looks good, r=me once that point is resolved and you squash commits.

**Comment by qwandor-google** [comment]
Okay, skipping the `sigtimedwait` test for aarch64. What would you like squashed? Commits all have descriptions and should build at each step of the way, and CONTRIBUTING.md doesn't say anything about a policy on squashing. I can squash everything into one commit if you like, but I figured the individual descriptions would be more useful.

**Comment by JohnTitor** [comment]
> I figured the individual descriptions would be more useful.

I'd prefer to avoid history-noise than to remain each description except for CI stuff.

**Pull request merged**
