### PR TITLE
Bump libc-test version to match libc

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you also update the version of the libc dependency? It rarely happens but just in case I'd avoid a potential version mismatching.

**Comment by joshtriplett** [comment]
On Thu, Aug 04, 2022 at 02:05:40AM -0700, Yuki Okushi wrote:
> Could you also update the version of the libc dependency? It rarely happens but just in case I'd avoid a potential version mismatching.

Done.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!
@bors r+

**Comment by JohnTitor** [comment]
@Amanieu Could you take care of the new release?

**Pull request merged**
