### PR TITLE
[0.2] Backports

### PR DESCRIPTION
**Pull request by tgross35**
Backport the following Solaris changes:

- https://github.com/rust-lang/libc/pull/3864
- https://github.com/rust-lang/libc/pull/3999
- https://github.com/rust-lang/libc/pull/4004

Also cherry picks the backport of https://github.com/rust-lang/libc/pull/3634 so this can start before https://github.com/rust-lang/libc/pull/4016 merges.

### CODE REVIEW

**Comment by tgross35** [comment]
Including https://github.com/rust-lang/libc/pull/4019 so this can merge without conflict

**Comment by tgross35** [comment]
It was not mentioned specifically but Solaris does not have `flock`, so having that exposed was a bug. The relevant PR is https://github.com/rust-lang/libc/pull/3864.

**Comment by pfmooney** [comment]
But removing the `flock`-related defines from illumos would still be breaking.

**Comment by tgross35** [comment]
They should not have been removed from illumos right? https://github.com/rust-lang/libc/blob/0f9f8c91adb0365c0d13b34ec27ac8019818cf1f/src/unix/mod.rs#L1573

**Comment by pfmooney** [comment]
Sorry, I misread and through the `LOCK_`* bits had gotten lost in the shuffle.

**Pull request merged**
