### PR TITLE
Add offsets in user_regs_struct from sys/reg.h

### PR DESCRIPTION
**Pull request by marmistrz**

### CODE REVIEW

**Comment by marmistrz** [comment]
I had to add `sys/reg.h` to `libc-test/build.rs`. Hopefully this will pass all the tests right now.

**Comment by marmistrz** [comment]
It seems that `sys/reg.h` is only on x86 and x86_64. Restricted cfg.header to those platforms

**Comment by marmistrz** [comment]
Oh, there was no flag defined for `x86`. Fixed that.

**Comment by marmistrz** [comment]
What about making a new release? I guess we'll need this in nix-rust/nix#666

**Comment by alexcrichton** [comment]
Sure, instructions are [in the README](https://github.com/rust-lang/libc#releasing-your-change-to-cratesio)

**Pull request merged**
