### PR TITLE
linux/android adding seccomp filter and data types.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by JohnTitor** [comment]
```
   cargo:warning=/checkout/target/i686-unknown-linux-musl/debug/build/libc-test-ba81c310cd2e4aa5/out/main.c:24969:93: error: 'SECCOMP_FILTER_FLAG_NEW_LISTENER' undeclared here (not in a function); did you mean 'SECCOMP_FILTER_FLAG_TSYNC'?
  cargo:warning=24969 |             static const unsigned  long __test_const_SECCOMP_FILTER_FLAG_NEW_LISTENER_val = SECCOMP_FILTER_FLAG_NEW_LISTENER;
  cargo:warning=      |                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                                             SECCOMP_FILTER_FLAG_TSYNC
  cargo:warning=/checkout/target/i686-unknown-linux-musl/debug/build/libc-test-ba81c310cd2e4aa5/out/main.c:25005:81: error: 'SECCOMP_RET_USER_NOTIF' undeclared here (not in a function); did you mean 'SECCOMP_RET_ERRNO'?
  cargo:warning=25005 |             static const unsigned int __test_const_SECCOMP_RET_USER_NOTIF_val = SECCOMP_RET_USER_NOTIF;
  cargo:warning=      |                                                                                 ^~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                                 SECCOMP_RET_ERRNO
  cargo:warning=cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
  cargo:warning=cc1: all warnings being treated as errors
```

I think musl's kernel header is old and doesn't seem to have them, we should skip tests for now.

**Comment by JohnTitor** [comment]
I mean we can add them with a tweak to the test, does it work for you to drop them?

**Comment by devnexen** [comment]
yes that s fine for now.

**Comment by JohnTitor** [comment]
Alright, @bors r+

**Pull request merged**
