### PR TITLE
add dirfd on unix

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
Ah looks like this may not be defined on rumprun?

**Comment by Mic92** [comment]
Interesting, because dirfd already appeared in 4.2BSD in 1983.

**Comment by Mic92** [comment]
How can I exclude rumprun, but include netbsd?

**Comment by alexcrichton** [comment]
I think there should be some examples in the netbsd module as well but the gist is to use target_vendor in the cfg.

Dunno what's up with rumprun to cause this failure...

**Comment by Susurrus** [comment]
@Mic92 Want to try pushing this again and seeing if it was a CI glitch? It'd be great to get this supported so we can support it in nix-rust/nix also.

**Comment by Mic92** [comment]
still the same problem.

**Comment by Susurrus** [comment]
`dirfd` is declared in `dirent.h` in NetBSD. This header file is included by the `build.rs` script in `libc-test`. So I'm not certain what's the problem, though I'm not too familiar with the testing framework used by `libc`. @alexcrichton Any other ideas?

**Comment by Susurrus** [comment]
Could it be because `dirfd` is actually a macro on NetBSD? [Source](http://cvsweb.netbsd.org/bsdweb.cgi/src/include/dirent.h?rev=1.36&content-type=text/x-cvsweb-markup&only_with_tag=MAIN)

**Comment by alexcrichton** [comment]
Want to just duplicate it to each platform and leave it out on NetBSD?

**Comment by Susurrus** [comment]
I think the correct solution here is to just skip the check for this function on NetBSD. There's already precedent for this with many other functions.

Additionally it might be worth pinging some people in the NetBSD IRC and seeing if our understanding here is correct.

**Comment by Mic92** [comment]
In nix we can just inline the netbsd macro.

**Comment by Susurrus** [comment]
I would have suggested inlining that macro within `libc` instead of in a higher-level library as libraries will probably expect it to exist in `libc` on that platform. Would that be rejected if it was submitted in a separate PR?

**Comment by alexcrichton** [comment]
Nah yeah we typically include macros for other platforms for common functionality, so including that for netbsd sounds fine by me!

**Comment by Susurrus** [comment]
@Mic92 Could I convince you to file an additional PR bringing `dirfd` to NetBSD as well? :-)

**Comment by Mic92** [comment]
@Susurrus ^

**Pull request merged**
