### PR TITLE
Add strdup extern

### PR DESCRIPTION
**Pull request by meh**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ bcb7c48ca108219357b32f77bf53dcfbc6c43d77

Thanks!

**Comment by alexcrichton** [comment]
Hm not sure what's up with the automation recently, but looks like CI all passed where relevant, so merging.

**Comment by meh** [comment]
Did you misclick? Because I'm pretty sure you just closed the pull request instead of merging it :panda_face:

**Comment by alexcrichton** [comment]
Gah! sorry about that

**Pull request merged**
