### PR TITLE
linux: add additional netlink interface attribute tags

### PR DESCRIPTION
**Pull request by tones111**

### CODE REVIEW

**Comment by tones111** [comment]
It looks like this change depends on a newer version of linux api headers than what the CI is using.  What kernel version is the libc crate attempting to target?

**Comment by JohnTitor** [comment]
> What kernel version is the libc crate attempting to target?

You could check it at https://github.com/rust-lang/libc/tree/master/ci/docker and related files under the ci dir.
Anyway, it's totally fine to skip tests for them until we bump the image. Could you add the consts here with a comment?
https://github.com/rust-lang/libc/blob/72fba0ecc76bf385d8f7b687fa8e46a1f6c0ae43/libc-test/build.rs#L3385

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thank you! @bors r+

**Pull request merged**
