### PR TITLE
add AT_* constants

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ah unfortunately CI is acting up, but I'll r+ once we've sorted those issues out. Thanks for the PR though!

**Comment by alexcrichton** [comment]
Ah yes I think nightlies are now fixed so...

@bors: retry

**Comment by alexcrichton** [comment]
Aha now *that* looks like a legitimate error!

**Comment by Mic92** [comment]
fixed now.

**Comment by Mic92** [comment]
request for @bors: r+

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
