### PR TITLE
haiku add sockaddr_dl type

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
how to pass the semver issue in your opinion ?

**Comment by Amanieu** [comment]
I think this is blocked on #2383

cc @JohnTitor

**Comment by JohnTitor** [comment]
Semver check doesn't block bors, there's a failure on sparc64 and it's timeout: `qemu-system-sparc64: terminating on signal 15 from pid 3413 (timeout)`

@bors retry

**Comment by JohnTitor** [comment]
```
error[E0124]: field `sdl_slen` is already declared
   --> src/unix/haiku/mod.rs:333:9
    |
326 |         pub sdl_slen: u8,
    |         ---------------- `sdl_slen` first declared here
...
333 |         pub sdl_slen: u8,
    |         ^^^^^^^^^^^^^^^^ field already declared

For more information about this error, try `rustc --explain E0124`.
error: could not compile `libc` due to previous error
```

**Pull request merged**
