### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by asomers**
These two messages got accidentally swapped in PR #2545

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by asomers** [comment]
I think bors is confused because the tests aren't getting run.  Can you bypass bors and merge directly?

**Comment by JohnTitor** [comment]
Could you remove the `skip-ci` prefix instead? I'd like to manage Git history with bors as possible.

**Comment by asomers** [comment]
As you wish

**Comment by JohnTitor** [comment]
Great, thank you! @bors r+

**Pull request merged**
