### PR TITLE
Macos rawsock

### PR DESCRIPTION
**Pull request by qrnch-jan**
Add some types needed for raw socket access on macos.

### CODE REVIEW

**Comment by qrnch-jan** [comment]
All I see in the error log under "Execute run.sh" is:

```
Error: 
```

I am at a loss as to what action I should take next.

**Comment by Amanieu** [comment]
I can see the log just fine, maybe it's an issue with your browser? In any case the error seems to be due to a missing header file, you might need to add it in libc-test/build.rs.

```
The following warnings were emitted during compilation:

warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23738:64: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_ndrv'
warning:              uint64_t __test_size_sockaddr_ndrv(void) { return sizeof(struct sockaddr_ndrv); }
warning:                                                                ^     ~~~~~~~~~~~~~~~~~~~~~~
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23738:78: note: forward declaration of 'struct sockaddr_ndrv'
warning:              uint64_t __test_size_sockaddr_ndrv(void) { return sizeof(struct sockaddr_ndrv); }
warning:                                                                              ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23742:40: error: field has incomplete type 'struct sockaddr_ndrv'
warning:                   struct sockaddr_ndrv v;
warning:                                        ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23742:26: note: forward declaration of 'struct sockaddr_ndrv'
warning:                   struct sockaddr_ndrv v;
warning:                          ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23752:28: error: offsetof of incomplete type 'struct sockaddr_ndrv'
warning:                     return offsetof(struct sockaddr_ndrv, snd_len);
warning:                            ^        ~~~~~~
warning: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/stddef.h:104:24: note: expanded from macro 'offsetof'
warning: #define offsetof(t, d) __builtin_offsetof(t, d)
warning:                        ^                  ~
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23752:44: note: forward declaration of 'struct sockaddr_ndrv'
warning:                     return offsetof(struct sockaddr_ndrv, snd_len);
warning:                                            ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23756:38: error: incomplete definition of type 'struct sockaddr_ndrv'
warning:                     return sizeof(foo->snd_len);
warning:                                   ~~~^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23755:28: note: forward declaration of 'struct sockaddr_ndrv'
warning:                     struct sockaddr_ndrv* foo = NULL;
warning:                            ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23760:80: error: declaration of 'struct sockaddr_ndrv' will not be visible outside of this function [-Werror,-Wvisibility]
warning:                  unsigned char* __test_field_type_sockaddr_ndrv_snd_len(struct sockaddr_ndrv* b) {
warning:                                                                                ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23761:30: error: incomplete definition of type 'struct sockaddr_ndrv'
warning:                     return &b->snd_len;
warning:                             ~^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23760:80: note: forward declaration of 'struct sockaddr_ndrv'
warning:                  unsigned char* __test_field_type_sockaddr_ndrv_snd_len(struct sockaddr_ndrv* b) {
warning:                                                                                ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23766:28: error: offsetof of incomplete type 'struct sockaddr_ndrv'
warning:                     return offsetof(struct sockaddr_ndrv, snd_family);
warning:                            ^        ~~~~~~
warning: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/stddef.h:104:24: note: expanded from macro 'offsetof'
warning: #define offsetof(t, d) __builtin_offsetof(t, d)
warning:                        ^                  ~
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23766:44: note: forward declaration of 'struct sockaddr_ndrv'
warning:                     return offsetof(struct sockaddr_ndrv, snd_family);
warning:                                            ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23770:38: error: incomplete definition of type 'struct sockaddr_ndrv'
warning:                     return sizeof(foo->snd_family);
warning:                                   ~~~^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23769:28: note: forward declaration of 'struct sockaddr_ndrv'
warning:                     struct sockaddr_ndrv* foo = NULL;
warning:                            ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23774:83: error: declaration of 'struct sockaddr_ndrv' will not be visible outside of this function [-Werror,-Wvisibility]
warning:                  unsigned char* __test_field_type_sockaddr_ndrv_snd_family(struct sockaddr_ndrv* b) {
warning:                                                                                   ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23775:30: error: incomplete definition of type 'struct sockaddr_ndrv'
warning:                     return &b->snd_family;
warning:                             ~^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23774:83: note: forward declaration of 'struct sockaddr_ndrv'
warning:                  unsigned char* __test_field_type_sockaddr_ndrv_snd_family(struct sockaddr_ndrv* b) {
warning:                                                                                   ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23780:28: error: offsetof of incomplete type 'struct sockaddr_ndrv'
warning:                     return offsetof(struct sockaddr_ndrv, snd_name);
warning:                            ^        ~~~~~~
warning: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/stddef.h:104:24: note: expanded from macro 'offsetof'
warning: #define offsetof(t, d) __builtin_offsetof(t, d)
warning:                        ^                  ~
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23780:44: note: forward declaration of 'struct sockaddr_ndrv'
warning:                     return offsetof(struct sockaddr_ndrv, snd_name);
warning:                                            ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23784:38: error: incomplete definition of type 'struct sockaddr_ndrv'
warning:                     return sizeof(foo->snd_name);
warning:                                   ~~~^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23783:28: note: forward declaration of 'struct sockaddr_ndrv'
warning:                     struct sockaddr_ndrv* foo = NULL;
warning:                            ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23788:81: error: declaration of 'struct sockaddr_ndrv' will not be visible outside of this function [-Werror,-Wvisibility]
warning:                  unsigned char(*__test_field_type_sockaddr_ndrv_snd_name(struct sockaddr_ndrv* b))[16] {
warning:                                                                                 ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23789:30: error: incomplete definition of type 'struct sockaddr_ndrv'
warning:                     return &b->snd_name;
warning:                             ~^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23788:81: note: forward declaration of 'struct sockaddr_ndrv'
warning:                  unsigned char(*__test_field_type_sockaddr_ndrv_snd_name(struct sockaddr_ndrv* b))[16] {
warning:                                                                                 ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23798:35: error: incomplete result type 'struct sockaddr_ndrv' in function definition
warning:              struct sockaddr_ndrv __test_roundtrip_sockaddr_ndrv(
warning:                                   ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23798:21: note: forward declaration of 'struct sockaddr_ndrv'
warning:              struct sockaddr_ndrv __test_roundtrip_sockaddr_ndrv(
warning:                     ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23799:39: error: variable has incomplete type 'struct sockaddr_ndrv'
warning:                  struct sockaddr_ndrv value, int32_t rust_size, int* error, unsigned char* pad
warning:                                       ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23798:21: note: forward declaration of 'struct sockaddr_ndrv'
warning:              struct sockaddr_ndrv __test_roundtrip_sockaddr_ndrv(
warning:                     ^
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23802:33: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_ndrv'
warning:                 int size = (int)sizeof(struct sockaddr_ndrv);
warning:                                 ^     ~~~~~~~~~~~~~~~~~~~~~~
warning: /Users/runner/work/libc/libc/target/x86_64-apple-darwin/debug/build/libc-test-09dfc1ba0d34a6d6/out/main.c:23798:21: note: forward declaration of 'struct sockaddr_ndrv'
warning:              struct sockaddr_ndrv __test_roundtrip_sockaddr_ndrv(
warning:                     ^
warning: 17 errors generated.
```

**Comment by qrnch-jan** [comment]
Ah, yes -- a javascript domain was being blocked.

**Comment by qrnch-jan** [comment]
Will github automatically rerun the merge check each time I push a commit to this branch?

**Pull request merged**
