### PR TITLE
type change for AF_INET, PF_INET  AF_INET6 PF_INET6

### PR DESCRIPTION
**Pull request by sum12**
I am not sure if this change is enough or more is needed fo #468

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hey, thanks for the PR! But this is a breaking change, as Alex said, and I'd hold off this as we currently have no plan to make a release 0.3 or 1.0.

**Comment by sum12** [comment]
ok. Thanks for taking a look. 
Any other ways I could contribute   ?

**Comment by JohnTitor** [comment]
> Any other ways I could contribute ?

Basically we add items when we need them. There're some requests on the issue tracker that someone wants to use constants or functions, I think they're good stuff to contribute (btw, if you want to contribute to Rust, there're some repos like rust-lang/rust that have more newcomer welcome issues).

**Comment by joshtriplett** [comment]
Even if we were making breaking changes, I don't think we'd want to change the types of these particular constants and not others in the same category.

In C, these are preprocessor symbols, and they don't have a type. I don't think this kind of change is worth the breakage it would cause.

**Comment by safinaskar** [comment]
Now this can be resent to libc 0.3

**Pull request closed without merging**
