### PR TITLE
Combined CI fixes

### PR DESCRIPTION
**Pull request by tgross35**
Combine the following to fix CI in one go:

- https://github.com/rust-lang/libc/pull/3794 (cc @joshtriplett)
- https://github.com/rust-lang/libc/pull/3796/commits/cc2fa87d8ecb74aab0a789e9f1e1fe4909a8fd7d (cc @nyurik)
- https://github.com/rust-lang/libc/pull/3578 (cc @devnexen)

Once this succeeds, we can cherry pick to the 0.2 branch.

### CODE REVIEW

**Comment by tgross35** [comment]
Hm, still a MacOS failure.

**Comment by tgross35** [comment]
The failure at https://github.com/rust-lang/libc/actions/runs/10310339998/job/28541913762?pr=3797 seems to be from the changes to the rust-lang/rust workspaces. The fix was merged yesterday so should be available on today's nightly, which will be available in a couple hours. Will retry the job then.

**Comment by tgross35** [comment]
I guess the fix was merged yesterday https://github.com/rust-lang/cargo/pull/14370, but the update to rust-lang/rust _just_ missed the cutoff for the most recent nightly https://github.com/rust-lang/rust/pull/128827#issuecomment-2276930231. ~10 hours to get a newer nightly and try again.

**Comment by tgross35** [comment]
Got the new nightly, but it looks like there is a new duplicate symbol failure.

**Comment by nyurik** [comment]
Each day libc CI crashes in a creative, fun, but always in a different way...

**Comment by tgross35** [comment]
Backported https://github.com/rust-lang/libc/pull/3806 with the exception of 56d665c9b3f7687eb206c3a1d2f943852df65f54 ("macOs various updates"), which turned out to not be needed.

**Pull request merged**
