### PR TITLE
Add missing stack size functions on Linux

### PR DESCRIPTION
**Pull request by carbotaniuman**

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you also include them in https://github.com/rust-lang/libc/tree/master/libc-test/semver?

**Comment by carbotaniuman** [comment]
Updated!

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Sorry for the delay and thank you for the PR!
@bors r+

**Comment by JohnTitor** [comment]
Maybe emscripten doesn't have it, could you check?

**Comment by JohnTitor** [comment]
Triage: Closing as inactive, feel free to reopen/resubmit if you're still interested in this change. Thank you!

**Pull request closed without merging**
