### PR TITLE
NetBSD: add two more errno values

### PR DESCRIPTION
**Pull request by 0-wiz-0**
available in NetBSD-current since 2020

### CODE REVIEW

**Comment by workingjubilee** [comment]
Why would this be a "breakage candidate"? Because it changes `ELAST`? `ELAST` on OS that use this convention is defined as being the largest errno. It's only intended to be used to allow checks to see if an error is within the known values for errno, and things of that nature, it's not really directly used by any API. It is "versioning in userspace", as it were.

**Comment by JohnTitor** [comment]
> Why would this be a "breakage candidate"? Because it changes `ELAST`? `ELAST` on OS that use this convention is defined as being the largest errno. It's only intended to be used to allow checks to see if an error is within the known values for errno, and things of that nature, it's not really directly used by any API. It is "versioning in userspace", as it were.

Yes, and I think it _could_ cause a bug (or any weird behavior due to lack of errno) if the last value points to a newer number while the user env is older.
As you mentioned on https://github.com/rust-lang/libc/issues/3131, we just should not provide such a const, I think.

**Comment by workingjubilee** [comment]
Noting that https://github.com/rust-lang/libc/pull/1902 was handled by leaving the value in place and deprecating it, though that time we said we'd change it.

**Comment by JohnTitor** [comment]
@0-wiz-0 Could you apply this?

> * Merge this change with the updated `ELAST` value, but also with a deprecation notice. People who are using `ELAST` "correctly" don't have to change anything immediately, so it doesn't introduce bugs in code that was written to be future-proof, but they can use the deprecation notice to prepare. People who were using it incorrectly have a heads up.

@rustbot author

**Comment by 0-wiz-0** [comment]
@JohnTitor I've added a deprecation warning as requested. Did I do it correctly?

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Yeah, thanks!
@bors r+

**Pull request merged**
