### PR TITLE
Deprecate _pad field on siginfo_t

### PR DESCRIPTION
**Pull request by alex**
As discussed in https://github.com/rust-lang/libc/pull/1316

### CODE REVIEW

**Comment by alex** [comment]
Hmm, what's teh appropriate way to wrap this long line?

**Comment by gnzlbg** [comment]
You can just break line at `since` and `note`.

Could you add the methods to access the field here as well ? The note should tell people to report here with their use case, and that they can upgrade their code to use the methods instead (but the available methods might not be enough).

**Comment by alex** [comment]
A method to access `_pad` you mean?

**Comment by gnzlbg** [comment]
I mean a method like `si_addr` in the other PR. 

The problem is, we are telling people that `pad` is deprecated, so when they see that message, they would be like "ok, I shouldn't use pad, what should I use instead?". That's a fair question. Ideally, we would have enough methods implemented already so that we can just tell people to use the type's methods to access the appropriate fields. 

That might not be feasible to do right now, and not all methods might be needed, but at least we should be able to tell people that "if you need a method that's not available, look how `si_addr` is implemented, and please submit a PR with the method you need and we will release that quickly", to minimize friction.  

Only after everybody is able to port their code can we make the method private, and then continue the refactor towards using an union when possible.

**Comment by gnzlbg** [comment]
So this LGTM. @bors: r+

**Pull request merged**
