### PR TITLE
Add Dockerfile for riscv64-unknown-linux-gnu

### PR DESCRIPTION
**Pull request by fintelia**
See #1415

### CODE REVIEW

**Comment by gnzlbg** [comment]
Note that this is not tested on CI, that would require adding a build job to .travis.yml. Is that intended ?

**Comment by fintelia** [comment]
Not intended so much as I just wasn't sure how to add the job to CI. I'll make that change in a bit

**Comment by gnzlbg** [comment]
I've restarted this particular build: https://travis-ci.com/rust-lang/libc/jobs/212378258

**Comment by fintelia** [comment]
That runs into a sort of circular issue: there isn't a riscv64gc-unknown-linux-gnu target yet because the standard library can't be compiled for 64-bit RISC-V. And the standard library can't be build for it because libc doesn't yet support it.

Perhaps there'd be a way to temporarily use the risc64gc-unknown-none-elf target?

**Comment by mati865** [comment]
@fintelia to add new CPU and target at same time you have to fix and test everything locally using by building Rust with modified dependencies (like patched libc), get dependencies fixes merged, get new target merged and finally add tests everywhere once the target works.

**Comment by fintelia** [comment]
@mati865 That makes more sense

**Comment by gnzlbg** [comment]
@fintelia my recommendation is to add it as a libcore target only first to rust-lang/rust . That requires adding a target specification to rust-lang/rust/src/librustc_target, and not much more. Once that is done, libc is no_std, so it can be built against that. Once you have libcore and libc working, getting support for liballoc shouldn't be hard, you can just shim out to libc::malloc. The largest chunk of work is getting libstd support, depending on how similar this is to other unix targets, might be a breeze or not.

**Comment by mati865** [comment]
Good point, I didn't know you can make something as big as `*-unknown-linux-gnu` std-less.

**Comment by gnzlbg** [comment]
> Good point, I didn't know you can make something as big as *-unknown-linux-gnu std-less.

If the target isn't tier2, nothing is built, and then you have to build it with xargo, which you can use to build libcore only. So... it kind of works by omission 😆

**Comment by fintelia** [comment]
Where is the tier listing actually specified in the rustc source? It seems that just adding a target spec file and including it in the [supported_targets!](https://github.com/rust-lang/rust/blob/6ea4036cd20a4b1ab1d56e555108c21735ff6946/src/librustc_target/spec/mod.rs#L330) macro is enough to cause `./x.py build` to try building the standard library for that target

**Comment by gnzlbg** [comment]
@fintelia you need to set `no_std = true` for your target here: https://github.com/rust-lang/rust/blob/03bd2f653f0d0adb69d862fbeec64663157e71e1/src/bootstrap/sanity.rs#L171

**Comment by gnzlbg** [comment]
This needs rebasing. What was previously in the `.travis.yml` needs to be moved to `ci/azure.yml` (check out how the other targets are added there - should be pretty similar).

**Comment by gnzlbg** [comment]
ping

**Comment by fintelia** [comment]
Sorry for the delay on this. I don't think I'm going to have a chance to go through all of the steps to get this together in the near term so if anyone else is interested feel free to take over

**Comment by gnzlbg** [comment]
@msizanoen1 please feel free to fork this branch and update it as you see fit and submit a PR.

**Comment by msizanoen1** [comment]
Actually getting std to compile for riscv64 is pretty simple: https://github.com/rust-lang/rust/compare/master...msizanoen1:riscv-std

**Comment by JohnTitor** [comment]
The dockerfile is added by #1684 and I'm closing this in favor of it, thanks for contributing!

**Pull request closed without merging**
