### PR TITLE
Disable broken targets

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
r? me

**Comment by mati865** [comment]
It's broken, you should call infra.

**Comment by gnzlbg** [comment]
@pietroalbini I see that GA is already active. Maybe that messed up bors somehow ? AFAICT rust-central-station is still using Azure, which is still correct.

**Comment by mati865** [comment]
Can you retry any i686 windows-gnu build before disabling it?
I'm curious if LLVM backport has fixed it.

**Comment by mati865** [comment]
Still broken, thanks for testing.
I'll update https://github.com/rust-lang/libc/issues/1592#issuecomment-553351104

**Comment by pietroalbini** [comment]
I'll take a look tomorrow.

**Comment by pietroalbini** [comment]
Let me investigate.

@gnzlbg can you delegate me for this PR? It should be `@bors delegate=pietroalbini}.

**Comment by pietroalbini** [comment]
@gnzlbg hmm, now it seems to be unstuck, but synchronization added failed PRs to the queue. Can you `@bors r- retry` the failed ones in https://buildbot2.rust-lang.org/homu/queue/libc ?

**Comment by gnzlbg** [comment]
@pietroalbini looks like its working now

**Comment by gnzlbg** [comment]
What did you do to "unstuck" bors ?

**Comment by pietroalbini** [comment]
@gnzlbg hit the "synchronize" button in the queue page. That button flushes all the cache bors has about a repo, forcing it to scrape all the open PRs again. It usually solves most of the problems, but it's a bit buggy (as you saw with the failed PRs being queued again). It should be used as a last resort, and it's usually best to ping us before hitting it.

**Comment by gnzlbg** [comment]
Thanks for fixing this!

**Pull request merged**
