### PR TITLE
Upgrade crate version to 0.2.103

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
If you can release a new version, it'd be awesome! :)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
ping @JohnTitor

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Sorry for the delay!
@bors r+

**Comment by GuillaumeGomez** [comment]
Network error. :)

**Comment by GuillaumeGomez** [comment]
```console
 cargo:rustc-cfg=libc_union
     Running `rustc --crate-name libc src/lib.rs --color never --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=67fbccdd649ddc45 -C extra-filename=-67fbccdd649ddc45 --out-dir /home/runner/work/libc/libc/target/armv7-unknown-linux-musleabihf/debug/deps --target armv7-unknown-linux-musleabihf -C incremental=/home/runner/work/libc/libc/target/armv7-unknown-linux-musleabihf/debug/incremental -L dependency=/home/runner/work/libc/libc/target/armv7-unknown-linux-musleabihf/debug/deps -L dependency=/home/runner/work/libc/libc/target/debug/deps --cfg freebsd11 --cfg libc_deny_warnings --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid`
cargo:rustc-cfg=libc_const_size_of
cargo:rustc-cfg=libc_align
cargo:rustc-cfg=libc_core_cvoid
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-unknown-linux-musleabihf` target may not be installed
```

**Pull request merged**
