### PR TITLE
add missing STATX_ATTR_* constants on gnu/linux

### PR DESCRIPTION
**Pull request by SteveLauC**
Corresponds to [this](https://github.com/torvalds/linux/blob/master/include/uapi/linux/stat.h#L189~L191):

```c
#define STATX_ATTR_MOUNT_ROOT		0x00002000 /* Root of a mount */
#define STATX_ATTR_VERITY		0x00100000 /* [I] Verity protected file */
#define STATX_ATTR_DAX			0x00200000 /* File is currently in DAX state */
```

### CODE REVIEW

**Comment by SteveLauC** [comment]
Sure thing! Done

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by SteveLauC** [comment]
[Docker Linux Tier2 (sparc64-unknown-linux-gnu)](https://github.com/rust-lang/libc/actions/runs/3212393818/jobs/5251253386#logs) failed:
```
cargo:warning=/checkout/target/sparc64-unknown-linux-gnu/debug/build/libc-test-468391f68ffdbc78/out/main.c:42209:71: error: 'STATX_ATTR_MOUNT_ROOT' undeclared here (not in a function); did you mean 'STATX_ATTR_AUTOMOUNT'?
  cargo:warning=42209 |             static const int __test_const_STATX_ATTR_MOUNT_ROOT_val = STATX_ATTR_MOUNT_ROOT;
  cargo:warning=      |                                                                       ^~~~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                                                       STATX_ATTR_AUTOMOUNT
  cargo:warning=/checkout/target/sparc64-unknown-linux-gnu/debug/build/libc-test-468391f68ffdbc78/out/main.c:42215:67: error: 'STATX_ATTR_VERITY' undeclared here (not in a function)
  cargo:warning=42215 |             static const int __test_const_STATX_ATTR_VERITY_val = STATX_ATTR_VERITY;
  cargo:warning=      |                                                                   ^~~~~~~~~~~~~~~~~
  cargo:warning=/checkout/target/sparc64-unknown-linux-gnu/debug/build/libc-test-468391f68ffdbc78/out/main.c:42221:64: error: 'STATX_ATTR_DAX' undeclared here (not in a function); did you mean 'STATX_ATTR_NODUMP'?
  cargo:warning=42221 |             static const int __test_const_STATX_ATTR_DAX_val = STATX_ATTR_DAX;
  cargo:warning=      |                                                                ^~~~~~~~~~~~~~
  cargo:warning=      |                                                                STATX_ATTR_NODUMP
  cargo:warning=cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
  cargo:warning=cc1: all warnings being treated as errors
  exit status: 1
```

Honestly and sadly, I have no idea why these constants are not found on it

**Comment by JohnTitor** [comment]
Because SPARC64 image on CI is old and doesn't know them:
https://github.com/rust-lang/libc/blob/a0ff4d25d8a2aacb48116ee3b24201da16317d4b/ci/docker/sparc64-unknown-linux-gnu/Dockerfile#L1-L2

You could ignore them on SPARC64 for now.

**Comment by SteveLauC** [comment]
> Because SPARC64 image on CI is old and doesn't know them:
> 
> https://github.com/rust-lang/libc/blob/a0ff4d25d8a2aacb48116ee3b24201da16317d4b/ci/docker/sparc64-unknown-linux-gnu/Dockerfile#L1-L2
> 
> You could ignore them on SPARC64 for now.

Thanks for showing me this. Then let's wait for a glibc update on sparc64.

**Comment by JohnTitor** [comment]
I don't think we have to wait as it's just our CI issue. And these should be the same as on other archs, right? Then ignoring test for SPARC64 won't make a major issue here.

**Comment by SteveLauC** [comment]
>  Then ignoring test for SPARC64 won't make a major issue here.

Yes. I am sorry that I misunderstand you at first. Added them to `build.rs`

**Comment by JohnTitor** [comment]
Timeout, @bors retry

**Pull request merged**
