### PR TITLE
Add backtrace definitions and support for statvfs

### PR DESCRIPTION
**Pull request by 0323pin**
This allows successful build and use of file deletion, a.k.a. _move to trash_ 

Tested with source build of `simp` with the **trash** feature enabled.
Without this commit, `simp` fails to build on NetBSD when the **trash** feature is enabled.

Moving a file to the trash bin:
2023-09-23-151144_1366x768_scrot

Verifying its existence in the trash bin:
2023-09-23-151421_1366x768_scrot

### CODE REVIEW

**Comment by 0323pin** [comment]
🎉 All checks have passed 😃

**Comment by JohnTitor** [comment]
1. Edit the related semver file as stated in the PR template, please read it first.
2. Have you ensured the link item is available on the minimal NetBSD environment? If not, this change would break someone's code.

**Comment by 0323pin** [comment]
> 1. Edit the related semver file as stated in the PR template, please read it first.

Done, I've added the new symbols to semver now.

> 2. Have you ensured the link item is available on the minimal NetBSD environment? If not, this change would break someone's code.

Yes, these are available in the base OS, so they are available on a minimal environment.

**Comment by JohnTitor** [comment]
Great, could you squash commits into one too?

**Comment by 0323pin** [comment]
> Great, could you squash commits into one too?

I don't know how to do that 😢 
Need to look into it later.

**Comment by 0323pin** [comment]
@JohnTitor I'm not really sure on how to do this as I've synced my fork with master in between my commits.

This is how it looks like at my end,

2023-09-24-150227_1366x768_scrot

Can't you simply use _squash and merge_ at your end?

**Comment by JohnTitor** [comment]
> Can't you simply use _squash and merge_ at your end?

Sadly no, we use the bot named `@bors` to run full CI and merge.

**Comment by 0323pin** [comment]
@JohnTitor Is this ok?

If not, it's probably easier for me to start from a new fork and do a new pull request.

**Comment by 0323pin** [comment]
Please advice.

**Pull request closed without merging**
