### PR TITLE
Add ucontext_t for aarch64-unknown-linux-musl

### PR DESCRIPTION
**Pull request by ifreund**
See: https://github.com/bytecodealliance/wasmtime/issues/2133

### CODE REVIEW

**Comment by JohnTitor** [comment]
> Use no_extra_traits due to array longer than 32

Did you test with this workaround? I guess we could auto-derive it here as well...

https://github.com/rust-lang/libc/blob/035a4809428d319e72ff1aaae5c5335f18623836/src/unix/linux_like/linux/gnu/b64/aarch64/align.rs#L25-L27

**Comment by ifreund** [comment]
> Did you test with this workaround? I guess we could auto-derive it here as well...

I tried it but the math doesn't work out in this case. The prime factorization of `36 + 512` is `2 * 2 * 137`.

**Comment by JohnTitor** [comment]
Ah, makes sense. I'd still prefer to auto-derive it as this will make the difference between arch/env and users will be confused.

**Comment by JohnTitor** [comment]
(Note that CI will fail anyway until #1865 gets merged.)

**Comment by JohnTitor** [comment]
Looks good except for spurious failures. Could you rebase and squash commits into one?

**Comment by ifreund** [comment]
@JohnTitor squashed!

**Review by JohnTitor — APPROVED** [review]
Thanks a lot!

**Pull request merged**
