### PR TITLE
Add missing structs for mac

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please wait a bit, I'll ping you once working (sorry, forgot to precise WIP...).

**Comment by GuillaumeGomez** [comment]
The C equivalent is using `#pragma pack(4)` so until rust can lower the alignment, we can't move forward in here. Waiting for such an update! :)

**Comment by alexcrichton** [comment]
I'm going to close this due to inactivity, but feel free to resubmit with a rebase!

**Comment by GuillaumeGomez** [comment]
Like said above, I need to be able to `pack` so once rustc has it, I'll for sure!

**Pull request closed without merging**
