### PR TITLE
Move rtems cfg-ed import with the others

### PR DESCRIPTION
**Pull request by tgross35**
Clean up code added in https://github.com/rust-lang/libc/pull/3866

### CODE REVIEW

**Comment by tgross35** [comment]
@thesummer just noticed this when starting a backport, is there any reason it was in a separate cfg block in https://github.com/rust-lang/libc/pull/3866?

**Comment by thesummer** [comment]
@tgross35 Sorry, I was a bit pre-occupied the last week and lost track of the status here. Is there anything else I can help you with?

**Comment by thesummer** [comment]
@tgross35 Is there anything I can help with to get the changes merged into the libc-0.2 branch / release?

There is a conference coming soon with some of the RTEMS folk present and I was hoping to give them a demo with the sources of the public repos, so they can start playing around with Rust as well 🙏.

**Comment by tgross35** [comment]
Oh don't worry about this, I just forgot to close it :) Thanks for the follow up, we'll figure out something better at some point but it isn't pressing.

**Comment by thesummer** [comment]
@tgross35 ok, thanks. Should I prepare a PR for backporting the things to the libc-0.2 branch?

**Comment by tgross35** [comment]
Don't worry about it, I plan to do a round of cherry picks this weekend and will include the relevant ones as long as there isn't any major conflict.

**Comment by thesummer** [comment]
Perfect. Thanks a lot.

**Pull request closed without merging**
