### PR TITLE
Bump to 0.2.82

### PR DESCRIPTION
**Pull request by puradox**
Allow developers to start using ip_mreqn in Fuchsia.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Can this wait on https://github.com/rust-lang/libc/pull/2013? It's blocking https://github.com/rust-lang/socket2/pull/183.

**Comment by puradox** [comment]
@Thomasdezeeuw Looks like #2013 merged 👍

**Comment by Thomasdezeeuw** [comment]
@JohnTitor you have time to release a new version? Socket2 on Fuchsia is now blocked on this pr.

**Comment by JohnTitor** [comment]
There are still some PRs to be reviewed and I'd like to merge #2008 to fix the wrong definition at least.

**Comment by joshtriplett** [comment]
Could we merge https://github.com/rust-lang/libc/pull/2020 as well, please?

**Comment by puradox** [comment]
#2008 and #2020 have merged. Are we waiting on anything else?

**Comment by puradox** [comment]
@JohnTitor Sorry to be a bother, but can we get an update on this release?

**Comment by JohnTitor** [comment]
I'm going to r+ this once #2006 gets merged (and we should fix a CI failure). Sorry for the delay!

**Comment by puradox** [comment]
No worries, thank you for the quick update 🙏🏼

**Comment by JohnTitor** [comment]
Okay, let's release a new version :)
@bors r+

**Pull request merged**
