### PR TITLE
add waitid to netbsd

### PR DESCRIPTION
**Pull request by oconnor663**
This PR is mainly for me to see what breaks in CI.

### CODE REVIEW

**Comment by oconnor663** [comment]
@alexcrichton CI isn't passing on this guy yet. Will bors wait for that?

**Comment by alexcrichton** [comment]
@bors: r-

Ah ok, feel free to just ping me when it's working!

**Comment by oconnor663** [comment]
Trying again after moving NetBSD's `idtype_t` up a level.

**Comment by oconnor663** [comment]
@alexcrichton I think I'm still breaking the builds on netbsd and openbsd. If I'm causing trouble with this PR I can figure out how to test this stuff locally instead?

**Comment by alexcrichton** [comment]
Oh not at all, no worries!

You should be able to test locally though pretty simply, you can follow the instructions in .travis.yml which I believe in theory is just a few commands.

**Comment by semarie** [comment]
@oconnor663 I didn't found `waitid` neither `idtype_t` under my OpenBSD `/usr/include` tree (it is  -current, so the upcoming 6.1 version). I think this function is just not supported/implemented by OpenBSD.

**Comment by oconnor663** [comment]
Thanks. I had seen a couple declarations of `waitid` in the BSD repo and I'd just run with it, but I guess those aren't an actual implementation. I'll take it out here and see what happens.

**Comment by semarie** [comment]
According to http://bxr.su/search?defs=waitid, the `waitid` function could be found only in NetBSD. FreeBSD only defines it (with a dummy) for linux compatibility-layer. So except NetBSD, others BSD doesn't define it: it is just unimplemented.

**Comment by oconnor663** [comment]
Oh that's super useful, thanks. I'm still getting [this error](https://travis-ci.org/rust-lang/libc/jobs/207956898) on NetBSD, not sure how to interpret it:

```
/usr/local/rumprun-x86_64/lib/libc.a(waitid.o): In function `_waitid':
/build/rumprun/src-netbsd/lib/libc/gen/waitid.c:52: undefined reference to `wait6'
collect2: error: ld returned 1 exit status
```

It looks like that's maybe related to the ifdefs in this section of `sys/sys/wait.h`, but that's as far as I've gotten:

```
#if defined(_XOPEN_SOURCE) || defined(_NETBSD_SOURCE)
#ifndef __LIBC12_SOURCE__
pid_t	wait3(int *, int, struct rusage *) __RENAME(__wait350);
pid_t	wait4(pid_t, int *, int, struct rusage *) __RENAME(__wait450);
pid_t	wait6(idtype_t, id_t, int *, int, struct wrusage *, siginfo_t *);
#endif
#endif
```

**Comment by alexcrichton** [comment]
@oconnor663 oh if you grep around for `#[link_name]` annotations you'll see some similar situations for netbsd already I believe.

**Comment by superriva** [comment]
```
/usr/local/rumprun-x86_64/lib/libc.a(waitid.o): In function `_waitid':
/build/rumprun/src-netbsd/lib/libc/gen/waitid.c:52: undefined reference to `wait6'
collect2: error: ld returned 1 exit status
```
Look at the netbsd's github source:
https://github.com/IIJ-NetBSD/netbsd-src/blob/128cb45583a1d297a1d78fbe2802d993a7b45b51/lib/libc/gen/waitid.c
```
int
waitid(idtype_t idtype, id_t id, siginfo_t *info, int flags)
{
	int status;

	switch (**wait6(idtype, id, &status, flags, NULL, info)**) {   // line 52
	case -1:
		return -1;
	case 0:
		if (info != NULL)
			memset(info, 0, sizeof(*info));
		/*FALLTHROUGH*/
	default:
		return 0;
	}
```
It uses wait6. So, I think you have to add wai6 function to the mod.rs.

**Comment by oconnor663** [comment]
@superriva I'm pretty new to this stuff, could you help me understand how a missing declaration in Rust code could prevent C code from compiling, when the function that's missing is implemented in C?

**Comment by superriva** [comment]
@oconnor663 
I'm a newbie too. But I will try to answer how I understand that.
Сode all functions, declared in the 'extern' part of mod.rs, is extracted from unix libc. And then it is compiled into the final rust libc. Please, see output Travis log. It show a gcc flag '--as-needed'. Thefore, if a function is not declared then it code will not extracted from unix libc and will not compiled into rust libc. So, you have a pointer to not existed function in your case.

**Comment by oconnor663** [comment]
@superriva hmm, just added an extern declaration for `wait6`, but it doesn't seem to have fixed the error: https://travis-ci.org/rust-lang/libc/jobs/217846693#L851

**Comment by superriva** [comment]
@oconnor663 Try to add in the libc/libc-test/build.rs:

    if netbsd {
        cfg.header("ufs/ufs/quota.h");
        cfg.header("ufs/ufs/quota1.h");
        cfg.header("sys/ioctl_compat.h");
+     cfg.header("sys/wait.h");
    }

**Comment by oconnor663** [comment]
@superriva I think that's already happening here? https://github.com/rust-lang/libc/blob/master/libc-test/build.rs#L91

**Comment by superriva** [comment]
@oconnor663 Hmm, yes.

**Comment by superriva** [comment]
@oconnor663 Excuse me, do you know how to squash the commits? In my topic: https://github.com/rust-lang/libc/pull/559

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with tests fixed!

**Pull request closed without merging**
