### PR TITLE
add more pthread_attr functions and related constants:

### PR DESCRIPTION
**Pull request by Ncerzzk**
pthread_attr_getinheritsched
pthread_attr_setinheritsched
pthread_attr_getschedpolicy
pthread_attr_setschedpolicy
pthread_attr_getschedparam
pthread_attr_setschedparam
PTHREAD_INHERIT_SCHED
PTHREAD_EXPLICIT_SCHED

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you fix the style issue?

**Comment by Ncerzzk** [comment]
> Could you fix the style issue?

hi, fixed.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Pull request merged**
