### PR TITLE
Add ioctl() constants for BPF

### PR DESCRIPTION
**Pull request by equal-l2**

### CODE REVIEW

**Comment by equal-l2** [comment]
@gnzlbg Will you try again please?

**Comment by equal-l2** [comment]
```
bad BIOCSETF value at byte 2: rust: 16 (0x10) != c 8 (0x8)
bad BIOCSRTIMEOUT value at byte 2: rust: 16 (0x10) != c 8 (0x8)
bad BIOCGRTIMEOUT value at byte 2: rust: 16 (0x10) != c 8 (0x8)
bad BIOCSETFNR value at byte 2: rust: 16 (0x10) != c 8 (0x8)
```

I'll fix this soon.

**Comment by equal-l2** [comment]
For future reference:

These constants are defined as below:
```
#define BIOCSETF        _IOW('B',103, struct bpf_program)
#define BIOCSRTIMEOUT   _IOW('B',109, struct timeval)
#define BIOCGRTIMEOUT   _IOR('B',110, struct timeval)
#define BIOCSETFNR      _IOW('B', 126, struct bpf_program)
```

`struct bpf_program` is this:
```
struct bpf_program {
	u_int bf_len;
	struct bpf_insn *bf_insns;
};
```

And `struct timeval`:
```
_STRUCT_TIMEVAL
{
	__darwin_time_t         tv_sec;         /* seconds */
	__darwin_suseconds_t    tv_usec;        /* and microseconds */
};
```
(`__darwin_time_t` is `long`, `__darwin_suseconds_t` is `__int32_t`)

The problem is that size of pointer and `long` differs between 32-bit and 64-bit.

**Comment by semarie** [comment]
it broke OpenBSD. several of them are not defined on it

**Pull request merged**
