### PR TITLE
Add makedev for the BSDs

### PR DESCRIPTION
**Pull request by asomers**
Also, make Linux's makedev function safe and const.

### CODE REVIEW

**Comment by asomers** [comment]
cc @musikid

**Comment by semarie** [comment]
LGTM for openbsd.

just a question about the type used for the function definition: why using `c_uint` (and casting it to `dev_t`) instead of `dev_t` directly ?

**Comment by asomers** [comment]
> LGTM for openbsd.
> 
> just a question about the type used for the function definition: why using `c_uint` (and casting it to `dev_t`) instead of `dev_t` directly ?

Just because that's what the existing Linux definition does.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
👍, @bors r+

**Comment by asomers** [comment]
@JohnTitor I think this should fix the bors error.  But I don't know how to run the tests on emscripten except by asking bors to merge.

**Comment by JohnTitor** [comment]
We could do `@bors try` but I think it's okay to r+ in this case.
@bors r+

**Comment by asomers** [comment]
@JohnTitor I think if you do " bors delegate=asomers" then that will give me permission to use "bors try".  It'll also give me permission to merge the PR, but I promise not to do that unless you say so ;) .

**Comment by JohnTitor** [comment]
👍, @bors delegate+

**Comment by asomers** [comment]
bors try

**Comment by asomers** [comment]
@JohnTitor it finally passes CI, I've squashed my commits.

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Pull request merged**
