### PR TITLE
Freebsd items

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I didn't finish the rebase for whatever reason. Should be better now. Let's see if CI is happy, I think a few things will be broken so I'll look how to fix them and check how to ignore some fields checks as well if needed.

**Comment by GuillaumeGomez** [comment]
I updated locally the link to `ctest2` until it's published. So now I get:

```
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26555:23: error: redefinition of '__test_size_rusage'
  cargo:warning=             uint64_t __test_size_rusage(void) { return sizeof(struct rusage); }
  cargo:warning=                      ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2621:23: note: previous definition is here
  cargo:warning=             uint64_t __test_size_rusage(void) { return sizeof(struct rusage); }
  cargo:warning=                      ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26556:23: error: redefinition of '__test_align_rusage'
  cargo:warning=             uint64_t __test_align_rusage(void) {
  cargo:warning=                      ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2622:23: note: previous definition is here
  cargo:warning=             uint64_t __test_align_rusage(void) {
  cargo:warning=                      ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26568:27: error: redefinition of '__test_offset_rusage_ru_utime'
  cargo:warning=                 uint64_t __test_offset_rusage_ru_utime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2634:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_offset_rusage_ru_utime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26571:27: error: redefinition of '__test_fsize_rusage_ru_utime'
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_utime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2637:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_utime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26577:34: error: redefinition of '__test_field_type_rusage_ru_utime'
  cargo:warning=                 struct timeval* __test_field_type_rusage_ru_utime(struct rusage* b) {
  cargo:warning=                                 ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2643:34: note: previous definition is here
  cargo:warning=                 struct timeval* __test_field_type_rusage_ru_utime(struct rusage* b) {
  cargo:warning=                                 ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26582:27: error: redefinition of '__test_offset_rusage_ru_stime'
  cargo:warning=                 uint64_t __test_offset_rusage_ru_stime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2648:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_offset_rusage_ru_stime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26585:27: error: redefinition of '__test_fsize_rusage_ru_stime'
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_stime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2651:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_stime(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26591:34: error: redefinition of '__test_field_type_rusage_ru_stime'
  cargo:warning=                 struct timeval* __test_field_type_rusage_ru_stime(struct rusage* b) {
  cargo:warning=                                 ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2657:34: note: previous definition is here
  cargo:warning=                 struct timeval* __test_field_type_rusage_ru_stime(struct rusage* b) {
  cargo:warning=                                 ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26596:27: error: redefinition of '__test_offset_rusage_ru_maxrss'
  cargo:warning=                 uint64_t __test_offset_rusage_ru_maxrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2662:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_offset_rusage_ru_maxrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26599:27: error: redefinition of '__test_fsize_rusage_ru_maxrss'
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_maxrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2665:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_maxrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26605:25: error: redefinition of '__test_field_type_rusage_ru_maxrss'
  cargo:warning=                  long* __test_field_type_rusage_ru_maxrss(struct rusage* b) {
  cargo:warning=                        ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2671:25: note: previous definition is here
  cargo:warning=                  long* __test_field_type_rusage_ru_maxrss(struct rusage* b) {
  cargo:warning=                        ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26610:27: error: redefinition of '__test_offset_rusage_ru_ixrss'
  cargo:warning=                 uint64_t __test_offset_rusage_ru_ixrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2676:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_offset_rusage_ru_ixrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26613:27: error: redefinition of '__test_fsize_rusage_ru_ixrss'
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_ixrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2679:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_ixrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26619:25: error: redefinition of '__test_field_type_rusage_ru_ixrss'
  cargo:warning=                  long* __test_field_type_rusage_ru_ixrss(struct rusage* b) {
  cargo:warning=                        ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2685:25: note: previous definition is here
  cargo:warning=                  long* __test_field_type_rusage_ru_ixrss(struct rusage* b) {
  cargo:warning=                        ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26624:27: error: redefinition of '__test_offset_rusage_ru_idrss'
  cargo:warning=                 uint64_t __test_offset_rusage_ru_idrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2690:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_offset_rusage_ru_idrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26627:27: error: redefinition of '__test_fsize_rusage_ru_idrss'
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_idrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2693:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_idrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26633:25: error: redefinition of '__test_field_type_rusage_ru_idrss'
  cargo:warning=                  long* __test_field_type_rusage_ru_idrss(struct rusage* b) {
  cargo:warning=                        ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2699:25: note: previous definition is here
  cargo:warning=                  long* __test_field_type_rusage_ru_idrss(struct rusage* b) {
  cargo:warning=                        ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26638:27: error: redefinition of '__test_offset_rusage_ru_isrss'
  cargo:warning=                 uint64_t __test_offset_rusage_ru_isrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2704:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_offset_rusage_ru_isrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:26641:27: error: redefinition of '__test_fsize_rusage_ru_isrss'
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_isrss(void) {
  cargo:warning=                          ^
  cargo:warning=/root/libc/target/x86_64-unknown-freebsd/debug/build/libc-test-809464fa918cfbf9/out/main.c:2707:27: note: previous definition is here
  cargo:warning=                 uint64_t __test_fsize_rusage_ru_isrss(void) {
  cargo:warning=                          ^
  cargo:warning=fatal error: too many errors emitted, stopping now [-ferror-limit=]
  cargo:warning=20 errors generated.
  exit status: 1
```

The fields don't seem duplicated so I'm not sure what would be the issue here. Any idea maybe?

**Comment by JohnTitor** [comment]
I guess so because I remember that the same (or similar) failure happened in the past and it was due to import some similar header files (IIRC something like `sys/foo.h` was involved). But I'm not too familiar with FreeBSD, I need some debugging to provide further help (looking at the generated C file would be a help, I imagine).

**Comment by GuillaumeGomez** [comment]
The last error is pretty interesting:

```
cargo:warning=/tmp/cirrus-ci-build/target/x86_64-unknown-freebsd/debug/build/libc-test-46bad6d5373dd9cb/out/main.c:33091:65: error: use of undeclared identifier 'KVME_TYPE_GUARD'
  cargo:warning=            static const int __test_const_KVME_TYPE_GUARD_val = KVME_TYPE_GUARD;
```

The `KVME_TYPE_GUARD` is defined in the `sys/user.h` header (which is added by the test script) alongside a few others `KVME_*` constants (which are found). How strange.

**Comment by GuillaumeGomez** [comment]
I don't think either but bors doesn't seem to agree... How should we fix this?

**Comment by JohnTitor** [comment]
As the above comment says, we should also update the nightly version in the CI config.

**Comment by GuillaumeGomez** [comment]
Where is it set? I looked in the `ci` folder but didn't find it...

**Comment by GuillaumeGomez** [comment]
Update the CI nightly version as well!

**Comment by lnicola** [comment]
This will break `rust-lang/rust` on the next update, filed https://github.com/rust-lang/rust/pull/90495.

**Comment by GuillaumeGomez** [comment]
@lnicola Good catch, thanks!

**Pull request merged**
