### PR TITLE
Serial Experiments GitHub Actions

### LINKED ISSUE #1582: Github actions
@pietroalbini could we enable github actions for libc ? It has many more buildjobs than Azure, and for libc that's a huge bottleneck.

### PR DESCRIPTION
**Pull request by JohnTitor**
Let's start the party to close #1582.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Yay, I think it now works just like Pipelines. I added some `needs` and `max-parallel` so that we can keep jobs under 20.

@pietroalbini When you have time, could you confirm this doesn't cause any issues for other repos?

**Comment by pietroalbini** [comment]
How many jobs are here in total?

**Comment by JohnTitor** [comment]
It's about ~50 jobs.

**Comment by pietroalbini** [comment]
Can we run a subset of jobs (dunno, like, max 10) on PRs and the rest through bors?

**Comment by JohnTitor** [comment]
Sounds good! Will set up for it.

**Comment by JohnTitor** [comment]
Seems try run works well, it has spurious failure though: https://github.com/rust-lang/libc/actions/runs/302768169

**Comment by JohnTitor** [comment]
Let's try again, @bors try

**Comment by JohnTitor** [comment]
Ah, it should've been `bors build finished`: https://github.com/rust-lang/rust-central-station/pull/959/files

**Comment by JohnTitor** [comment]
Okay, bors now listens to actions successfully.
The number of PR jobs is now under 10 so I'm going to merge this to unblock everything.
@bors: r+

**Comment by JohnTitor** [comment]
Spurious? @bors retry

**Comment by JohnTitor** [comment]
`wget` works fine, let's @bors try

**Comment by JohnTitor** [comment]
Ohh, Cirrus CI is definitely unrelated.
@bors try

**Comment by JohnTitor** [comment]
Finally, it passed!
@bors r+

**Pull request merged**
