### PR TITLE
Fix build on x86_64-unknown-cloudabi, bump version

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

For posterity, this was [discovered here](https://github.com/rust-lang/rust/pull/56092#issuecomment-445514260)

**Comment by mati865** [comment]
Erm, all green.

**Comment by alexcrichton** [comment]
Something about [this](https://github.com/rust-lang/rust-central-station/pull/120) is unfortunately broken, so I'm gonna merge manually for now.

**Pull request merged**
