### PR TITLE
add some sysv shared memory to macosx

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
This should be ready.

r? @alexcrichton @malbarbo

**Comment by gnzlbg** [comment]
Would be cool if a minor release could be done after this is merged.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
The README also has [some notes](https://github.com/rust-lang/libc#releasing-your-change-to-cratesio) on how releases are done

**Pull request merged**
