### PR TITLE
redox: convert to target_family unix

### PR DESCRIPTION
**Pull request by jackpot51**
This is the first step to supporting https://github.com/rust-lang/rust/issues/60139.

In order to have a smooth transition, there will need to be a change made in rust at the same time, switching Redox over to the unix target family. See https://github.com/rust-lang/rust/pull/60547

### CODE REVIEW

**Comment by gnzlbg** [comment]
@jackpot51 I think it would be better to make the rust-lang/rust PR use the libc of this branch, and once bors try passes there, then we can merge this here, release, and update the rust-lang/rust PR to use the released version, and merge it with high priority. What do you think?

**Comment by jackpot51** [comment]
I think that sounds good to me. I will do that soon

**Comment by jackpot51** [comment]
@gnzlbg it is done: https://github.com/rust-lang/rust/pull/60547, https://github.com/rust-lang/rust/pull/60547/commits/2ab50afb0d50505d05547bb831dc211d8ba1a9e6

**Comment by gnzlbg** [comment]
So let's merge this, do a release, and then you can update the PR upstream !

**Comment by jackpot51** [comment]
@gnzlbg what should I do about the build failure? I checked and the failures do not seem to be introduced by this PR, but am open to including fixes if possible and necessary.

**Comment by mati865** [comment]
It's https://github.com/rust-lang/libc/issues/1333

The thing is upgrading system on CI is not trivial task for this repo because the code is verified against the system.

**Comment by jackpot51** [comment]
Woohoo!

**Pull request merged**
