### PR TITLE
update crate version to 0.2.154

### PR DESCRIPTION
**Pull request by Dirreke**
Need #3572 to repair the build for rust. Sorry for not submitting a PR before 0.2.153.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Thanks! I'm currently not able to make a release but will do that in a few days.

**Comment by agg23** [comment]
I know you're busy John, but when you get a moment can we push this release?

**Comment by JohnTitor** [comment]
👍, could you also update the libc dependency version on libc-test?

**Comment by heiher** [comment]
@JohnTitor Could you please include this patch in next release? Thanks.

https://github.com/rust-lang/libc/pull/3606

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Released on crates.io: https://crates.io/crates/libc/0.2.154

**Pull request merged**
