### PR TITLE
haiku: add getentropy

### PR DESCRIPTION
**Pull request by devnexen**
no man page so far but
https://github.com/haiku/haiku/blob/e4a557f372b21b348e0c6a2ae7157c1b73e0d738/src/system/libroot/posix/unistd/getentropy.c#L13

### CODE REVIEW

**Comment by tgross35** [comment]
Looks straightforward enough to me, @nielx could you double check this?

**Review by tgross35 — APPROVED** [review]

**Comment by nielx** [comment]
@devnexen No objections to adding `getentropy()`, however I think the place is incorrect. The commit you cite actually moved this out of libbsd into the general libroot. However, in this change, you place it in the block that links to `bsd`. While this will not cause any problems in practise, I suggest it is placed outside of this block to match Haiku.

**Comment by nielx** [comment]
@tgross35 looks good to me!

**Comment by tgross35** [comment]
Thanks for reviewing! I am just holding off on merging anything until FreeBSD comes back (rustc broke, should be fixed in this nightly or the next one)

**Comment by devnexen** [comment]
> Thanks for reviewing! I am just holding off on merging anything until FreeBSD comes back (rustc broke, should be fixed in this nightly or the next one)
Seems [working now](https://github.com/rust-lang/libc/pull/3996/commits/ca2f10910879548cd3fcd2c4ef4a235b08ccaed4).

**Pull request merged**
