### PR TITLE
Linux: add reboot() and constants

### PR DESCRIPTION
**Pull request by bugaevc**
Add declarations from `sys/reboot.h` and `linux/reboot.h`. Initially originated as nix-rust/nix#386.

### CODE REVIEW

**Comment by bugaevc** [comment]
Should the rest of reboot declarations be in `notbsd/mod.rs`, or should I copy the declarations to `notbsd/android`, or are they somehow included from `notbsd/linux/mod.rs` (doesn't seem to be the case, but there are lots of functions there and just several in `notbsd/android`)?

**Comment by alexcrichton** [comment]
If they're shared among all the platforms under `notbsd` (Android + Linux) then it should be fine to place the definitions in `notbsd/mod.rs`, but copying is also fine. Looks like CI is green here so I'd be good merging, but do you wanna juggle around the declarations a bit?

**Comment by bugaevc** [comment]
I'm not really sure whether the same stuff is available under Android: Android is Linux anyway, but it may well be glibc-specific stuff.
Let me try to put them into `notbsd` and see if that breaks the Android build.

**Comment by bugaevc** [comment]
OK, so it does break the Android build. Reverting.

**Comment by bugaevc** [comment]
Feel free to merge this (or should we play the rebasing/squashing game?).

**Comment by alexcrichton** [comment]
Nah this is fine, thanks again!

**Comment by bugaevc** [comment]
Thanks! When can I expect this to be released (e.g. to use it in nix)?

**Comment by alexcrichton** [comment]
Would it be possible for nix to use a git version of libc for now? I can be sure to make a release right before a nix release, but we just made a release yesterday I believe for another nix-requested PR :)

**Comment by alexcrichton** [comment]
That being said, I certainly don't mind making another release!

**Comment by bugaevc** [comment]
Filed nix-rust/nix#387 for nix to track libc's master

**Comment by alexcrichton** [comment]
Thanks! I'll add some comments over there as well.

**Pull request merged**
