### PR TITLE
added EPOLL(5)  for Illumos (Solaris fork) 

### PR DESCRIPTION
**Pull request by cneira**
EPOLL(5)  is being used in crates like mio and iovec , this change allows those crates and other that depends on EPOLL(5)  to be built in illumos systems.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think there's some tidy failures, and could the changes to src/lib.rs get backed out as well? (it looks like nothing necessary?)

**Comment by cneira** [comment]
Fixed code style, and removed not needed changes in lib.rs

**Comment by cneira** [comment]
Thanks a lot @bors

**Pull request merged**
