### PR TITLE
Add TIOCGRS485 and TIOCSRS485 for musl #1094

### PR DESCRIPTION
**Pull request by xoac**
I need help with adding `TIOCSRS485` and `TIOCSRS485` constants to libc.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me! I think CI is failing though?

**Comment by xoac** [comment]
It's not good. This lacks some definitions. I just defined this for musl target.
We should add this also here:
```
src/unix/notbsd/linux/other/*
src/unix/notbsd/linux/mips/ *
src/unix/newlibc/*
src/unix/uclibc/*
```
and maybe in more places but I am not sure how to check values that paramter should have. It would nice to have a link to sources in c in every module.

**Comment by xoac** [comment]
This CI is failing because when I forked `master`  master was failing

**Comment by alexcrichton** [comment]
@xoac I don't think that's correct? There's syntax errors in this PR?

**Comment by alexcrichton** [comment]
Looks like there may still be some CI failures?

**Comment by xoac** [comment]
I think u missed comment about missing definition for other implementations. It will be available for musl target but will not for exmple for glibc x86. It's because I don't know where to verify that variables..

**Comment by alexcrichton** [comment]
Oh that's fine! We're ok with incremental updates an additions

**Pull request merged**
