### PR TITLE
adding in6_ifreq to apple.

### LINKED ISSUE #3611: Why in6_ifreq does not exist on macOS
https://github.com/apple-oss-distributions/xnu/blob/main/bsd/netinet6/in6_var.h
It seems that all related ipv6 structures in this header file do not exist

### PR DESCRIPTION
**Pull request by devnexen**
close #3611

### CODE REVIEW

**Comment by JohnTitor** [comment]
CI fails: https://github.com/rust-lang/libc/actions/runs/8884641673/job/24394199472?pr=3617

**Comment by cavivie** [comment]
@JohnTitor Why does the ci fail on sparc64-unknown-linux-gnu target, it seems to be not related to this PR, I think it can be merged.

**Comment by safinaskar** [comment]
@cavivie

> @JohnTitor Why does the ci fail on sparc64-unknown-linux-gnu target, it seems to be not related to this PR, I think it can be merged.

I think sparc64 problems are unrelated to this PR, too. Sparc problems was apparently fixed in https://github.com/rust-lang/libc/pull/3707 , so this PR just need to be rebased

**Comment by cavivie** [comment]
> I think sparc64 problems are unrelated to this PR, too. Sparc problems was apparently fixed in #3707 , so this PR just need to be rebased

@devnexen Could you please work on this, we may be able to merge soon.

**Review by JohnTitor — APPROVED** [review]

**Pull request merged**
