### PR TITLE
Re-export c_char_def as c_char instead of defining c_char per target

### PR DESCRIPTION
**Pull request by taiki-e**
# Description

Replaces https://github.com/rust-lang/libc/pull/4199 by doing https://github.com/rust-lang/libc/pull/4199#issuecomment-2548178664.

Closes https://github.com/rust-lang/libc/pull/4199.

# Sources

# Checklist

- [ ] Relevant tests in `libc-test/semver` have been updated
- [x] No placeholder or unstable values like `*LAST` or `*MAX` are
  included (see [#3131](https://github.com/rust-lang/libc/issues/3131))
- [ ] Tested locally (`cd libc-test && cargo test --target mytarget`);
  especially relevant for platforms that may not be checked in CI

### CODE REVIEW

**Comment by taiki-e** [comment]
Hmm...

https://github.com/rust-lang/libc/actions/runs/12372572407/job/34531085124?pr=4201

```
src/teeos/mod.rs:12: import found after module when it belongs before
src/vxworks/riscv64.rs:3: typedef found after module when it belongs before
src/vxworks/aarch64.rs:3: typedef found after module when it belongs before
src/vxworks/riscv32.rs:3: typedef found after module when it belongs before
src/vxworks/x86_64.rs:3: typedef found after module when it belongs before
... (omitted)
src/unix/nto/aarch64.rs:2: import found after module when it belongs before
src/unix/nto/x86_64.rs:2: import found after module when it belongs before
src/wasi/mod.rs:9: import found after module when it belongs before
```

**Comment by tgross35** [comment]
> Hmm...
> 
> https://github.com/rust-lang/libc/actions/runs/12372572407/job/34531085124?pr=4201
> 
> ```
> src/teeos/mod.rs:12: import found after module when it belongs before
> src/vxworks/riscv64.rs:3: typedef found after module when it belongs before
> src/vxworks/aarch64.rs:3: typedef found after module when it belongs before
> src/vxworks/riscv32.rs:3: typedef found after module when it belongs before
> src/vxworks/x86_64.rs:3: typedef found after module when it belongs before
> ... (omitted)
> src/unix/nto/aarch64.rs:2: import found after module when it belongs before
> src/unix/nto/x86_64.rs:2: import found after module when it belongs before
> src/wasi/mod.rs:9: import found after module when it belongs before
> ```

This repo has really old tooling that likes to complain about a lot.

My idea with having `c_char_def` is that I could go through one OS at a time and double check that things line up, replacing arch-specific `type c_chars = ...` in e.g. `some_os/{aarch64,x86_64,arm}.rs` with a `pub use crate::arch::c_char_def as c_char;` in `some_os/mod.rs` if things line up. Unfortunately I don't think that changing from definitions to reexports really highlights any remaining discrepancies.

Admittedly this plan was from before I knew anyone else was working on this so I am open to other suggestions, but could at least the known changes in https://github.com/rust-lang/libc/pull/4199 get in before updating everything else?

**Comment by taiki-e** [comment]
(The approach I said I think is ideal in https://github.com/rust-lang/libc/pull/4199#issuecomment-2548226721, doesn't have such an CI problem: https://github.com/rust-lang/libc/pull/4202)

**Comment by taiki-e** [comment]
Closing in favor of https://github.com/rust-lang/libc/pull/4202, which is doing the approach I said I think is ideal in https://github.com/rust-lang/libc/pull/4199#issuecomment-2548226721.

**Pull request closed without merging**
