### PR TITLE
Add TCP_FASTOPEN_CONNECT for Linux after 4.11

### LINKED ISSUE #1633: Add TCP_FASTOPEN_CONNECT for Linux after 4.11
Since Linux Kernel 4.11, `TCP_FASTOPEN_CONNECT` sockopt was supported. [Commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=19f6d3f3c8422d65b5e3d2162e30ef07c6e21ea2)

Example usage:

```c
sockfd = socket(...);

int optval = 1;
int optval = 1;
setsockopt(sockfd,
           IPPROTO_TCP,
           TCP_FASTOPEN_CONNECT,
           (void *)&optval,
           sizeof(optval));

// Call connect instead of sendto
ret = connect(...);
```

### Definition

```c
#define TCP_FASTOPEN_CONNECT	30	/* Attempt FastOpen with connect */
```

### PR DESCRIPTION
**Pull request by zonyitoo**
fix #1633

### CODE REVIEW

**Comment by zonyitoo** [comment]
@gnzlbg Hello, could you review this PR?

**Comment by zonyitoo** [comment]
@gnzlbg Hello, here is another one, related to #1635

**Comment by JohnTitor** [comment]
@zonyitoo Could you rebase to make sure things?
r? @JohnTitor

**Comment by zonyitoo** [comment]
Done.

**Pull request merged**
