### PR TITLE
ARMv6K Horizon OS support

### PR DESCRIPTION
**Pull request by Meziu**
Added support for the Horizon OS Nintendo 3DS system `Newlib` declarations.

Edit: after some changes, networking is now stable with standardized API.

### CODE REVIEW

**Comment by Meziu** [comment]
@JohnTitor Why did it get blocked?

**Comment by JohnTitor** [comment]
We need an internal decision for this, sorry about that.

**Comment by Meziu** [comment]
> We need an internal decision for this, sorry about that.

Oh yeah don’t worry, I was just puzzled by the block without a message. Take all the time needed.

**Comment by Meziu** [comment]
@JohnTitor I don't want to come off as insistent, but it's been over a month and I received no info. Is there any chance this will get merged? It's not a problem if it won't, I just want to know if I should continue to work seriously on this project so that I may set my priorities correctly.

**Comment by JohnTitor** [comment]
This isn't blocked by _me_, but a team and they are busy with other work, so I cannot tell you when decision is made. And I don't have enough time to do open source work right now so cannot push the process, sorry about that.

**Comment by Meziu** [comment]
Fixed the standards for the networking, matching the latest version of compiler.

**Comment by AzureMarker** [comment]
@JohnTitor another month has passed, any news? What team needs to make a decision, and what is it about? There isn't a lot of transparency going on right now.

**Comment by AzureMarker** [comment]
r? @rust-lang/libc 
Since @JohnTitor said they don't have time to work on this. Can someone clarify what team needs to make what decision?

**Comment by Meziu** [comment]
r? rust-lang/libc

**Comment by Amanieu** [comment]
I chased down the various threads related to this issue. It seems that this is blocked on [this comment](https://github.com/rust-lang/rust/pull/88529#issuecomment-919938396) by @skade which expresses concerns about bindings to vendor-specific APIs. However this PR only creates bindings to newlib standard C APIs so I think it is fine to merge.

@bors r+

**Comment by Meziu** [comment]
> I chased down the various threads related to this issue. It seems that this is blocked on [this comment](https://github.com/rust-lang/rust/pull/88529#issuecomment-919938396) by @skade which expresses concerns about bindings to vendor-specific APIs. However this PR only creates bindings to newlib standard C APIs so I think it is fine to merge.
> 
> 
> 
> @bors r+

Yes, that is indeed the reason why this PR is made to be this way. Glad to see it solved. 😃

**Pull request merged**
