### PR TITLE
Implement utmpx.h itens for NetBSD

### LINKED ISSUE #1534: [API Request] Expose utmp and utmpx on netbsd
For reference:
[utpm](https://github.com/NetBSD/src/blob/trunk/include/utmp.h)
[utpmx](https://github.com/NetBSD/src/blob/trunk/include/utmpx.h)

### PR DESCRIPTION
**Pull request by GrayJack**
This PR partially closes #1534

If add the constants, structs and and extra traid implmentation

### CODE REVIEW

**Comment by GrayJack** [comment]
The fails seems not to be related  my code changes

**Comment by GrayJack** [comment]
@gnzlbg Do I have to resolve the merge comflicts or the moderators or libc that does that?

**Comment by gnzlbg** [comment]
Need to fix formatting.

**Comment by GrayJack** [comment]
Linux builds failed on CI, dunno why

**Comment by gnzlbg** [comment]
> error[E0277]: arrays only have std trait implementations for lengths 0..=32

You are trying to use PartialEq or Debug for arrays with more than 32 elements in your manual implementations, but these impls do not exist. You already are doing the "iterator workaround" for one of the fields, I think you just need to apply it to others.

**Comment by GrayJack** [comment]
I did a `cargo check --target x86_64-unknown-netbsd` and now the check passed

**Comment by GrayJack** [comment]
What failed?

**Comment by gnzlbg** [comment]
The network failed.

@bors: retry

**Comment by GrayJack** [comment]
Can we test again?

**Comment by GrayJack** [comment]
I don't known why macOS build fails

**Comment by gnzlbg** [comment]
Looks spurious. @bors: r+

**Pull request merged**
