### PR TITLE
Add LC_ constants for redox (and truncate() is now supported)

### PR DESCRIPTION
**Pull request by coolreader18**
From `relibc/include/bits/locale.h` and `relibc/src/header/unistd/mod.rs`

### CODE REVIEW

**Comment by coolreader18** [comment]
Also IPPROTO_RAW I guess

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by coolreader18** [comment]
Uh... is that just a fluke?

**Comment by JohnTitor** [comment]
Yeah, the sparc64 job often causes timeout, @bors retry

**Pull request merged**
