### PR TITLE
Add misc constants and functions for android

### PR DESCRIPTION
**Pull request by fkm3**
These are the main diffs present in the downstream android opensource
project repo.

### CODE REVIEW

**Comment by Amanieu** [comment]
CI failure seems to be because we are using an old version of the Android emulator. You should try updating the CI scripts to use a newer version.

**Comment by fkm3** [comment]
Thanks. It looks like it is using android SDK version 24 for arm and version 28 for x86, but `getrandom` was only added in version 28. I'll try bumping the version. https://github.com/rust-lang/libc/commit/eb0794a5d8af5b7b370b01c5ae4f7f5f0c14bc0d seems to have chosen different versions on purpose though, so I'm a little wary.

**Comment by Amanieu** [comment]
This seems to have been due to an unavailability of emulator images for certain SDK versions: https://github.com/rust-lang/libc/pull/1344#issuecomment-494346531

**Comment by fkm3** [comment]
There are no system images for armeabi-v7a after API version 24. It may be that support was dropped. I'm unsure.

I'm going to try moving the `getrandom` declaration into `b64/mod.rs` and then only bump the API version for aarch64.

**Comment by Amanieu** [comment]
Maybe try using an arm64 image? It should support both 32-bit and 64-bit ARM.

**Comment by Amanieu** [comment]
Seems like x86_64 is still running a v24 image.

**Comment by fkm3** [comment]
I've updated x86_64 as well now. The newer `system.img` doesn't work easily with `e2fs`, so I had to add some extra code to workaround it. PTAL, thanks for sticking with me!

**Comment by fkm3** [comment]
Switched from `dd` to `fallocate` (12.892 secs vs 0.438 on my machine). Hopefully that will fix the time out.

**Comment by Amanieu** [comment]
I think there might be something wrong with the arm image being used?

**Comment by fkm3** [comment]
Are there logs for the timeout?

**Comment by Amanieu** [comment]
https://github.com/rust-lang/libc/runs/6141722587?check_suite_focus=true

**Comment by fkm3** [comment]
Thanks. I can't find a solution. It seems like an over constrained problem.

Some notes, possibly incorrect:

* `getrandom` requires API version >= 28
* Android emulator support for arm64 on a x64 host was dropped somewhere in the API range (24, 28].
* There is some support for running arm on the x64 emulator ([link](https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html)), but I'm not sure if it is relevant to the CI tests. Additionally, running the x64 emulator on x64 requires KVM (which I assume the CI doesn't support, if it runs on github actions)

I wonder if we can avoid the android emulator altogether with some combination of qemu + the arm64 system image (similar to what the android x64 tests are doing). I might give that a try, but will probably be slow to follow up.

**Comment by Amanieu** [comment]
An alternative solution might be to simply exclude the new symbols from tests (see `libc-test/build.rs`) and keep using the old Android emulator image.

**Comment by fkm3** [comment]
Sorry for the slow follow up. 

> An alternative solution might be to simply exclude the new symbols from tests (see libc-test/build.rs) and keep using the old Android emulator image.

I've uploaded new changes that try this approach.

I've also added another io_uring constant.

Thanks!

**Review by JohnTitor — APPROVED** [review]

**Pull request merged**
