### PR TITLE
Add `get_hostname` to esp-idf

### LINKED ISSUE #3748: Hostname on xtensa esp-idf esp32s3
Hi, 
I need to use hostname_max and the function gethostname for xtensa-esp32s3-espidf but they're not supported for this target.
Can anyone give me any suggestion or help?
Thanks

### PR DESCRIPTION
**Pull request by Laura7089**
This PR adds:

- `gethostname` (found [here](https://github.com/espressif/newlib-esp32/blob/esp-4.3.0/newlib/libc/include/sys/unistd.h#L287) in the ESP newlib fork, and [here](https://docs.esp-rs.org/esp-idf-svc/esp_idf_sys/fn.gethostname.html) in `esp-idf-svc`)
- ~~`_SC_HOST_NAME_MAX` (found [here](https://github.com/espressif/newlib-esp32/blob/esp-4.3.0/newlib/libc/include/sys/unistd.h#L401))~~

to `espidf`.

Closes #3748.

### CODE REVIEW

**Comment by Laura7089** [comment]
There is currently not a corresponding semver symbol check file (that I can find) for the ESP - am I looking in the wrong place?

**Comment by Laura7089** [comment]
Closes #3748.

**Comment by tgross35** [comment]
> There is currently not a corresponding semver symbol check file (that I can find) for the ESP - am I looking in the wrong place?

There isn't one, but feel free to start one. It won't get checked against anything for now but we can add it in the future.

> Closes #3748.

Goes in the PR description :)

---

Could you please add a link to the relevant headers providing these in the PR description?

@rustbot author

(just comment `@rustbot review` when it is ready for a look)

**Comment by Laura7089** [comment]
I'm having some trouble finding concrete definitions of `HOST_NAME_MAX` (or similar) in the ESP-IDF documentation or the newlib repo. Is it possible it's not defined in the IDF?

**Comment by tgross35** [comment]
I think this should be good, but it needs a rebase and to be marked ready for review. Unless you were waiting for confirmation on `HOST_NAME_MAX`?

@rustbot author

**Comment by Laura7089** [comment]
`sort` appears to change its behaviour based on the `LC_COLLATE` environment variable - may I suggest setting this in `ci/style.sh` to disambiguate the desired behaviour?

**Comment by tgross35** [comment]
> `sort` appears to change its behaviour based on the `LC_COLLATE` environment variable - may I suggest setting this in `ci/style.sh` to disambiguate the desired sort order?

Good idea, done in https://github.com/rust-lang/libc/pull/4026

**Pull request merged**
