### PR TITLE
musl fixes and musl+riscv32 fixes

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by kraj** [comment]
`cd libc-test && cargo test` fails on my archlinux _without_ my changes as well

```
OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-Wno-address-of-packed-member" "-Wno-unknown-warning-option" "-Wno-deprecated-declarations" "-D_GNU_SOURCE" "-D__GLIBC_USE_DEPRECATED_SCANF" "-o" "/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/627d083e0321a21f-main.o" "-c" "/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/main.c"
  cargo:warning=/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/main.c: In function ‘__test_roundtrip_inotify_event’:
  cargo:warning=/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/main.c:23146:13: note: the ABI of passing struct with a flexible array member has changed in GCC 4.4
  cargo:warning=23146 |             ) {
  cargo:warning=      |             ^
  cargo:warning=/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/main.c: In function ‘__test_fsize_af_alg_iv_iv’:
  cargo:warning=/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/main.c:25568:34: error: invalid application of ‘sizeof’ to incomplete type ‘__u8[]’ {aka ‘unsigned char[]’}
  cargo:warning=25568 |                     return sizeof(foo->iv);
  cargo:warning=      |                                  ^
  cargo:warning=/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/main.c:25569:17: error: control reaches end of non-void function [-Werror=return-type]
  cargo:warning=25569 |                 }
  cargo:warning=      |                 ^
  cargo:warning=At top level:
  cargo:warning=cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
  cargo:warning=cc1: all warnings being treated as errors
  exit status: 1

  --- stderr
  rust version: 1.68.2


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-Wno-address-of-packed-member" "-Wno-unknown-warning-option" "-Wno-deprecated-declarations" "-D_GNU_SOURCE" "-D__GLIBC_USE_DEPRECATED_SCANF" "-o" "/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/627d083e0321a21f-main.o" "-c" "/home/kraj/work/libc/target/debug/build/libc-test-04f83ede874c351b/out/main.c" with args "cc" did not execute successfully (status code exit status: 1).

```

**Comment by kraj** [comment]
nightly x86_64-unknown-freebsd-13 failure is build host related as well.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by JohnTitor** [comment]
Seems some consts are declared twice, @rustbot author

**Comment by akiernan** [comment]
https://github.com/rust-lang/libc/pull/3302

**Pull request closed without merging**
