### PR TITLE
Add a couple pthread function definitions and get_sched for musl.

### PR DESCRIPTION
**Pull request by mwanner**
I missed `pthread_setaffinity_np` for the musl variant, so I added a few missing function declarations for musl.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like there's some errors on CI though?

**Comment by mwanner** [comment]
> Thanks! Looks like there's some errors on CI though?

Hm.. interesting, test coverage without writing a test. Nice.

How do I run these tests locally?  Fails for me due to not finding `linux/input.h` (for target `x86_64-unknown-linux-musl`) or `linux/module.h` (against default system glibc).

**Comment by mwanner** [comment]
> You need to use the docket containers, check .travis.yml for how the run_docker script is called.

Ah, thanks, I'll try that.

**Comment by mwanner** [comment]
> Thanks! Looks like there's some errors on CI though?

I dropped the definitions for functions that musl really doesn't provide, squashed the two commits and rebased onto master.  This seems to pass CI just fine, now.  Please have another look.

**Comment by gnzlbg** [comment]
Looks like you've rebased one commit too much :/  

Otherwise LGTM. @alexcrichton this can be merged as is.

**Pull request merged**
