### PR TITLE
Add unix adjtime support.

### PR DESCRIPTION
**Pull request by guyru**

### CODE REVIEW

**Comment by guyru** [comment]
> broken_heart Test failed - [checks-actions](https://github.com/rust-lang/libc/runs/5996515299?check_suite_focus=true)

What does the checks-action test mean?

**Comment by Amanieu** [comment]
That's just the action that reports the build status at the end. You need to find the actual failure on the list on the left. In this case: https://github.com/rust-lang/libc/runs/5996464765?check_suite_focus=true

**Comment by Amanieu** [comment]
adjtime seems to be missing on Android.

**Pull request merged**
