### PR TITLE
Add schedule params & priority pthread functions

### LINKED ISSUE #609: Why is there no `pthread_setschedparam`
I want to set a priority for my thread. `std::thread` does not offer this. So I wanted to make my own crate for this. I have found that `libc` crate provides some `pthread` bindings but does not have `setschedparam` function. Why it is so?

### PR DESCRIPTION
**Pull request by vityafx**
Fixes #609. Provides bindings to `pthread_getschedparam`, `pthread_setschedparam` and `pthread_setschedprio` functions.

P.S. My first PR in such a project.
P.P.S. `libc-test` crashed at building stage with a lot of errors, so I hope `travis` will do a check.
P.P.P.S. These functions are tested to work on Linux (Ubuntu 14.04) with my own crate. I will release it next week, it provides ability to control thread schedule policies and priorities.

### CODE REVIEW

**Comment by vityafx** [comment]
I see the problem but will provide a fix only next week...

**Comment by alexcrichton** [comment]
Looks good to me! I'll r+ once CI is green

**Comment by vityafx** [comment]
As from what I have found in the Google `setschedprio` is not available at `osx`, `bsd` and `android`.
Also, I have filled an [issue](https://github.com/rust-lang/libc/issues/615) with my `libc-test` crate failures.

**Comment by vityafx** [comment]
@alexcrichton even though this was compiled successfully I am still not sure did I find the correct place for it or no. It seems each system decides own rules how to follow POSIX :/ But from what I have seen I think `pthread_setschedprio` is linux-only function.

**Comment by alexcrichton** [comment]
Ok this seems good for now regardless, thanks for the PR!

@bors: r+

**Comment by vityafx** [comment]
@alexcrichton I see that `bors` takes the whole first message here as a commit message. I think it should be changed, am I right?

**Comment by alexcrichton** [comment]
Ah no worries!

**Pull request merged**
