### PR TITLE
Add support for tvOS

### PR DESCRIPTION
**Pull request by thomcc**
This is essentially identical to the iOS support, as the OS is... essentially identical to iOS.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by thomcc** [comment]
Mind cutting a release with this in it at some point soon?

**Comment by JohnTitor** [comment]
Sure, I'll handle it after work.

**Comment by thomcc** [comment]
Thanks! No rush!

**Pull request merged**
