### PR TITLE
add struct ifmap

### PR DESCRIPTION
**Pull request by canndrew**

### CODE REVIEW

**Comment by semarie** [comment]
`struct ifmap` doesn't exist in BSDs (checked OpenBSD, and quickly grep
source tree of DragonFly, FreeBSD and NetBSD).

**Comment by canndrew** [comment]
@semarie Thanks :). I already moved it down into the `notbsd` part of the hierarchy.

**Comment by alexcrichton** [comment]
Should the fields here be `pub` so they can be accessed externally?

**Comment by canndrew** [comment]
> Should the fields here be `pub` so they can be accessed externally?

Yes. Good catch :p

**Comment by canndrew** [comment]
Worth a shot.

@alexcrichton: this one is ready to go as well

**Comment by alexcrichton** [comment]
I'm gonna close this now due to inactivity, but it can of course be resubmitted!

**Pull request closed without merging**
