### PR TITLE
solarish lgrp api update

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by jclulow** [comment]
Can you paste your test run output on your illumos system please?

**Comment by devnexen** [comment]
`uname -a && cargo test --manifest-path libc-test/Cargo.toml 
SunOS openindianavbox 5.11 illumos-c8f4a9f75f i86pc i386 i86pc
   Compiling libc-test v0.2.118 (/export/home/dcarlier/Contribs/libc/libc-test)
    Finished test [unoptimized + debuginfo] target(s) in 38.07s
     Running test/cmsg.rs (target/debug/deps/cmsg-5231031972d4331c)

running 5 tests
test t::test_cmsg_data ... ok
test t::test_cmsg_len ... ok
test t::test_cmsg_firsthdr ... ok
test t::test_cmsg_space ... ok
test t::test_cmsg_nxthdr ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.49s

     Running test/errqueue.rs (target/debug/deps/errqueue-60489a375b9e8639)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running test/linux_elf.rs (target/debug/deps/linux_elf-15f46b98d77e7a25)
PASSED 0 tests
     Running test/linux_fcntl.rs (target/debug/deps/linux_fcntl-0912f81c274f044d)
PASSED 0 tests
     Running test/linux_if_arp.rs (target/debug/deps/linux_if_arp-e6ceb8dc05379390)
PASSED 0 tests
     Running test/linux_ipv6.rs (target/debug/deps/linux_ipv6-9fda4a29281a8751)
PASSED 0 tests
     Running test/linux_strerror_r.rs (target/debug/deps/linux_strerror_r-9bb9ef9cebf5a325)
PASSED 0 tests
     Running test/linux_termios.rs (target/debug/deps/linux_termios-d2b009b541d35a54)
PASSED 0 tests
     Running test/main.rs (target/debug/deps/main-983bb6a8e4b85924)
RUNNING ALL TESTS
PASSED 7514 tests
     Running test/semver.rs (target/debug/deps/semver-999d9960c6775712)
PASSED 1 tests
     Running test/sigrt.rs (target/debug/deps/sigrt-adc2fb5c533c424a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s`

**Comment by jclulow** [comment]
Thanks -- looks good to me!

**Pull request merged**
