### PR TITLE
linux add timer api

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Hm, the lint now covers one more pattern (#86426), I'll handle it later.

**Comment by 12101111** [comment]
Is `#[link(name = "rt")]` needed? It's already linked here: https://github.com/rust-lang/libc/blob/90aa0e32eca33ccec050c034c438b1b703f16449/src/unix/mod.rs#L310-L311

**Pull request merged**
