### PR TITLE
Haiku: add definitions for the Haiku's native sytem API.

### PR DESCRIPTION
**Pull request by nielx**
On the Haiku platform, the POSIX (and BSD) API coexists with the native API,
that has its origins on the BeOS platform. Unlike other UNIX-like platforms,
the native API is not an extension of the POSIX API, but instead exists sui
generis, and many of the POSIX concepts have their own native variety, with
relatively limited interoperability.

Nonetheless, the native API coexists in the same library as the standard C and
POSIX functions, namely libroot.so, and therefore this crate is a good place
to add bindings to it.

This commit implements most of Haiku's support kit, the most important parts
of the kernel kit, and a part of the storage kit.

### CODE REVIEW

**Comment by nielx** [comment]
@kallisti5 @jessicah @ahwayakchih Since you have contributed to the Haiku bindings before, could you have a look and perhaps add some comments?

**Comment by nielx** [comment]
I'm working on the style and semantic issues pointed out by the CI.

**Comment by kallisti5** [comment]
This patch looks like an awesome start to Haiku having improved rust support.   Our rust toolchain is fairly up to date, and critical rust crates [have](https://github.com/rust-lang/socket2/pull/136) been receiving [patches](https://github.com/deprecrated/net2-rs/pull/109) improving support.

**Comment by nielx** [comment]
Changes since previous push:

- reorder the file a bit more to be consistent with the other files
- added some more bindings to the native API (kernel/fs_*.h)
- checked the validity using the libc-test process. I will send a PR to enable libc-test for Haiku soon.

This change is ready for review.

**Comment by kallisti5** [comment]
@JohnTitor  This one's looking pretty solid and fills in a lot of missing base libc stuff from Haiku.  Thoughts?

**Comment by JohnTitor** [comment]
Hey, thanks for PR!

@nielx Do you want me to make a new relase for `ctest2` and run libc-test here?

**Comment by nielx** [comment]
@JohnTitor That would be appreciated. I have some follow-up work to this commit that adds support for libc-test and that applies some fixes that it pointed out, so if there is a ctest2 package that supports Haiku, it will allow others to reproduce the tests and build on that work.

**Comment by JohnTitor** [comment]
Okay, published ctest2 0.4.0.

**Comment by nielx** [comment]
I added support for Haiku in the testing framework, and the fixes for the issues that it pointed out.

**Comment by nielx** [comment]
@JohnTitor Anything I can do to help you progress this?

**Comment by JohnTitor** [comment]
Hey, thanks for the ping!
Could we add a Docker image and tweak the CI config so that we can run CI for Haiku?
One question, it seems this has some breaking changes, does it mean the old definitions are incorrect and won't work anyway? If so, I think this is acceptable. If not (e.g. it has been recently changed), I wonder this breaks some uses.

**Comment by nielx** [comment]
> Could we add a Docker image and tweak the CI config so that we can run CI for Haiku?

It should be possible to set up a cross-compiling CI configuration to build libc for Haiku. I don't think it is possible to build and run the tests that way. Haiku is not (yet) virtualizable friendly, so I there's not such a thing as a Haiku VM image yet. I do wonder what the relative value of a continuous CI build would be, but we can certainly try to set it up.

> One question, it seems this has some breaking changes, does it mean the old definitions are incorrect and won't work anyway? If so, I think this is acceptable. If not (e.g. it has been recently changed), I wonder this breaks some uses.

The old definitions have always been incorrect.

**Review by JohnTitor — APPROVED** [review]
Okay, thanks for clarifying! Looks good to me now.

**Pull request merged**
