### PR TITLE
redox: correct EPOLL constants

### PR DESCRIPTION
**Pull request by jackpot51**
Reference: https://gitlab.redox-os.org/redox-os/relibc/-/commit/0f5e6a5649dba7979f5b78965a68268c1f8ff894

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you rebase to make CI green?

**Comment by tgross35** [comment]
@jackpot51 gentle nudge, as mentioned above this just needs a rebase

@rustbot author

**Comment by jackpot51** [comment]
Sorry for the delay, I have rebased it now.

**Review by tgross35 — APPROVED** [review]
Thanks!

**Comment by tgross35** [comment]
Oh, looks like no backport is needed since these were already in 0.2 from https://github.com/rust-lang/libc/pull/3686.

**Pull request merged**
