### PR TITLE
fixes some netbsd compile errors

### PR DESCRIPTION
**Pull request by dhuseby**
cleaning up the netbsd build a bit.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like there are some OpenBSD compile errors? The iOS ones seem unrelated and I can fix those separately

**Comment by dhuseby** [comment]
@alexcrichton i think i fixed the compile error.

**Comment by alexcrichton** [comment]
Looks like the automation disagrees with the change to `st_spare`?

**Comment by dhuseby** [comment]
@alexcrichton this is a generated test?  I'm not sure how to fix this.  I tried to track it down in the libc-test folder but it must be autogenerating code based on the struct's fields because there is no explicit reference to st_spare.  That suggests the autogenerating code is wrong or can't handle that special case.

**Comment by alexcrichton** [comment]
Yeah these are generated tests, and it was correct beforehand, so why the change?

**Comment by dhuseby** [comment]
@alexcrichton because of the function here: https://github.com/dhuseby/rust/blob/master/src/libstd/os/netbsd/fs.rs#L151  but now I think the real solution is to fix rust/src/libstd instead of changing libc.

**Comment by alexcrichton** [comment]
On netbsd that function should probably just be removed or properly remove `[u32; 2]`, it's intended that the trait returns the platform-specific types

**Comment by alexcrichton** [comment]
Sounds like the symbols were taken care of in https://github.com/rust-lang/libc/pull/197, and libstd probably just needs to be corrected for the stat, so closing. Feel free to reopen though if I'm missing something!

**Comment by dhuseby** [comment]
@alexcrichton kthx

**Pull request closed without merging**
