### PR TITLE
Default RHS to Self for Div and Shl

### PR DESCRIPTION
**Pull request by npmccallum**
This fixes a consistency issue with the other operator traits.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! These are just used during documentation, however, so is this change required for correctness?

**Comment by npmccallum** [comment]
@alexcrichton I assumed it would be required for correct documentation. :)

**Comment by alexcrichton** [comment]
Oh we don't actually document these traits as part of the build, they're just required to document other things (it's sort of a hack today)

**Comment by npmccallum** [comment]
I don't take this patch to be urgent. I just took it to be easy while I was fixing the actual code in the rust bug. :)

https://github.com/rust-lang/rust/pull/49630

**Pull request merged**
