### PR TITLE
Add riscv64gc-unknown-freebsd support

### PR DESCRIPTION
**Pull request by t6**
Also see https://github.com/rust-lang/rust/pull/91284

### CODE REVIEW

**Comment by Amanieu** [comment]
This is blocked on https://github.com/rust-lang/rust/pull/91284. Once that PR is merged and is available in a nightly, please add a build-check on CI by adding `riscv64gc-unknown-freebsd` to `RUST_LINUX_NO_CORE_TARGETS` in `ci/build.sh`.

**Comment by t6** [comment]
Added it to `ci/build.sh`.

**Pull request merged**
