### PR TITLE
Add ucontext_t for freebsd-aarch64

### LINKED ISSUE #3217: ucontext_t is missing on aarch64-unknown-freebsd
2e3999ddf0fa added `mcontext_t` but not `ucontext_t`. FreeBSD `ucontext_t` is machine-independent but libc crate limits it by `target_arch`.

See [ucontext_t definition](https://github.com/freebsd/freebsd-src/blob/releng/13.2/sys/sys/_ucontext.h) vs. [mcontext_t definition](https://github.com/freebsd/freebsd-src/blob/releng/13.2/sys/arm64/include/ucontext.h)

```rust
error[E0412]: cannot find type `ucontext_t` in crate `libc`
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:219:57
    |
219 |               let ucontext = &mut *(context as *mut libc::ucontext_t);
    |                                                           ^^^^^^^^^^ help: a struct with a similar name exists: `mcontext_t`
    |
   ::: veloren-4b6c5f57e3a9/cargo-crates/libc-0.2.133/src/unix/bsd/freebsdlike/freebsd/aarch64.rs:20:1
    |
20  | / s_no_extra_traits! {
21  | |     pub struct gpregs {
22  | |         pub gp_x: [::register_t; 30],
23  | |         pub gp_lr: ::register_t,
..   |
44  | |     }
45  | | }
    | |_- similarly named struct `mcontext_t` defined here

error[E0412]: cannot find type `ucontext_t` in crate `libc`
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:259:45
    |
259 |           unsafe fn get_pc_sp(context: &libc::ucontext_t) -> (usize, usize) {
    |                                               ^^^^^^^^^^ help: a struct with a similar name exists: `mcontext_t`
    |
   ::: veloren-4b6c5f57e3a9/cargo-crates/libc-0.2.133/src/unix/bsd/freebsdlike/freebsd/aarch64.rs:20:1
    |
20  | / s_no_extra_traits! {
21  | |     pub struct gpregs {
22  | |         pub gp_x: [::register_t; 30],
23  | |         pub gp_lr: ::register_t,
..   |
44  | |     }
45  | | }
    | |_- similarly named struct `mcontext_t` defined here

error[E0412]: cannot find type `ucontext_t` in crate `libc`
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:314:54
    |
314 |           unsafe fn update_context(context: &mut libc::ucontext_t, regs: TrapHandlerRegs) {
    |                                                        ^^^^^^^^^^ help: a struct with a similar name exists: `mcontext_t`
    |
   ::: veloren-4b6c5f57e3a9/cargo-crates/libc-0.2.133/src/unix/bsd/freebsdlike/freebsd/aarch64.rs:20:1
    |
20  | / s_no_extra_traits! {
21  | |     pub struct gpregs {
22  | |         pub gp_x: [::register_t; 30],
23  | |         pub gp_lr: ::register_t,
..   |
44  | |     }
45  | | }
    | |_- similarly named struct `mcontext_t` defined here

error[E0425]: cannot find value `pc` in this scope
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:420:59
    |
420 |                     context.uc_mcontext.mc_gpregs.gp_pc = pc as libc::register_t;
    |                                                           ^^ not found in this scope

error[E0425]: cannot find value `sp` in this scope
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:421:59
    |
421 |                     context.uc_mcontext.mc_gpregs.gp_sp = sp as libc::register_t;
    |                                                           ^^ not found in this scope

error[E0425]: cannot find value `x0` in this scope
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:422:61
    |
422 |                     context.uc_mcontext.mc_gpregs.gp_x[0] = x0 as libc::register_t;
    |                                                             ^^ not found in this scope

error[E0425]: cannot find value `x1` in this scope
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:423:61
    |
423 |                     context.uc_mcontext.mc_gpregs.gp_x[1] = x1 as libc::register_t;
    |                                                             ^^ not found in this scope

error[E0425]: cannot find value `x29` in this scope
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:424:62
    |
424 |                     context.uc_mcontext.mc_gpregs.gp_x[29] = x29 as libc::register_t;
    |                                                              ^^^ not found in this scope

error[E0425]: cannot find value `lr` in this scope
   --> veloren-4b6c5f57e3a9/cargo-crates/wasmer-vm-2.3.0/src/trap/traphandlers.rs:425:62
    |
425 |                     context.uc_mcontext.mc_gpregs.gp_x[30] = lr as libc::register_t;
    |                                                              ^^ not found in this scope

Some errors have detailed explanations: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `wasmer-vm` due to 9 previous errors
```

### PR DESCRIPTION
**Pull request by nathaniel-bennett**
Resolves #3217

### CODE REVIEW

**Comment by tgross35** [comment]
The ucontext changes look good, but could you link whatever you are referencing for `mcontext_t`? https://github.com/freebsd/freebsd-src/blob/1a207e5cdf997bd5a04e020d26039844a0c1294f/sys/arm64/include/ucontext.h#L54-L61 (linked from https://github.com/rust-lang/libc/issues/3217) has a different definition.

**Comment by nathaniel-bennett** [comment]
The definition you link is included in the `aarch64.rs` submodule, which is intended for 64-bit ARM. The one I added is in the `arm.rs` submodule for 32-bit ARM architectures; its corresponding documentation can be found here:

https://github.com/freebsd/freebsd-src/blob/2b7f2890a812eb09dccaa8069483566a3b292338/sys/arm/include/ucontext.h#L74-L84

Likewise, documentation for PowerPC can be found here:

https://github.com/freebsd/freebsd-src/blob/2b7f2890a812eb09dccaa8069483566a3b292338/sys/powerpc/include/ucontext.h#L39-L51

**Review by tgross35 — APPROVED** [review]
Sorry I missed this, thanks for the extra info!

This is okay to go on stable but it isn't a clean cherry pick due to `#[align]`. I'll try to get it at some point, but feel free to resubmit this against the 0.2 branch if you want to get it in a bit sooner.

**Comment by tgross35** [comment]
@asomers could I get an ack from you before I backport this?

**Comment by asomers** [comment]
nack @tgross35 there's an error for armv7.  I'll open a PR to fix it.

**Pull request merged**
