### PR TITLE
update libc-test and its libc dependency to 0.2.148

### PR DESCRIPTION
**Pull request by chenx97**
Please make a release so I can use the changes I made for MIPS R6 :)

### CODE REVIEW

**Comment by Dirreke** [comment]
and I would like to let #3301 go too. Thanks!

**Comment by Dirreke** [comment]
Could you merge it? Thanks. @JohnTitor

**Comment by JohnTitor** [comment]
Let me clean up the PR queue before this.

**Comment by JohnTitor** [comment]
Sorry for not getting back to y'all sooner! I haven't had enough time to cut a new release, but I will have it this weekend (hopefully, though!).

**Comment by chenx97** [comment]
Did you have enough time this weekend 😇

**Comment by JohnTitor** [comment]
Sorry, no! @Amanieu Could you handle this if you have time?

**Comment by chenx97** [comment]
@joshtriplett Could you handle this if you have time?

**Comment by chenx97** [comment]
@joshtriplett I see that you bumped the version of the main crate, but not the dependency of the test. This PR should now do it for you.

**Pull request merged**
