### PR TITLE
Add final rtnetlink constants

### PR DESCRIPTION
**Pull request by jbaublitz**
This is a follow up to the PR #1351 which is for issue #1059 as it was closed before I realized there's one last set of netlink constants needed for use with rtnetlink. I'm marking this as WIP until I've verified everything's good with CI and that I've included all necessary constants. I'll remove WIP once it's passing CI and it's ready for review.

### CODE REVIEW

**Comment by gnzlbg** [comment]
good bot

**Comment by jbaublitz** [comment]
@gnzlbg All right, should be good to go. Thanks!

**Comment by jbaublitz** [comment]
retry

**Comment by jbaublitz** [comment]
Killjoy bot :slightly_frowning_face:

**Comment by skrap** [comment]
@jbaublitz: was there a reason that you did not include the RTM message type defines in here?  Like RTM_NEWLINK, RTM_DELLINK, etc?

**Comment by jbaublitz** [comment]
@skrap Oversight on my part due to the formatting for the `man 7 rtnetlink` docs. This should be included. I'll put together another PR for `libc` and (as I'm guessing this is why you're asking) I'll provide support in [neli](https://github.com/jbaublitz/neli).

**Comment by skrap** [comment]
Hah, yeah, you're onto me 😆 .  I'd be more than happy to help out in some way — perhaps I could provide something to add to the neli examples collection using some of those new constants?

**Comment by jeromegn** [comment]
I probably don't know enough, but is there a reason these constants can't be added for musl? If I had to guess: they're not defined in musl.

Trying to use rtnetlink with a musl target is not possible right now.

**Comment by jbaublitz** [comment]
@jeromegn Are you using libc directly? If so, only certain constants should not be usuable from musl. The rest are in both GNU and musl.

**Comment by jeromegn** [comment]
I'm not, but rtnetlink requires constants such as `NETLINK_CAP_ACK`. Sorry, this is likely the wrong place to write about this (I realize this now).

I should look into neli and see if it compiles on x86 64 unknown musl.

**Comment by jbaublitz** [comment]
I've tried to make neli compatible with musl because of what I learned doing this PR so please file an issue with neli and I'd be happy to take a look if it doesn't work as expected. If you need additional constants through neli, also file an issue there and I'll do another PR to libc.

**Pull request merged**
