### PR TITLE
Added linger struct

### PR DESCRIPTION
**Pull request by sateffen**
Added linger struct like mentioned in #327 

I looked up documentations on some platforms, and all look the same in the unix world. Additionally I've tested this with a local setup, building it against [this](https://github.com/rust-lang-nursery/net2-rs/pull/44) pullrequest, and it works well.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like this is defined the same everywhere, perhaps the definition could go in `src/unix/mod.rs`?

**Comment by sateffen** [comment]
Fugg, I could have foreseen this^^

I looked for each SO_LINGER to have a linger struct with it, but I failed to recognize this is on each platform. Thanks for the hint! I'll change this as soon as I've got some time.

Thanks @alexcrichton for your patience and guidance through my rust learning experience, even though this are embarrassing problems that don't have anything to do with rust^^

**Comment by sateffen** [comment]
Done the refactoring. Works with my test setup (on a cloud9 machine)

**Comment by alexcrichton** [comment]
Awesome, and no worries!

**Pull request merged**
