### PR TITLE
Add missing kqueue constants across BSDs

### PR DESCRIPTION
**Pull request by valpackett**
While here, reorder some to match the C headers

### CODE REVIEW

**Review by semarie — APPROVED** [review]
regarding OpenBSD, it LGTM

**Comment by valpackett** [comment]
ping

**Review by JohnTitor — APPROVED** [review]

**Comment by valpackett** [comment]
That's some new checks introduced in nightly rust 👀

> thread 't::test_cmsg_nxthdr' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x1b6966ed4d1', libc-test/test/cmsg.rs:74:25

google showing one result

Looks like this: https://github.com/rust-lang/rust/pull/98112

**Pull request merged**
