### PR TITLE
Add more items from `include/linux/sched.h` header

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
More items coming from the header file `include/linux/sched.h`.

Re-opening of #3513 because of a wrong push on my end (sorry).

r? @JohnTitor

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
👍 @bors r+

**Comment by GuillaumeGomez** [comment]
Ah I see failures is fixed in https://github.com/rust-lang/libc/pull/3516. Thanks for working on it!

**Comment by JohnTitor** [comment]
Should be fixed now! @bors retry

**Comment by GuillaumeGomez** [comment]
Thanks for your help! :)

**Pull request merged**
