### PR TITLE
Do not assume dynamic linking in musl/mips targets

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by malbarbo** [comment]
Required for https://github.com/rust-lang/rust/pull/47663

**Comment by alexcrichton** [comment]
Due to the usage of `target_feature` I think this won't break the current target when landing, right?

**Comment by malbarbo** [comment]
I think it will break... The target definition is initialized using `..super::linux_base::opts()`, which returns `crt_static_respected = false`...

**Comment by malbarbo** [comment]
Considering that we are not changing the default linking mode in https://github.com/rust-lang/rust/pull/47663 anymore, can this be merged?

**Comment by alexcrichton** [comment]
@malbarbo hm I'm not sure I could say w/o testing, mind testing before and after this change to see if the targets build correctly?

**Comment by malbarbo** [comment]
I had tested it with both static and dynamic linking. I tested it again after changing `crt_static_respected = false`. Both works as expected.

I had forgotten to commit the -fPIC changes, but I pushed it now.

**Comment by alexcrichton** [comment]
Ok!

@bors: r+

**Pull request merged**
