### PR TITLE
add definitions for s390x musl targets

### PR DESCRIPTION
**Pull request by kaniini**
Add support for s390x musl targets to libc.

I haven't added CI because I am not familiar with the pipelines, but would be glad to do so if somebody outlines what needs to be done.

### CODE REVIEW

**Comment by kaniini** [comment]
CI is mostly blocking on rust-lang/rust#82166 being merged, which adds the s390x-unknown-linux-musl target.

**Comment by Amanieu** [comment]
LGTM. Let's wait on rust-lang/rust#82166 so we can have CI set up.

I'm not too familiar with the libc CI, but basically just copy what we're already doing for other architectures on musl (e.g. mips, arm). The relevant files are all in `ci/`.

**Comment by kaniini** [comment]
Yeah that's why I decided to go with #82166 first.  Then handle the libc bits and any std bits afterward.

**Review by workingjubilee — COMMENTED** [review]
These all are destined to go into fn ioctl which is expecting a c_int.

**Comment by kaniini** [comment]
Based on conversation in Zulip, I wonder if it makes sense to move a lot of these constants to the common part of the musl support code.

**Comment by workingjubilee** [comment]
Yes, I think so, that's kind of how the libc crate is "supposed" to be designed (according to https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md anyways!). Probably using a similar structure as the "generic bits" vs. "arch-specific bits" pattern that musl uses for its own organization.

**Comment by kaniini** [comment]
@Amanieu this should be good to go now.  rust#82166 has landed.

**Comment by Amanieu** [comment]
Is ci/s390x-linux-musl.json still needed?

**Comment by kaniini** [comment]
git, how does it even work?

**Comment by Amanieu** [comment]
You need to add the target to .github/workflows/bors.yml so it gets picked up by CI.

**Comment by kaniini** [comment]
oh, technically the s390x-unknown-linux-musl target is tier 3 atm.  can we just skip the CI?  or how do you want to tackle it?

**Comment by Amanieu** [comment]
Ah good point, let's just skip it for now.

**Pull request merged**
