### PR TITLE
Add various strcase* functions and getline

### PR DESCRIPTION
**Pull request by palfrey**
Adds
* `strcasestr`
* `strcasecmp`
* `strncasecmp`
*  `getline`

I *think* they're semi-universal, but shall see what CI pops up...

### CODE REVIEW

**Comment by gnzlbg** [comment]
It appears that freebsd lacks `getline`.

**Comment by palfrey** [comment]
@gnzlbg https://www.freebsd.org/cgi/man.cgi?query=getline&apropos=0&sektion=0&manpath=FreeBSD+8.2-RELEASE&format=html indicates FreeBSD 8.0+ has getline, but only if you define `_WITH_GETLINE`, so let's try that...

**Comment by gnzlbg** [comment]
r? @gnzlbg 

@palfrey please ping me when CI is green

**Comment by gnzlbg** [comment]
The windows `msvc` toolchains are failing with:

```
C:\projects\libc\target\x86_64-pc-windows-msvc\debug\build\libc-test-9926ed016ab2f41f\out\main.c(591): error C2065: 'strcasecmp': undeclared identifier
C:\projects\libc\target\x86_64-pc-windows-msvc\debug\build\libc-test-9926ed016ab2f41f\out\main.c(591): warning C4047: 'return': 'int (__cdecl *)(const char *,const char *)' differs in levels of indirection from 'int'
C:\projects\libc\target\x86_64-pc-windows-msvc\debug\build\libc-test-9926ed016ab2f41f\out\main.c(596): error C2065: 'strncasecmp': undeclared identifier
C:\projects\libc\target\x86_64-pc-windows-msvc\debug\build\libc-test-9926ed016ab2f41f\out\main.c(596): warning C4047: 'return': 'int (__cdecl *)(const char *,const char *,std::size_t)' differs in levels of indirection from 'int'
```

Could you take a look?

**Comment by gnzlbg** [comment]
I think it would be good to add these to `redox`, `cloudabi`, etc. as well.

**Comment by palfrey** [comment]
b05e05819da2e2cc3dc15deb6c784bdee3328f3f is a bit of a hack, but I managed to hit (temporarily) one of the Travis issues locally and manually pulling the Docker images before building seemed to fix the problem

**Comment by palfrey** [comment]
Good news: down to just 1 failure ;)
Bad news: Failure on sparc64-unknown-linux-gnu
```
+ curl -LO https://cdimage.debian.org/cdimage/ports/9.0/sparc64/iso-cd/debian-9.0-sparc64-NETINST-1.iso
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   362  100   362    0     0    456      0 --:--:-- --:--:-- --:--:--   456
  0     0    0     0    0     0      0      0 --:--:--  0:05:01 --:--:--     0
curl: (28) Operation timed out after 300808 milliseconds with 0 out of 0 bytes received
```
Pretty sure this still isn't due to this PR...

**Comment by gnzlbg** [comment]
Thank you!

**Pull request merged**
