### PR TITLE
Fix --no-default-features builds

### LINKED ISSUE #928: Hard error compiling libc 0.2.36: #![feature(link_cfg)] missing ?
```shell 
 Compiling libc v0.2.36
error[E0658]: is feature gated (see issue #37406)
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.36/src/unix/mod.rs:279:9
    |
279 |         #[link(name = "c", kind = "static", cfg(target_feature = "crt-static"))]
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(link_cfg)] to the crate attributes to enable
```

### PR DESCRIPTION
**Pull request by gnzlbg**
Closes #928 #929 #684

### CODE REVIEW

**Comment by gnzlbg** [comment]
Is there a reason for the `run.sh` script to use `exec` to invoke cargo test on libc-test? ping: @malbarbo

**Comment by gnzlbg** [comment]
The failure is not my fault. That `target_vendor` thing should probably have a `#[cfg_attr]` for libstd as well.

**Comment by alexcrichton** [comment]
@gnzlbg for now could similar logic be applied to only take that branch when building in libstd?

**Comment by gnzlbg** [comment]
@alexcrichton I've pushed a fix for that, hopefully that won't break anything else.

**Comment by clarcharr** [comment]
Could a new version of libc be released that includes this change?

**Comment by alexcrichton** [comment]
Sure! Instructions for how to do so [are here](https://github.com/rust-lang/libc#releasing-your-change-to-cratesio)

**Comment by clarcharr** [comment]
@alexcrichton it appears that the version has already been bumped since the change, but it wasn't pushed to crates.io

**Comment by alexcrichton** [comment]
Oops sorry about that, published now!

**Pull request merged**
