### PR TITLE
Add some constant and struct on macOS

### PR DESCRIPTION
**Pull request by LuoZijun**
file: `net/bpf.h`

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like CI may be red though?

**Comment by LuoZijun** [comment]
@alexcrichton ping ...

**Comment by alexcrichton** [comment]
@LuoZijun oh when you update it feel free to ping me, I don't check this every hour for a green test passing!

@bors: r+

**Comment by LuoZijun** [comment]
@alexcrichton got it :)

**Pull request merged**
