### PR TITLE
ci: Upload artifacts created by libc-test

### PR DESCRIPTION
**Pull request by tgross35**
This gives us something that is easier to look at when the automatically generated tests fail.

### CODE REVIEW

**Comment by tgross35** [comment]
@asomers it seems like the FreeBSD 15 runner is giving us an error that `CAP_UNUSED0_44` is undeclared. Do you know if there is a recent change that we should adjust or skip this for?

**Comment by asomers** [comment]
Yep.  https://github.com/freebsd/freebsd-src/commit/b165e9e3ea4e327fc421d81c2a89242bd8720780 deleted that definition.  I wonder if we should just delete all of the CAP_UNUSED constants, for the same reason that we don't allow constants like XXX_MAX or RLIM_NLIMITS?

**Comment by asomers** [comment]
@tgross35 see #4183 and #4184 for the `CAP_UNUSED0_44` fix.

**Comment by tgross35** [comment]
I was going to say it's entirely up to you, it seemed like capsicum was the only user based on a quick search. Appreciate the fast PRs.

**Pull request merged**
