### PR TITLE
Add exchangedata for bsd

### PR DESCRIPTION
**Pull request by debris**
docs: ` https://www.unix.com/man-page/osx/2/exchangedata/

### CODE REVIEW

**Comment by mati865** [comment]
Looks legit:
```
cargo:warning=/checkout/target/x86_64-rumprun-netbsd/debug/build/libc-test-a83d36f94edd2cc5/out/main.c: In function '__test_fn_exchangedata':
cargo:warning=/checkout/target/x86_64-rumprun-netbsd/debug/build/libc-test-a83d36f94edd2cc5/out/main.c:5424:24: error: 'exchangedata' undeclared (first use in this function)
cargo:warning=                 return exchangedata;
cargo:warning=                        ^
cargo:warning=/checkout/target/x86_64-rumprun-netbsd/debug/build/libc-test-a83d36f94edd2cc5/out/main.c:5424:24: note: each undeclared identifier is reported only once for each function it appears in
cargo:warning=/checkout/target/x86_64-rumprun-netbsd/debug/build/libc-test-a83d36f94edd2cc5/out/main.c:5425:13: error: control reaches end of non-void function [-Werror=return-type]
cargo:warning=             }
cargo:warning=             ^
cargo:warning=cc1: all warnings being treated as errors
exit code: 1
```

**Comment by semarie** [comment]
`exchangedata()` doesn't exist under OpenBSD

**Comment by alexcrichton** [comment]
I'm gonna close this now due to inactivity, but it can of course be resubmitted!

**Pull request closed without merging**
