### PR TITLE
Add `SYS_lseek` and `SYS_mmap` for aarch64 Android

### PR DESCRIPTION
**Pull request by lberrymage**
Values are sourced from https://android.googlesource.com/platform/bionic/+/0339184/libc/kernel/uapi/asm-generic/unistd.h.

I noticed these constants were missing when compiling for the aarch64-linux-android target.

I'm not entirely sure whether I added the semver tests correctly, so please let me know if those need changes.

### CODE REVIEW

**Comment by lberrymage** [comment]
The CI failures appear to be unrelated:

```
  = note: /usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: /rust/lib/rustlib/aarch64-unknown-linux-musl/lib/libstd-55a85b3d629131f6.rlib(std-55a85b3d629131f6.std.e271c4a0ea64dd3f-cgu.0.rcgu.o): in function `std::sys::pal::unix::thread::Thread::get_name':
          /rustc/0824b300eb0dae5d9ed59719d3f2732016683d66/library/std/src/sys/pal/unix/thread.rs:233:(.text._ZN3std3sys3pal4unix6thread6Thread8get_name17h151b5832ae5a589dE+0x30): undefined reference to `pthread_getname_np'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)
```

**Comment by JohnTitor** [comment]
Could you rebase? The CI failure has been fixed on the latest libc-0.2 branch.

**Comment by lberrymage** [comment]
Rebased and CI is now passing.

**Review by JohnTitor — APPROVED** [review]
Thanks!

**Pull request merged**
