### PR TITLE
apple add ctl_info.

### LINKED ISSUE #3045: Missing `struct ctl_info` of MacOS
This structure is used with the `CTLIOCGINFO` ioctl to translate from a kernel control name to a control id.
`CTLIOCGINFO` is missing as well.

### PR DESCRIPTION
**Pull request by devnexen**
closes #3045.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Duplicate of https://github.com/rust-lang/libc/pull/3046?

**Comment by devnexen** [comment]
true :)

**Comment by siegfried** [comment]
Maybe this one is better?

**Comment by devnexen** [comment]
@siegfried @JohnTitor whatever you prefer ;-)

**Comment by JohnTitor** [comment]
Oh, I didn't check the diff carefully! Anyway, I don't mind either. For now, I'm going to merge #3046 but feel free to follow-up if you need these consts :)

**Pull request closed without merging**
