### PR TITLE
linux/android aarch64 add user_regs_struct and user_fpsimd_struct

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by irgstg** [comment]
Hi,

Seems like there is a wide awareness around this issue:
https://github.com/gnzlbg/ctest/pull/89
https://github.com/rust-lang/rust/issues/54341

Do you think that a PR which includes `user_regs_struct` alone, while opening an issue regarding `user_fpsimd_struct` would be a better idea?

Thanks ;)

**Comment by irgstg** [comment]
I think it'll pass w/o any problems now @Amanieu

**Comment by irgstg** [comment]
I don't see how this fail is relate to this PR

**Comment by devnexen** [comment]
test time out it seems. it happens on occasion.

**Pull request merged**
