### PR TITLE
Add more constants for getnameinfo on android

### PR DESCRIPTION
**Pull request by coolreader18**

### CODE REVIEW

**Comment by coolreader18** [comment]
I think the ci failure is just because of a network failure

**Comment by JohnTitor** [comment]
Re-triggering CI.

**Comment by coolreader18** [comment]
Yup, looks like it's fine now.

**Comment by coolreader18** [comment]
By the way, here's what the relevant section of the ndk netdb.h header looks like, which I used as a source:
```h
/*
 * Constants for getnameinfo()
 */
#define	NI_MAXHOST	1025
#define	NI_MAXSERV	32

/*
 * Flag values for getnameinfo()
 */
#define	NI_NOFQDN	0x00000001
#define	NI_NUMERICHOST	0x00000002
#define	NI_NAMEREQD	0x00000004
#define	NI_NUMERICSERV	0x00000008
#define	NI_DGRAM	0x00000010
#if 0 /* obsolete */
#define NI_WITHSCOPEID	0x00000020
#endif
```

**Pull request merged**
