### PR TITLE
Add IPV6_FREEBIND to Fuchsia

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
No idea if this is the correct value, I copied it from Linux.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
@tamird can you confirm the value is correct?

**Comment by Amanieu** [comment]
Are you sure this flag is actually supported on fuchsia? It doesn't seem to be handled here: https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/sdk/lib/fdio/socket.cc

**Comment by tamird** [comment]
Does not appear to exist on Fuchsia. https://cs.opensource.google/search?q=IPV6_FREEBIND&sq=&ss=fuchsia

I  think we could upgrade the definitions from musl but haven't had a need for it yet.

cc @ghanan94

**Comment by Thomasdezeeuw** [comment]
Closing this since Fuchsia doesn't seem to have the constant.

**Pull request closed without merging**
