### PR TITLE
Solarish: add the arc4random* API family

### PR DESCRIPTION
**Pull request by devnexen**
[solaris](https://docs.oracle.com/cd/E88353_01/html/E37843/arc4random-buf-3c.html)
[illumos](https://illumos.org/man/3C/arc4random_buf)

### CODE REVIEW

**Comment by RalfJung** [comment]
This would help remove a [FIXME](https://github.com/rust-lang/rust/blob/b9d47cfa9b8f0805bfab2c254a02e598a906f102/library/std/src/sys/random/arc4random.rs#L20-L30) in `std`.

**Comment by tgross35** [comment]
Thanks for linking the docs. LGTM but I'll wait for one of the solarish people to double check this, or merge it in another day or two if we don't hear back.

**Review by tgross35 — APPROVED** [review]

**Comment by RalfJung** [comment]
@devnexen maybe you can add the docs link to the PR description, so they become part of the commit message.

(As I already told you in multiple past PRs, please write descriptions for your PRs! It makes them much easier to review, and therefore much more likely to be landed.)

**Comment by tgross35** [comment]
@jclulow, @pfmooney would one of you be able to ack this?

**Comment by tgross35** [comment]
This looks fine to me so I will merge it, but wait for a solarish set of eyes before backport (@jclulow)

**Pull request merged**
