### PR TITLE
Bump version to 0.2.141

### PR DESCRIPTION
**Pull request by arjentz**
Bump version as requested in https://github.com/rust-lang/socket2/issues/405

### CODE REVIEW

**Comment by JohnTitor** [comment]
Let me merge some more PRs in the review queue.

**Comment by jbg** [comment]
FYI, upwards of 48,500 crates currently fail to build on all musl targets because libc 0.2.140 is broken on musl. IMHO, it may be worth considering yanking 0.2.140 and/or publishing a quick 0.2.141 even without the extra merged PRs.

**Comment by arjentz** [comment]
Maybe I failed to express the urgency of this PR. I figured it'd be merged and released pretty quickly (and I didn't have the numbers handy). Thanks @jbg!

@JohnTitor It would be great if we could get the release out ASAP

**Comment by JohnTitor** [comment]
It's interesting that you don't have even a single word of appreciation for my maintaining this crate and making releases, whereas you immediately downvote me for asking you to wait a bit to take care of the PR waiting for review. _Sigh_.

**Comment by jbg** [comment]
> > FYI, upwards of 48,500 crates currently fail to build on all musl targets because libc 0.2.140 is broken on musl. IMHO, it may be worth considering yanking 0.2.140 and/or publishing a quick 0.2.141 even without the extra merged PRs.
> 
> @jbg Seems you misunderstand how this crate works, it just exposes consts/fns/structs etc. We've also tested the build for musl on CI and it's green. If you refer to the socket2 issue, its build is broken because it uses an _undeclared_ item on this crate, note that it's not this crate's fault.
> 
> But yeah, let's make a new release now then, @bors r+

Thanks very much for the release, and apologies for the misunderstanding, I mistakently thought a `libc` patch release had made those constants conditional on glibc targets and broken `socket2`, rather than a `socket2` patch release starting to depend on `libc` constants that were unexpectedly only exported on glibc targets.

Is there a way the docs could show when constants are target-specific? The 0.2.140 docs don't indicate in any way that `DCCP_*` is only exported for glibc targets in that version. Maybe rustdoc doesn't provide a convenient way to do that?

**Comment by JohnTitor** [comment]
Yeah, given how we (re)export items, IIRC it's difficult to show items on docs.rs per target.
But we have platform-specific docs on gh-pages: https://rust-lang.github.io/libc/#platform-specific-documentation
Does it work for you?

**Comment by jbg** [comment]
Yes, these are excellent.

I think despite the link from README they might be easily missed, though, given how docs.rs is in many people's muscle memory.

I wonder if it's possible somehow to get rustdoc to produce the little yellow tags (like the `Unix` and `Windows` ones on https://docs.rs/tokio/latest/tokio/signal/index.html) for target-specific re-exports. I think somehow adding a [#[doc(cfg)] attribute](https://doc.rust-lang.org/rustdoc/unstable-features.html#doccfg-recording-what-platforms-or-features-are-required-for-code-to-be-present) to the re-exports would do it, but that would require the docs to be built with nightly rustdoc (which docs.rs does use).

**Comment by JohnTitor** [comment]
`#[doc(cfg(...))]` _might_ be a good solution here, although it should be quite hard as this crate supports a lot of targets...

**Comment by jbg** [comment]
I'll have a play and if it's not too ugly I'll submit a PR for consideration :)

**Comment by Thomasdezeeuw** [comment]
Thanks @JohnTitor!

**Comment by JohnTitor** [comment]
Published on crates.io: https://crates.io/crates/libc/0.2.141

**Comment by arjentz** [comment]
Thanks a lot @JohnTitor

**Pull request merged**
