### PR TITLE
Upstream a few more constants from rustix.

### PR DESCRIPTION
**Pull request by sunfishcode**
Add a definition of `CIBAUD` for powerpc and powerpc64 on glibc.

And a definition for `RLIM64_INFINITY` on linux_like platforms.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
@bors r+
Thanks!

**Comment by JohnTitor** [comment]
Some jobs failed, could you check?
@rustbot author

**Comment by sunfishcode** [comment]
Fixed the declaration of `rlim64_t` on i686-linux-android, and squashed into a single commit.

**Comment by JohnTitor** [comment]
Thanks and sorry for the delay! @bors r+

**Comment by sunfishcode** [comment]
This PR doesn't touch any files used by FreeBSD, but CI is failing on FreeBSD like this:

```
RUNNING ALL TESTS
bad tcp_info size: rust: 240 (0xf0) != c 256 (0x100)
bad tcp_info align: rust: 4 (0x4) != c 8 (0x8)
bad field offset __tcpi_pad of tcp_info: rust: 164 (0xa4) != c 176 (0xb0)
bad field type __tcpi_pad of tcp_info: rust: 0x2b1529dd778c != c 0x2b1529dd7798
size of struct tcp_info is 256 in C and 240 in Rust
thread 'main' panicked at 'some tests failed', /tmp/cirrus-ci-build/target/x86_64-unknown-freebsd/debug/build/libc-test-6b8396ef363a1463/out/main.rs:12:21
```

**Comment by JohnTitor** [comment]
The issue is now fixed on master, @bors retry

**Comment by JohnTitor** [comment]
Seems there's a typo in cfg.

**Comment by sunfishcode** [comment]
Oops, fixed.

**Pull request merged**
