### PR TITLE
Add fn sync to android targets

### PR DESCRIPTION
**Pull request by DoumanAsh**
Note that it has different signature from posix's one

### CODE REVIEW

**Comment by DoumanAsh** [comment]
It turns out signature of this function is changing from `int sync(void)` into `void sync(void)` depending on android version so might be not feasible to add

**Comment by JohnTitor** [comment]
Looking at https://github.com/aosp-mirror/platform_bionic/commit/79a8f4b2c9b5096c90608018b0d3ba0cb6216ea8, it's a quite old commit (existing since android-8.0.0_r1) so we don't have to count the use of `int sync(void)` here, I guess (Android 7 or older is now "not supported version" IIRC)?

**Comment by DoumanAsh** [comment]
In my case we're using Android 7 and it is not like these versions would disappear all of the sudden.
But I understand if you want to support only latest versions

**Comment by JohnTitor** [comment]
Hm, then it'd be better to declare on the user codebase instead as I'm not sure there's a graceful way to detect the Android toolchain.

**Pull request closed without merging**
