### PR TITLE
Add some permission and misc (mostly 'mode_t' related) constants to Redox.

### PR DESCRIPTION
**Pull request by goyox86**
Hi!

While porting some software ((exa)[https://github.com/ogham/exa])to Redox I found these missing constants. 

Cheers!

//cc @ids1024 @jackpot51

### CODE REVIEW

**Comment by jackpot51** [comment]
@goyox86 The mode_t values should probably be hex

**Comment by goyox86** [comment]
Ah I left them as decimal as @ids1024 mentioned it would be good to leave them like Linux ones. I'm gonna change them then.

**Comment by goyox86** [comment]
Done @jackpot51

**Comment by jackpot51** [comment]
@goyox86 Thanks very much for that!

**Pull request merged**
