### PR TITLE
Add SIGRTMIN/SIGRTMAX on Linux

### LINKED ISSUE #1883: libc expose SIGRTMIN and SIGRTMAX
Exposing SIGRTMIN and SIGRTMAX might be problematic as they dynamically change and will therefore be hard to encode as constants. Perhaps exposing them in the form of functions is the best solution? I have very little experience porting from C to Rust so I am not sure what the best way of doing that would be. If someone gave me a point in the right direction then I would be willing to try to tackle this.

Target triplet: x86_64-linux-gnu

Man page for signals:
https://www.man7.org/linux/man-pages/man7/signal.7.html

Other crates looking for feature:
https://github.com/nix-rust/nix/issues/1143

### PR DESCRIPTION
**Pull request by clarfonthey**
Closes #1883

### CODE REVIEW

**Comment by Amanieu** [comment]
CI is failing, can you have a look at the errors?

**Comment by clarfonthey** [comment]
Will try to fix this weekend.

**Comment by JohnTitor** [comment]
@clarfonthey Still failing, do you have some time to resolve it? If so, I'm happy to hold off a release for now. Feel free to let us know if you need help!

**Comment by clarfonthey** [comment]
I was running into a few GCC errors locally that I'll have to fix. No need to hold off a release, but I'll try to get to this soon. :)

**Comment by clarfonthey** [comment]
Ah, yeah, I can't even get `libc-test` to work on master either. I get this:

```rust


warning: /proj/rust-libc/target/debug/build/libc-test-42f2f7ec12252b85/out/main.c: In function ‘__test_roundtrip_inotify_event’:
warning: /proj/rust-libc/target/debug/build/libc-test-42f2f7ec12252b85/out/main.c:22248:13: note: the ABI of passing struct with a flexible array member has changed in GCC 4.4
warning: 22248 |             ) {
warning:       |             ^
warning: /proj/rust-libc/target/debug/build/libc-test-42f2f7ec12252b85/out/main.c: In function ‘__test_field_type_sockaddr_vm_svm_zero’:
warning: /proj/rust-libc/target/debug/build/libc-test-42f2f7ec12252b85/out/main.c:22451:28: error: returning ‘unsigned char (*)[3]’ from a function with incompatible return type ‘uint8_t (*)[4]’ {aka ‘unsigned char (*)[4]’} [-Werror=incompatible-pointer-types]
warning: 22451 |                     return &b->svm_zero;
warning:       |                            ^~~~~~~~~~~~
warning: /proj/rust-libc/target/debug/build/libc-test-42f2f7ec12252b85/out/main.c: At top level:
warning: cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
warning: cc1: all warnings being treated as errors

error: failed to run custom build command for `libc-test v0.2.95 (/proj/rust-libc/libc-test)`
```

Is there something wrong with my setup or is this an actual bug?

**Comment by JohnTitor** [comment]
Looks like it's different from the current CI failure, could you push your change so that I can investigate?

**Comment by JohnTitor** [comment]
Or, if you get it without any change (i.e. on master), it should be caused by glibc version difference between CI and your env.

**Comment by clarfonthey** [comment]
I get the same error with or without my change, so, I'm assuming it is a glibc change. I'm running on Arch Linux and have the latest updates.

**Comment by JohnTitor** [comment]
Then it should be the case. You can push the changes and use CI for testing instead.

**Pull request closed without merging**
