### PR TITLE
Add futimens

### PR DESCRIPTION
**Pull request by pitdicker**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like this may not be present on OSX?

**Comment by pitdicker** [comment]
This automation is _really_ great :)

**Comment by alexcrichton** [comment]
Ah looks like Android also doesn't have this function unfortunately :(

**Comment by alexcrichton** [comment]
Ah I'm rolling up some other PRs, I'll take care of it.

**Comment by pitdicker** [comment]
Just to make sure, android does not seem to have  `utimes`, but it does have `utimens`

**Pull request merged**
