### PR TITLE
Remove tier 3 targets from CI

### PR DESCRIPTION
**Pull request by joshtriplett**
These targets seem to regularly break unrelated PRs, and in general we
shouldn't gate PRs on tier 3 targets (per the target tier policy).

### CODE REVIEW

**Comment by workingjubilee** [comment]
@joshtriplett This doesn't seem to remove *all* tier 3 targets, can we identify this PR as singling out the Switch and μClibc targets?

**Comment by joshtriplett** [comment]
> @joshtriplett This doesn't seem to remove _all_ tier 3 targets, can we identify this PR as singling out the Switch and μClibc targets?

I had intended for it to, but clearly I've missed some that weren't labeled as such.

**Comment by workingjubilee** [comment]
Maybe I'm mistaken?

**Comment by tgross35** [comment]
This was merged via https://github.com/rust-lang/libc/pull/3797.

**Pull request closed without merging**
