### PR TITLE
openbsd/netbsd commonize getnameinfo

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by tgross35 — APPROVED** [review]

**Comment by semarie** [comment]
FYI it not ok on OpenBSD.

it fails to pass the test suite:

```
  cargo:warning=/data/semarie/repos/rust/build-libc/build/x86_64-unknown-openbsd/debug/build/libc-test-2bed02be9f63dff8/out/main.c:15285:24: error: incompatible function pointer types returning 'int (const struct sockaddr *, socklen_t, char *, size_t, char *, size_t, int)' (aka 'int (const struct sockaddr *, unsigned int, char *, unsigned long, char *, unsigned long, int)') from a function with result type 'int (*)(const struct sockaddr *, socklen_t, char *, socklen_t, char *, socklen_t, int)' (aka 'int (*)(const struct sockaddr *, unsigned int, char *, unsigned int, char *, unsigned int, int)') [-Werror,-Wincompatible-function-pointer-types]
  cargo:warning=                return getnameinfo;
  cargo:warning=                       ^~~~~~~~~~~
  cargo:warning=1 error generated.

  --- stderr
  rust version: 1.80.0


  error occurred: Command "/usr/local/bin/sccache" "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-unknown-openbsd" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-Wno-address-of-packed-member" "-Wno-unknown-warning-option" "-Wno-deprecated-declarations" "-Wno-deprecated-declarations" "-o" "/data/semarie/repos/rust/build-libc/build/x86_64-unknown-openbsd/debug/build/libc-test-2bed02be9f63dff8/out/63e0546644a06edb-main.o" "-c" "/data/semarie/repos/rust/build-libc/build/x86_64-unknown-openbsd/debug/build/libc-test-2bed02be9f63dff8/out/main.c" with args cc did not execute successfully (status code exit status: 1).
```

**Comment by tgross35** [comment]
Interesting - per https://man.freebsd.org/cgi/man.cgi?query=getnameinfo&sektion=3&format=html (tested in CI) and https://man.openbsd.org/getnameinfo.3 they have an identical function signature. Is this signature version-dependent?

**Comment by semarie** [comment]
the problem is `servlen: ::socklen_t` (on NetBSD) vs `servlen: ::size_t` (on OpenBSD and FreeBSD)

**Comment by devnexen** [comment]
ah ok let s just revert it.

**Comment by tgross35** [comment]
Reverts here https://github.com/rust-lang/libc/pull/3834 and here https://github.com/rust-lang/libc/pull/3835.

Feel free to reopen this if there is a better way to commonize things, we can make sure @semarie signs off.

**Pull request merged**
