### PR TITLE
Fix redox

### PR DESCRIPTION
**Pull request by mati865**
Revival of https://github.com/rust-lang/libc/pull/1422

All the missing impls were added in https://github.com/rust-lang/libc/pull/1438

Should unblock https://github.com/rust-lang/rust/pull/61393

### CODE REVIEW

**Comment by mati865** [comment]
Successful build: https://travis-ci.com/mati865/libc/builds/121390368

**Comment by newpavlov** [comment]
You will need to add [`Clone` impls](https://github.com/rust-lang/libc/pull/1422/files and define `timezone`) and probably remove derive of traits (or implement them manually) which cause failures [here](https://travis-ci.com/rust-lang/libc/jobs/213715301).

**Comment by gnzlbg** [comment]
The derive of traits (except for Copy and Clone) aren't really necessary for anything, so you can just leave them all out.

**Comment by mati865** [comment]
It was fixed in https://github.com/rust-lang/libc/pull/1438

The build fails because of https://github.com/rust-lang/rust/issues/63115 which will be fixed by https://github.com/rust-lang/rust/pull/63122

**Comment by newpavlov** [comment]
@gnzlbg
Can you re-run CI to see if the issue got fixed?

**Comment by mati865** [comment]
CI is being migrated to Azure and will not succeed without https://github.com/rust-lang/libc/pull/1376

**Comment by jackpot51** [comment]
This is no longer required

**Comment by mati865** [comment]
It won't be necessary for new nightly builds but libc is still empty when building for Redox from old nightly, beta or stable although I don't even know if they work after all those changes.

**Comment by jackpot51** [comment]
I don't really see a use case for building for Redox prior to the 2019-08-08 nightly

**Comment by jackpot51** [comment]
Anything doing that will need to be updated anyways

**Pull request closed without merging**
