### PR TITLE
Bump version to 0.2.97

### PR DESCRIPTION
**Pull request by jonas-schievink**
I'd like to get a new release published, since I want to make use of https://github.com/rust-lang/libc/pull/2228 in https://github.com/rust-analyzer/rust-analyzer/pull/9204

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you also update the libc dependency version on libc-test?

**Comment by jonas-schievink** [comment]
Sure, done

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by JohnTitor** [comment]
Published on crates.io: https://crates.io/crates/libc/0.2.97

**Comment by jonas-schievink** [comment]
Great, thanks!

**Pull request merged**
