### PR TITLE
Move musl-compatible constants to linux/mod.rs

### PR DESCRIPTION
**Pull request by jbaublitz**
This is a continuation of #1452. I think CI is ready to run fully and the PR is ready to be merged if the pipelines pass based on the CI I've done using musl libc in my own projects.

### CODE REVIEW

**Comment by jbaublitz** [comment]
I'm a little confused. I rebased onto master but the CI jobs in azure are either not visible in Github or the don't seem to have run even though I didn't disable anything. Is this expected?

**Comment by gnzlbg** [comment]
> I'm a little confused. I rebased onto master but the CI jobs in azure are either not visible in Github or the don't seem to have run even though I didn't disable anything. Is this expected?

It isn't, they aren't currently running for PRs, for some reason. I need to investigate that.

**Comment by gnzlbg** [comment]
@pietroalbini why can that be ? 

```yml
trigger: ["auto-libc","try"]
pr: ["master"]
```

Shouldn't that trigger azure jobs in PR builds ?

**Pull request merged**
