### PR TITLE
VxWorks: add functions for message queue

### PR DESCRIPTION
**Pull request by BaoshanPang**

### CODE REVIEW

**Comment by BaoshanPang** [comment]
The error is not related to my code:
https://dev.azure.com/rust-lang2/libc/_build/results?buildId=1077&view=logs&j=a0d58cc1-afb1-556c-24c8-109083aad81d&t=3a3b8099-ea38-5855-a2d4-9817ff96dcb5&l=20

**Comment by BaoshanPang** [comment]
@gnzlbg 
Thanks for the review. When the code can be merged in the master branch?

**Comment by JohnTitor** [comment]
@BaoshanPang Hey, could you rebase to make CI green?
r? @JohnTitor

**Comment by JohnTitor** [comment]
Thanks!

**Comment by BaoshanPang** [comment]
@JohnTitor Thank you!

**Pull request merged**
