### PR TITLE
Add AT_FDCWD for FreeBSD

### PR DESCRIPTION
**Pull request by PlasmaPower**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by PlasmaPower** [comment]
Oops, looks like AT_FDWCD was already defined in submodules for netbsd (though they were the same). I'm moving those definitions to the main thing. If I ammend the commit it won't break bors right?

**Comment by PlasmaPower** [comment]
Actually since some netbsd variants have more AT_* definitions, I think I'll just leave netbsd the way it was.

**Comment by PlasmaPower** [comment]
Okay should be good to go now, unless we do want to change the AT_FDCWD definition for netbsd.

**Pull request merged**
