### PR TITLE
Make some freebsd private struct fields public and upgrade crate version to 0.2.112

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Otherwise we can't use the structs at all...

### CODE REVIEW

**Comment by Amanieu** [comment]
Can't you use the struct with `mem::zeroed`, like C code does with `memset`? Or do you actually need to look at the value of the private field?

**Comment by GuillaumeGomez** [comment]
It is a linked list, I need the `next` field to be able to get the next element. The problem here isn't the initialization (I already used `zeroed` :wink: ).

**Comment by GuillaumeGomez** [comment]
Can you publish the new version please? :)

**Pull request merged**
