### PR TITLE
freebsd moving the kinfo_file type to general use.

### PR DESCRIPTION
**Pull request by devnexen**
but keeping the constant KINFO_FILE_SIZE for intel archs only.

### CODE REVIEW

**Comment by tgross35** [comment]
New workflow, we will merge https://github.com/rust-lang/libc/pull/3800 first then cherry pick it. Nominated https://github.com/rust-lang/libc/pull/3800 for stable.

**Comment by tgross35** [comment]
Reposting from https://github.com/rust-lang/libc/pull/3800#issuecomment-2284975673, I closed the wrong PR:

Thanks, do you have a link to docs/headers for `KINFO_FILE_SIZE` to confirm?

This should have an update in `libc-test/semver`.

@rustbot label +stable-nominated

**Comment by devnexen** [comment]
sure here the [header](https://github.com/freebsd/freebsd-src/blob/97c31cc80098956688a36a173a42b54549350d40/sys/sys/user.h#L330).

**Comment by tgross35** [comment]
Great, thanks for the reference. Could you add `kinfo_file` to `libc-test/semver/freebsd.txt`?

**Review by tgross35 — APPROVED** [review]
Thanks!

**Pull request merged**
