### PR TITLE
fill out common unix syscalls

### PR DESCRIPTION
**Pull request by Uplifting**
i'm expecting a few build failures, particularly from brk/sbrk.

### CODE REVIEW

**Comment by Uplifting** [comment]
`settimeofday` takes a `const void*` instead of a `struct timezone` on netbsd...is there a way to change the type signature for just that arch?

In order to get the tests to pass it also looks like it is necessary to define `clock_t` in mips64.

**Comment by alexcrichton** [comment]
Ah yeah currently you can handle that by just duplicating the signature, it's ok to do so.

**Comment by Uplifting** [comment]
At this point I think I'll just move some functions to the notbsd folder.

**Comment by alexcrichton** [comment]
@bors: r+

Looks great now!

**Pull request merged**
