### PR TITLE
Fix mips64-musl ioctl consts to c_int

### PR DESCRIPTION
**Pull request by workingjubilee**
This arch was overlooked or unspecified in earlier PRs that fixed
c_ulong to c_int for ioctl.h consts for musl, see PR #289, PR #301,
or PR #1097 for such prior art, however these are still args to
fn ioctl on mips64-musl, which is expecting c_ints.

Some numbers acquired casts to reflect the fact the data is being
used and (so should be written as) an unsized bitfield, even if
the value is greater than i32::MAX.

Currently rustc is not building on mips64-linux-musl because of this error.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Build failure on sparc64-linux-gnu and aarch64-linux android, appears spurious but both died around the same point


<details><summary>aarch64-linux-android</summary>
<p>

>    Compiling libc v0.2.86 (/checkout)
   Compiling libc-test v0.1.0 (/checkout/libc-test)
    Finished test [unoptimized + debuginfo] target(s) in 1m 15s
     Running target/aarch64-linux-android/debug/deps/cmsg-85998318d0dbb347
/checkout/target/aarch64-linux-android/debug/deps/cmsg-85998318d0dbb347: 1 file pushed, 0 skipped. 6.6 MB/s (6280304 bytes in 0.904s)
status: exit code: 0
stdout ---
> 
> running 5 tests
test t::test_cmsg_data ... ok
test t::test_cmsg_firsthdr ... ok
test t::test_cmsg_len ... ok
test t::test_cmsg_nxthdr ... ok
test t::test_cmsg_space ... ok
> 
>test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 128.65s
> 
> 
>stderr ---
>     Running target/aarch64-linux-android/debug/deps/errqueue-f5addfcdc0abe27f
/checkout/target/aarch64-linux-android/debug/deps/errqueue-f5addfcdc0abe27f: 1 file pushed, 0 skipped. 7.4 MB/s (6216840 bytes in 0.806s)
status: exit code: 101
> stdout ---
>
> stderr ---
thread 'main' panicked at 'No option 'h' defined', /cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.21/src/lib.rs:799:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> thread 'main' panicked at 'failed to find successful test run', /tmp/runtest.rs:45:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: test failed, to rerun pass '--test errqueue'
Error: Process completed with exit code 101.

</p>
</details>

<details><summary>sparc-unknown-linux-gnu</summary>
<p>

>       Running target/sparc64-unknown-linux-gnu/debug/deps/main-236950364f4610fb
>qemu-system-sparc64: terminating on signal 15 from pid 2245 (timeout)
OpenBIOS for Sparc64
Configuration device id QEMU version 1 machine id 0
kernel addr 404000 size b267e0
kernel cmdline init=/run_prog.sh
CPUs: 1 x SUNW,UltraSPARC-IIi
UUID: 00000000-0000-0000-0000-000000000000
Welcome to OpenBIOS v1.1 built on Mar 12 2020 14:03
  Type 'help' for detailed information
>
>RUNNING ALL TESTS
>PASSED 19344 tests
>+ cargo test --features extra_traits --manifest-path libc-test/Cargo.toml --target sparc64-unknown-linux-gnu
   Compiling libc v0.2.86 (/checkout)
   Compiling libc-test v0.1.0 (/checkout/libc-test)
>warning: function is never used: `cmsg_nxthdr`
>  --> libc-test/test/cmsg.rs:14:9
   |
14 | /         pub fn cmsg_nxthdr(
15 | |             mhdr: *const msghdr,
16 | |             cmsg: *const cmsghdr,
17 | |         ) -> *mut cmsghdr;
   | |__________________________^
   |
   = note: `#[warn(dead_code)]` on by default
>
> warning: 1 warning emitted
>
>    Finished test [unoptimized + debuginfo] target(s) in 1m 20s
>    Running target/sparc64-unknown-linux-gnu/debug/deps/cmsg-2643cde4a5a9cd20
>qemu-system-sparc64: terminating on signal 15 from pid 2919 (timeout)
>OpenBIOS for Sparc64
>Configuration device id QEMU version 1 machine id 0
>kernel addr 404000 size b267e0
>kernel cmdline init=/run_prog.sh
>CPUs: 1 x SUNW,UltraSPARC-IIi
>UUID: 00000000-0000-0000-0000-000000000000
>Welcome to OpenBIOS v1.1 built on Mar 12 2020 14:03
>  Type 'help' for detailed information
>
> running 4 tests
test t::test_cmsg_data ... ok
test t::test_cmsg_firsthdr ... ok
test t::test_cmsg_len ... ok
test t::test_cmsg_space ... ok
>
> test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s
>
>     Running target/sparc64-unknown-linux-gnu/debug/deps/errqueue-aec01ef3f9138751

</p>
</details>

this PR should only affect mips64 targets though, and neither of those libcs.

**Comment by workingjubilee** [comment]
...similar issues, including failures on `x86_64-unknown-linux-gnux32`.
apparently this is a recurring problem: https://github.com/rust-lang/libc/pull/1851#issuecomment-669488614

Do I have the power?
Do I have a moderate amount of power?
Do I have... moderating power?

@bors retry

**Comment by workingjubilee** [comment]
darn :^) I'll stop fussing I guess.

**Comment by Amanieu** [comment]
I *think* this is the right syntax. You now have the power!

@bors delegate=workingjubilee

**Comment by workingjubilee** [comment]
Thank you! I guess I'm gonna keep smacking it every now and then until the suite passes or it develops a new, more interesting error than "aarch64 and sparc64 have spurious failures now and then". :^)

@bors r+

**Comment by Amanieu** [comment]
The error on aarch64 doesn't seem to be spurious. Can you try setting RUST_BACKTRACE=1 in CI so we can get a backtrace for the error?

**Comment by Amanieu** [comment]
cc @JohnTitor Any idea what might be causing the CI failure here?

**Comment by workingjubilee** [comment]
It read like other errors that were dismissed as spurious but!
aye aye capitán.

**Comment by workingjubilee** [comment]
agh whoops.
@bors -try

**Comment by JohnTitor** [comment]
> 
> 
> cc @JohnTitor Any idea what might be causing the CI failure here?

We've encountered `No option 'h' defined` several times, right? So, previously I re-tried the build and CI became green after some trying. I guess the cause is something related to CI or QEMU but I'm totally not sure :/

**Comment by workingjubilee** [comment]
so of course on THAT build, all the problematic testers choose to pass, but then we get this:

<details><summary>break in doc generation for aarch64-fuschia</summary>
<p>

>Run LIBC_CI=1 sh ci/dox.sh
>  LIBC_CI=1 sh ci/dox.sh
>  shell: /usr/bin/bash -e {0}
>+ TARGET_DOC_DIR=target/doc
>+ README=README.md
>+ PLATFORM_SUPPORT=platform-support.md
>+ rm -rf target/doc
>+ mkdir -p target/doc
>+ rustc --version
>+ grep -E nightly
>rustc 1.52.0-nightly (fe1bf8e05 2021-02-23)
>+ rustup component add rust-src
>info: downloading component 'rust-src'
>info: installing component 'rust-src'
>info: using up to 500.0 MiB of RAM to unpack components
>+ grep [\d|\w|-]* \\ ci/build.sh
>+ sed -i.bak s/ \\//g targets
>+ grep ^[_a-zA-Z0-9-]*$ targets
>+ sort
>+ mv tmp targets
>+ rm platform-support.md
>rm: cannot remove 'platform-support.md': No such file or directory
>+ true
>+ printf ### Platform-specific documentation\n
>+ read -r target
>documenting aarch64-apple-darwin
>documenting aarch64-apple-ios
>documenting aarch64-fuchsia
>+ echo documenting aarch64-apple-darwin
>+ continue
>+ read -r target
>+ echo documenting aarch64-apple-ios
>+ continue
>+ read -r target
>+ echo documenting aarch64-fuchsia
>+ rustup target add aarch64-fuchsia
>info: downloading component 'rust-std' for 'aarch64-fuchsia'
>info: installing component 'rust-std' for 'aarch64-fuchsia'
>info: using up to 500.0 MiB of RAM to unpack components
>+ export RUSTDOCFLAGS=--cfg freebsd11
>+ cargo doc --target aarch64-fuchsia --no-default-features --features extra_traits
>   Compiling libc v0.2.86 (/home/runner/work/libc/libc)
> Documenting libc v0.2.86 (/home/runner/work/libc/libc)
>    Finished dev [unoptimized + debuginfo] target(s) in 4.25s
>+ cp -r target/aarch64-fuchsia/doc target/doc/aarch64-fuchsia
>cp: cannot create directory 'target/doc/aarch64-fuchsia': No such file or directory
>Error: Process completed with exit code 1.

</p>
</details>


<details><summary>aarch64-unknown-linux-gnu semver test</summary>
<p>

> + cargo semver --api-guidelines --target=aarch64-unknown-linux-gnu
>    Updating crates.io index
>   Compiling libc v0.2.86 (/home/runner/work/libc/libc)
>    Finished dev [unoptimized + debuginfo] target(s) in 1.82s
>   Compiling libc v0.2.86
>    Finished dev [unoptimized + debuginfo] target(s) in 2.87s
>version bump: 0.2.86 -> (breaking) -> 0.2.87
>error: breaking changes in `statx`
>   --> /home/runner/work/libc/libc/src/unix/linux_like/linux/gnu/mod.rs:7:1
>    |
>7   | / s! {
>8   | |     pub struct statx {
>9   | |         pub stx_mask: u32,
>10  | |         pub stx_blksize: u32,
>...   |
>302 | |     }
>303 | | }
>    | |_^
>    |
>warning: item made private (breaking)
>   --> /home/runner/work/libc/libc/src/unix/linux_like/linux/gnu/mod.rs:16:9
>    |
>16  |         __statx_pad1: [u16; 1],
>    |         ^^^^^^^^^^^^^^^^^^^^^^
>warning: item made private (breaking)
>   --> /home/runner/work/libc/libc/src/unix/linux_like/linux/gnu/mod.rs:30:9
>    |
>30  |         __statx_pad2: u64,
>    |         ^^^^^^^^^^^^^^^^^
>warning: public field added to struct with no private fields (breaking)
>   --> /home/runner/work/libc/libc/src/unix/linux_like/linux/gnu/mod.rs:29:9
>    |
>29  |         pub stx_mnt_id: u64,
>    |         ^^^^^^^^^^^^^^^^^^^
>warning: private field added to struct with no private fields (breaking)
>   --> /home/runner/work/libc/libc/src/unix/linux_like/linux/gnu/mod.rs:31:9
>    |
>31  |         __statx_pad3: [u64; 12],
>    |         ^^^^^^^^^^^^^^^^^^^^^^^
>    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
>
>error: aborting due to previous error
>
>error: rustc-semverver errored

</p>
</details>

**Comment by JohnTitor** [comment]
The semverver check is unrelated to this PR and can be ignored. For the docs failure, I'm not sure why it happened, let's give it one more try.
@bors try

**Comment by workingjubilee** [comment]
That doesn't make sense at all.

**Comment by workingjubilee** [comment]
Well no, I mean, copying failing that makes sense. It exits with a non-zero status code.

**Comment by JohnTitor** [comment]
Cirrus CI sometimes re-schedules the jobs due to their CI capacity and it causes bors failure :(
@bors try again...

**Comment by workingjubilee** [comment]
loving it!

<details><summary>aarch64-linux-android backtrace</summary>
<p>

```backtrace
     Running target/aarch64-linux-android/debug/deps/errqueue-f5addfcdc0abe27f
/checkout/target/aarch64-linux-android/debug/deps/errqueue-f5addfcdc0abe27f: 1 file pushed, 0 skipped. 7.7 MB/s (6211296 bytes in 0.774s)
status: exit code: 101
stdout ---

stderr ---
thread 'main' panicked at 'No option 'h' defined', /cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.21/src/lib.rs:799:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at 'failed to find successful test run', /tmp/runtest.rs:45:9
stack backtrace:
   0: std::panicking::begin_panic
   1: runtest::main::{{closure}}
   2: core::option::Option<T>::unwrap_or_else
   3: runtest::main
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: test failed, to rerun pass '--test errqueue'
```

</p>

**Comment by Amanieu** [comment]
Try adding it here:
```diff
diff --git a/ci/runtest-android.rs b/ci/runtest-android.rs
index b8030c41a7..e14dba322c 100644
--- a/ci/runtest-android.rs
+++ b/ci/runtest-android.rs
@@ -27,6 +27,7 @@ fn main() {
 
     let output = Command::new("adb")
         .arg("shell")
+        .arg("RUST_BACKTRACE=1")
         .arg(&dst)
         .output()
         .expect("failed to run: adb shell");
```

**Comment by workingjubilee** [comment]
>error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-updateYTlfqG/release-stable.toml'
>error: caused by: failed to make network request
>error: caused by: error sending request for url (https://static.rust-lang.org/rustup/release-stable.toml): >connection error: Connection reset by peer (os error 104)
>error: caused by: connection error: Connection reset by peer (os error 104)
>error: caused by: Connection reset by peer (os error 104)
>Error: Process completed with exit code 1.

Sigh.
@bors retry

**Comment by workingjubilee** [comment]
Well, the error is elusive and non-reoccurring, so we're only consistently blocking on the semverver and failure to generate docs for fuschia.

**Comment by Amanieu** [comment]
Eh at this point I'd say just revert the backtrace stuff and brute-force r+ until it works.

**Comment by workingjubilee** [comment]
Does the backtrace actually add that much weight to CI? This error may reoccur and it may be simply better to have it there for the next time it does.

Will r+ not block on the semverver failure?

**Comment by Amanieu** [comment]
Semverver doesn't block success. Not exactly sure why but that's how it is set up.

Let's keep the backtraces as you suggested.

@bors r+

**Comment by workingjubilee** [comment]
That's... not really more useful, hm.

```backtrace
thread 'main' panicked at 'failed to find successful test run', /tmp/runtest.rs:46:9
stack backtrace:
   0: std::panicking::begin_panic
   1: runtest::main::{{closure}}
   2: core::option::Option<T>::unwrap_or_else
   3: runtest::main
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: test failed, to rerun pass '--test errqueue'
```

**Comment by Amanieu** [comment]
Just comment out the aarch64-android CI for now, this is too much trouble.

**Comment by workingjubilee** [comment]
Noted, it's a tier 3 target anyways.

**Comment by Amanieu** [comment]
(retry doesn't pick up new commits)

**Comment by workingjubilee** [comment]
Ahh, thank you!

**Comment by workingjubilee** [comment]
Looks like it does block on doc generation. It's not obvious to me what changed in the last week to make that fail now, but it appears to be pretty stateful and error-prone. I made some changes to the shell script to fix this. It should error less often in the future.

**Pull request merged**
