### PR TITLE
Some update for vxWorks

### PR DESCRIPTION
**Pull request by BaoshanPang**
1. fix issues found in testing
2. code cleanup
3. remove copyright notice

### CODE REVIEW

**Comment by BaoshanPang** [comment]
cc @n-salim 
cc @UmeshKalappa

**Comment by gnzlbg** [comment]
Could you please rebase?

**Comment by BaoshanPang** [comment]
> Could you please rebase?

Sure. I am going to do it.

**Comment by BaoshanPang** [comment]
I will create a new PR to replace this one which is easier for me.

**Pull request closed without merging**
