### PR TITLE
backport: add stabilized HermitOS interface

### PR DESCRIPTION
**Pull request by stlankes**
HermitOS is a unikernel and its interface to the kernel is provided by https://crates.io/crates/hermit-abi. In the meantime parts of the interface is stabilized and we want to integrated it into libc. Unstable version will be still provided by hermit-abi.

This PR is a backport of #3724 and doesn't have breaking changes. It just provides new functions to enter the kernel.

### CODE REVIEW

**Comment by stlankes** [comment]
I forgot the error numbers and added to this PR.

**Comment by JohnTitor** [comment]
Do you think this breaks the existing usage? If so, I'd like to provide this only on 1.0 as it's a breaking change.

**Comment by stlankes** [comment]
No!

**Comment by Thomasdezeeuw** [comment]
Any update on this? We want to use it Mio as well.

**Comment by tgross35** [comment]
@stlankes I picked up the first commit as part of my backport bonanza, in https://github.com/rust-lang/libc/pull/3814. The second commit (5c7c7824, "add missing error numbers for HermitOS") seems like it is something that should go to `main` too. Could you create a new PR targeting `main` that makes that change? Comment `@rustbot label +stable-nominated` so it gets picked up in the next backport.

**Comment by tgross35** [comment]
This can probably just be closed once you create the new one, but

@rustbot author

**Comment by tgross35** [comment]
The backport of the first commit merged. I am going to go ahead and close this - but please feel free to put up a new PR with 5c7c7824253e6f3f4735cf253fe2c7e60ab94cd0, as mentioned above.

**Comment by Thomasdezeeuw** [comment]
Thanks @tgross35

**Comment by stlankes** [comment]
> @stlankes I picked up the first commit as part of my backport bonanza, in #3814. The second commit ([5c7c782](https://github.com/rust-lang/libc/commit/5c7c7824253e6f3f4735cf253fe2c7e60ab94cd0), "add missing error numbers for HermitOS") seems like it is something that should go to `main` too. Could you create a new PR targeting `main` that makes that change? Comment `@rustbot label +stable-nominated` so it gets picked up in the next backport.

I will do it next week. After my vacations...

**Pull request closed without merging**
