### PR TITLE
Make fd_set.fds_bits public

### LINKED ISSUE #730: fd_set.fds_bits is not public
Was there a reason for this? I know that there are `FD_CLR` and friends, but it seems odd that this one field is private while almost all struct fields for all `libc` types are public.

### PR DESCRIPTION
**Pull request by Susurrus**
Closes #730.

### CODE REVIEW

**Comment by alexcrichton** [comment]
CI is failing?

**Comment by Susurrus** [comment]
Interesting. I'm not really certain what that error is. Looks like a bug in `ctest`? I'll try to dig into it some more as I can reproduce it locally at least.

**Comment by Susurrus** [comment]
This looks to be a parsing error within `libc-test`. Looks like it doesn't like expressions in the length part of an array declaration, but this only applies to `pub` fields. Maybe I'll just close this since the `FD_*` macros should take care of this anyways.

**Comment by alexcrichton** [comment]
Up to you!

**Pull request closed without merging**
