### PR TITLE
Remove unreachable fuchsia branches

### PR DESCRIPTION
**Pull request by gnzlbg**
cc @cramertj

So this should be a non-functional change because these branches are unreachable, but please try to build fuchsia with this change to make sure this doesn't break anything.

### CODE REVIEW

**Comment by cramertj** [comment]
LGTM-- the `unix/` code will never be included on fuchsia now because of [this if](https://github.com/rust-lang/libc/blob/master/src/lib.rs#L187).

**Comment by gnzlbg** [comment]
@cramertj is there a Rust project building fuchsia on CI ? it would be cool if we could had some way to test that fuchsia doesn't break.

**Comment by cramertj** [comment]
No, there isn't any currently Rust project running tests on an up-to-date Fuchsia in CI. This is something we'd like to have and there have been efforts towards getting this, but there have been some obstacles.

**Pull request merged**
