### PR TITLE
Marking nl_pad as public so we can construct sockaddr_nl

### PR DESCRIPTION
**Pull request by WillYee**
Addressing issue 1135

https://github.com/rust-lang/libc/issues/1135

### CODE REVIEW

**Comment by gnzlbg** [comment]
I suppose that `nl_pad` are padding bits required for the ABIs to match. I wonder if one shouldn't be using here`repr(align)`, `repr(packed)`, etc. instead. @alexcrichton ?

**Comment by alexcrichton** [comment]
`repr(align)` is fine to use yeah, `repr(packed)` I believe is still feature gated

**Comment by gnzlbg** [comment]
Any progress here? @WillYee please use `repr(align)`/`repr(packed)`/etc. to remove the padding field instead of making it public.

**Comment by gnzlbg** [comment]
I'm closing this, since it is intended for this to be an internal implementation detail. See #1135 for how to initialize these structs.

**Pull request closed without merging**
