### PR TITLE
Remove PSP-related code

### PR DESCRIPTION
**Pull request by JohnTitor**
Removes the support to avoid some concerns.

For users: If you depend on the source here, please create a separate crate and use it instead. Sorry for the inconvenience.

### CODE REVIEW

**Comment by overdrivenpotato** [comment]
@JohnTitor Out of curiosity, what were the concerns with keeping these function stubs in libc? Is there anything we can do as the `rust-psp` project, to help keep these definitions in?

**Comment by tgross35** [comment]
> @JohnTitor Out of curiosity, what were the concerns with keeping these function stubs in libc? Is there anything we can do as the `rust-psp` project, to help keep these definitions in?

I am pretty late to the picture here but are there any possible licensing issues? It seems like that has come up a bit recently.

**Comment by JohnTitor** [comment]
@tgross35 Yeah, correct.

@overdrivenpotato If you want to know what the issue is, you can contact the Foundation members who manage the licensing issues.

**Pull request merged**
