### PR TITLE
unbreak openbsd after #2109

### PR DESCRIPTION
**Pull request by semarie**
several symbols added to semver regression tests in "unix" aren't defined on OpenBSD.
move these symbols in OS specific files.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Thanks and sorry for the breakage, the new semver test is experimental and needs some love.

**Comment by semarie** [comment]
homu failed due to network problem:
- [Docker Switch](https://github.com/rust-lang/libc/runs/2264486800) : `Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
- [Docker Linux Tier2 (mipsel-unknown-linux-musl)](https://github.com/rust-lang/libc/runs/2264486506) : `Head https://registry-1.docker.io/v2/library/ubuntu/manifests/20.04: Get https://auth.docker.io/token?account=githubactions&scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: EOF`

**Comment by JohnTitor** [comment]
```
 Step 1/7 : FROM ubuntu:20.04
Head registry-1.docker.io/v2/library/ubuntu/manifests/20.04: Get auth.docker.io/token?account=githubactions&scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: EOF
```

I remember this failure happened on rust-lang/rust yesterday, docker.io is fragile recently... @bors retry

**Pull request merged**
