### PR TITLE
Add x86_64-linux-android support

### PR DESCRIPTION
**Pull request by malbarbo**
When rust add support for x86_64-linux-android, the tests may be run with:
`rustup target add x86_64-linux-android && bash ci/run-docker.sh x86_64-linux-android`.

Android x86_64 emulator does not work without hardware acceleration, so we are not able to run tests on travis.

### CODE REVIEW

**Comment by malbarbo** [comment]
The tests passes running a local rustc with x86_64-linux-android support. After this PR got merged, I will send a PR to https://github.com/rust-lang/rust.

**Comment by alexcrichton** [comment]
Awesome, thanks! Looks great to me.

I think there may be a tidy error though?

**Comment by malbarbo** [comment]
Ah, I forgot to run tidy... Fixed now.

**Pull request merged**
