### PR TITLE
android: add android_set_abort_message

### PR DESCRIPTION
**Pull request by tweksteen**
As definied in set_abort_message.h [1].

[1] https://android.googlesource.com/platform/bionic/+/master/libc/include/android/set_abort_message.h

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks good, thanks!

**Comment by JohnTitor** [comment]
```
 E: Could not configure 'libc6:i386'. 
E: Could not perform immediate configuration on 'libgcc-s1:i386'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
The command '/bin/sh -c apt-get install -y --no-install-recommends   gcc-multilib make libc6-dev git curl ca-certificates libc6:i386' returned a non-zero code: 100
```

Hmm, I'm not sure this is spurious or not (something on CI is broken), let's see if next testing fails or not.

**Comment by JohnTitor** [comment]
Hm failed on `i686-linux-android` but I think it should be available, isn't it @tweksteen?

**Comment by tweksteen** [comment]
Thanks. The test was missing the correct header file. I updated the change and tested locally with `./ci/run-docker.sh x86_64-linux-android`.

**Pull request merged**
