### PR TITLE
Redox updates

### PR DESCRIPTION
**Pull request by jackpot51**
Adds some missing constants and functions for Redox

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you add them to https://github.com/rust-lang/libc/blob/master/libc-test/semver/redox.txt and squash commits?

**Comment by jackpot51** [comment]
Yes, I will do that

**Comment by jackpot51** [comment]
Done

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Pull request merged**
