### PR TITLE
Bump crate version to 0.2.92

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Could it be possible to have a new release in the coming days please? Thanks in advance!

### CODE REVIEW

**Comment by JohnTitor** [comment]
Could you also update the libc-test's version and its libc dep version?

**Comment by GuillaumeGomez** [comment]
Sure!

**Comment by GuillaumeGomez** [comment]
Done!

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!

**Comment by JohnTitor** [comment]
Published on crates.io: https://crates.io/crates/libc/0.2.92

**Comment by GuillaumeGomez** [comment]
Thanks a lot!

**Pull request merged**
