### PR TITLE
Link to Windows debug CRTs when crt-debug target_feature is present.

### PR DESCRIPTION
**Pull request by jdm**
Relies on https://github.com/rust-lang/rust/pull/62534 in order to fix https://github.com/rust-lang/rust/issues/39016.

### CODE REVIEW

**Comment by jdm** [comment]
This makes it possible to link a Rust binding crate against a C library that was compiled with /MTd or /MDd.

**Comment by gnzlbg** [comment]
What happens if the standard library is built to link to one, but this crate from crates.io is set to link to the other ?

What happens if a `#[no_std]` binary only uses this crate without using the standard library.

Also, this needs tests that show that this works.

**Comment by jdm** [comment]
@gnzlbg What happens in those cases when crt-static is used?

**Comment by jdm** [comment]
It's true; this change may not be enough because of the issue of building the standard library. I tried building https://github.com/servo/mozjs with a Cargo.toml patch for libc that replaced msvcrt with msvcrtd, and I still got the same error that I'm used to seeing:
```
 = note: lld-link: error: /failifmismatch: mismatch detected: 0 and 2 for key _ITERATOR_DEBUG_LEVEL
```

**Comment by gnzlbg** [comment]
@jdm note that libc is built as part of `libstd`, and linked there, applying certain link flags, and that when using it from crates.io, how things actually should get linked will depend, on whether the binary is `#[no_std]` or not. If the binary links libstd, trying to override link flags here will probably cause incompatibilities. I'd recommend you to open an issue in rust-lang/rust to discuss whether this is the right way to enable this feature - or does such an issue already exist ?

**Comment by jdm** [comment]
I mentioned it in the original PR description: https://github.com/rust-lang/rust/issues/39016

**Comment by ollie27** [comment]
@gnzlbg when using this crate from crates.io nothing get linked: https://github.com/rust-lang/libc/blob/6307a0bfce8b3fd980b9cb514e17d524de0a666d/src/windows/mod.rs#L195

**Comment by gnzlbg** [comment]
@ollie27 so if one builds a `#[no_std]` binary, and adds the libc crate as a dependency, no C standard library will be linked ? That sounds like a bug.

**Comment by ollie27** [comment]
> so if one builds a `#[no_std]` binary, and adds the libc crate as a dependency, no C standard library will be linked ?

Correct. I don't know if it's a bug or not but it looks like the same is true of musl: https://github.com/rust-lang/libc/blob/6307a0bfce8b3fd980b9cb514e17d524de0a666d/src/unix/mod.rs#L299-L305

I guess this is just how `crt-static` works at the moment.

**Comment by alexcrichton** [comment]
It looks like this was realized in the last few comments, but replying to [this cc](https://github.com/rust-lang/rust/issues/39016#issuecomment-509723742) this PR won't have the desired effect until something like https://github.com/rust-lang/rust/pull/62534 is also added.

**Comment by Bromeon** [comment]
Has there been progress towards linking to MSVCRT**D** (debug version), as described in https://github.com/rust-lang/rust/issues/39016?

If not, are there meanwhile any known workarounds?

**Comment by jdm** [comment]
No.

**Comment by jdm** [comment]
I don't have access to a Windows development environment any more, so I won't be pushing forward on this work.

**Pull request closed without merging**
