### PR TITLE
targets: add aero target

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
Adds the [aero](https://github.com/Andy-Python-Programmer/aero) target to the libc :^)

Signed-off-by: Andy-Python-Programmer <andypythonappdeveloper@gmail.com>

### CODE REVIEW

**Comment by Amanieu** [comment]
r? @JohnTitor

Could you handle this one? I'm not fully sure what our policy is for adding new targets.

**Comment by YusufKhan-gamedev** [comment]
A bit of information on the project, it does not have any users yet, it cant connect to the internet, it does not currently have X or Wayland, and it doesnt support many unix sycalls, but it may be useful on air-gapped systems in its current form. The project is moving at a quick pace though and I wouldn't be surprised if a bunch of what it doesnt support now will be supported relatively soon.

**Comment by JohnTitor** [comment]
is this target supported on rustc? If not, it's generally preferred that you have your own fork of the libc crate and maintain it.

**Comment by Andy-Python-Programmer** [comment]
Though in order to add the target to the rust compiler itself, this needs to be upstreamed.

**Comment by JohnTitor** [comment]
If you consider adding a new target, you should follow steps like https://github.com/rust-lang/libc/pull/2227. Otherwise, reviewers cannot know if you want just to have their own target or to make it an official one.

**Comment by JohnTitor** [comment]
Triage: Closing as inactive, feel free to re-open if you find some time to work on. Thanks for the PR anyway!

**Pull request closed without merging**
