### PR TITLE
Add definitions in libc headers in Android for riscv64

### PR DESCRIPTION
**Pull request by MaoHan001**
Signed-off-by: Chen Guoyin <chenguoyin.cgy@linux.alibaba.com>
Signed-off-by: Mao Han <han_mao@linux.alibaba.com>

### CODE REVIEW

**Comment by Amanieu** [comment]
Style check is failing, can you run `cargo fmt`?

**Comment by MaoHan001** [comment]
> Style check is failing, can you run `cargo fmt`?

Style check fixed

**Comment by Amanieu** [comment]
Thanks!

@bors r+

**Comment by Amanieu** [comment]
@joshtriplett Note that this PR adds an `align.rs`, you'll want to undo this in your PR.

**Comment by MaoHan001** [comment]
> @joshtriplett Note that this PR adds an `align.rs`, you'll want to undo this in your PR.

need another PR to remove this file?

**Comment by Amanieu** [comment]
No, this needs to be done in #2845.

**Pull request merged**
