### PR TITLE
Add user_regs_struct for riscv32/64

### PR DESCRIPTION
**Pull request by kxxt**
Copied from C header: https://elixir.bootlin.com/linux/latest/source/arch/riscv/include/uapi/asm/ptrace.h

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by kxxt** [comment]
> broken_heart Test failed - [checks-actions](https://github.com/rust-lang/libc/actions/runs/4535834422/jobs/7992002193)

I forgot to make that struct pub. It should be fixed now.

**Comment by JohnTitor** [comment]
👍 @bors r+

**Comment by JohnTitor** [comment]
Could you squash commits into one?

**Comment by kxxt** [comment]
Oops. I have made a stupid mistake when copying the struct from C header. I should test it before opening this PR. I am very sorry for wasting your time on this PR. 

It should be fixed now and I have checked that it builds  fine for target `riscv64gc-unknown-linux-gnu`

**Comment by kxxt** [comment]
Maybe it is better to mention in the contribution guide that the contributor should successfully build and test **for the target that they are working** on before opening PRs.

Directly following the contribution guide to run `cd libc-test && cargo test` only builds and tests for the host architecture.

 Adding this to the contribution guide would help contributors catch this kind of mistakes and save you time.

**Comment by JohnTitor** [comment]
I'm open to see a PR :)
@bors r+

**Pull request merged**
