### PR TITLE
adding SYS_pidfd_send_signal/SYS_pidfd_getfd constants to linux uclib…

### LINKED ISSUE #3008: `SYS_pidfd_getfd` and `SYS_pidfd_send_signal` missing from `armv7-unknown-linux-uclibceabihf`
[`SYS_pidfd_getfd`](https://man7.org/linux/man-pages/man2/pidfd_getfd.2.html) and [`SYS_pidfd_send_signal`](https://man7.org/linux/man-pages/man2/pidfd_send_signal.2.html) bindings are missing from `armv7-unknown-linux-uclibceabihf`.

Encountered in: https://github.com/nix-rust/nix/pull/1868/checks?check_run_id=9560208632,

### PR DESCRIPTION
**Pull request by devnexen**
…c arm flavor.

closes #3008

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Review by JonathanWoollett-Light — APPROVED** [review]
Thank you for addressing this so quickly

**Pull request merged**
