### PR TITLE
Add dirfd on netbsd

### PR DESCRIPTION
**Pull request by Mic92**
follow up of https://github.com/rust-lang/libc/pull/571

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could the `DIR` struct be defined to avoid the unsafe cast/load?

**Comment by Mic92** [comment]
It is already defined as incomplete type in `src/unix/mod.rs`

```
pub enum DIR {}
```

**Comment by alexcrichton** [comment]
Ok in that case we can go with this. Looks like CI is failing though?

**Comment by Mic92** [comment]
here we go!

**Comment by Susurrus** [comment]
@Mic92 Thanks for submitting this!

**Pull request merged**
