### PR TITLE
feat: IPV6_RECVHOPLIMIT & IP_RECVTTL for FreeBSD

### PR DESCRIPTION
**Pull request by SteveLauC**
Add 2 constants for FreeBSD:

1. [`IP_RECVTTL`](https://github.com/search?q=repo%3Afreebsd%2Ffreebsd-src%20IP_RECVTTL&type=code)
2. [`IPV6_RECVHOPLIMIT`](https://github.com/search?q=repo%3Afreebsd%2Ffreebsd-src+IPV6_RECVHOPLIMIT&type=code)

### CODE REVIEW

**Comment by SteveLauC** [comment]
Emm, no idea why the FreeBSD CIs are failing:(

**Comment by JohnTitor** [comment]
I guess you meant `IPV6_RECVHOPLIMIT`?

**Comment by SteveLauC** [comment]
> I guess you meant `IPV6_RECVHOPLIMIT`?

Thanks for catching it! How can I make such a mistake, I guess my head is pretty dizzy at that time:D

**Review by JohnTitor — APPROVED** [review]
Thank you!

**Pull request merged**
