### PR TITLE
Add support Zephyr OS

### PR DESCRIPTION
**Pull request by tomtom5152**
[Zephyr](https://zephyrproject.org/) is an embedded RTOS that provides its own POSIX API utilising newlib. Adding support to libc is the first step in providing full rust support for the OS.

### CODE REVIEW

**Comment by tomtom5152** [comment]
Rebased onto master to resolve conflicts and noticed @JohnTitor has added the `S-blocked` tag to this. Is there any guidance on what is needed to resolve the blocked status whilst I working on greater compiler integration please?

**Comment by JohnTitor** [comment]
> Is there any guidance on what is needed to resolve the blocked status whilst I working on greater compiler integration please?

We haven't established a policy about adding a new target, and we only accept targets if an [MCP](https://github.com/rust-lang/compiler-team/issues) is approved (there are some reasons that we do not accept targets unconditionally, e.g. we have to review if a target is _legally_ valid, it's difficult to determine if we can drop the support, etc...). See https://github.com/rust-lang/libc/pull/3032 for the previous discussion.

**Comment by JohnTitor** [comment]
The MCP has been approved, this now needs to resolve merge conflicts.

**Comment by JohnTitor** [comment]
Triage: Closing as inactive, feel free to re-submit a new PR if you're still interested in this change. Thank you anyway!

**Pull request closed without merging**
