### PR TITLE
Add CLOCK_PROCESS_CPUTIME_ID and CLOCK_THREAD_CPUTIME_ID constants

### PR DESCRIPTION
**Pull request by 0323pin**
`cpu-time`, https://github.com/tailhook/cpu-time fails to compile because it misses these constants.

```
error[E0432]: unresolved imports `libc::CLOCK_PROCESS_CPUTIME_ID`, `libc::CLOCK_THREAD_CPUTIME_ID`
 --> src/clock_gettime.rs:7:12
  |
7 | use libc::{CLOCK_PROCESS_CPUTIME_ID, CLOCK_THREAD_CPUTIME_ID};
  |            ^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^
  |            |                         |
  |            |                         no `CLOCK_THREAD_CPUTIME_ID` in the root
  |            |                         help: a similar name exists in the module: `_SC_THREAD_CPUTIME`
  |            no `CLOCK_PROCESS_CPUTIME_ID` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `cpu-time` (lib) due to 1 previous error
*** Error code 101
```

With this PR included  `cpu-time` builds successfully,

```
Building for cpu-time-1.0.0
     Locking 5 packages to latest compatible versions
   Compiling libc v0.2.158
   Compiling cpu-time v1.0.0 (/usr/pkgsrc/wip/cpu-time/work/cpu-time-1.0.0)
    Finished `release` profile [optimized] target(s) in 3.56s
```

Please consider adding these.

### CODE REVIEW

**Comment by devnexen** [comment]
I think your PR deserves the label `stable-nominated` (which you can add yourself I believe).

**Comment by 0323pin** [comment]
@devnexen It doesn't look like I can do it but, I might be wrong.

I was hoping this would get merged soon, since I have another unrelated addition locally.

**Comment by devnexen** [comment]
That s fine the merge might do it then. The goal is your changes being backported to the libc-0.2 branch so it lands for the next 0.2.* release.

**Comment by 0323pin** [comment]
> That s fine the merger might do it then. The goal is your changes being backported to the libc-0.2 branch so it lands for the next 0.2.* release.

That would be great. This is also the case with the one I have in the pipeline. Another missing definition on NetBSD.

**Comment by devnexen** [comment]
sorry I forgot about this ! but you need to type the rustbot command label stable-nominated to add the label.

**Comment by 0323pin** [comment]
> sorry I forgot about this ! but you need to type the rustbot command label stable-nominated to add the label like [here](https://github.com/rust-lang/libc/pull/3925#issuecomment-2351118141).

Ahh ... thanks! That worked :)

**Pull request closed without merging**
