### PR TITLE
Nfnetfilter queue constants

### PR DESCRIPTION
**Pull request by vorner**
Constants for the linux nfqueue netlink protocol (userspace firewall).

Continuation of #1562 and #1571.

### CODE REVIEW

**Comment by vorner** [comment]
I somehow missed the build failed and now it seems to be already deleted so I can't have a look why :-(.

Is there a way I can re-run it?

**Comment by JohnTitor** [comment]
Hey @vorner could you rebase to make CI happy?
r? @JohnTitor

**Comment by vorner** [comment]
Sure, that makes sense. Even if the failure would be my fault, I'd at least get the logs.

**Comment by vorner** [comment]
So it seems the CI failures are of the same nature as the ones in #1571 ‒ some of the added constants are too new and are not available in the musl sanitized kernel headers yet. I think the options are:

* Remove these from the pull request (I've included them for completeness, but I don't need these specific ones).
* Keep them, but somehow omit them from the test on the musl-based targets (I'm not sure how exactly to do that, but I think I'd find a way by studying already existing code). As these are kernel-constants, checking them on glibc should give enough confidence that they are correct.

What would you prefer me to do?

**Comment by JohnTitor** [comment]
> Remove these from the pull request

I'd prefer this if you don't need them. But could you not remove them but comment out and add FIXME comment so that we don't forget them?

**Comment by vorner** [comment]
I've added the change as a fixup so you can review the changes incrementally. But let me squash it before merging.

**Comment by JohnTitor** [comment]
Looks good! CI failure is unrelated to this and fixed in master, could you rebase again?

**Comment by vorner** [comment]
Thanks. I've also done the squashing.

**Comment by vorner** [comment]
OK, fixed, thanks. It's a bit unusual to find a rust project with 80-column policy, the majority is 120.

**Comment by vorner** [comment]
Hmm. This failure seems to be a network issue when setting things up. Is there a way for me to re-run it?

**Pull request merged**
