### PR TITLE
Add IP_ORIGDSTADDR and others on FreeBSD.

### PR DESCRIPTION
**Pull request by vi**
A follow-up from #1252.

CC @asomers.

r? @gnzlbg

### CODE REVIEW

**Comment by vi** [comment]
I'm not sure what that test does and why it fails.

**Comment by gnzlbg** [comment]
> Maybe that constnats were added to FreeBSD too recently?

We don't test FreeBSD 12 on CI, only 11. You probably need to skip these constants in the `build.rs` for `freebsd`.

**Comment by vi** [comment]
> You probably need to skip these constants in the build.rs for freebsd.

I'm not sure how to do it.

**Comment by gnzlbg** [comment]
Something like this: https://github.com/rust-lang/libc/blob/master/libc-test/build.rs#L567

**Pull request merged**
