### PR TITLE
Use correct type for c_ulong and c_long on 32-bit netbsdlike

### PR DESCRIPTION
**Pull request by jakllsch**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Could this use `cfg_if!` and modules like `b32` and `b64` like other platforms do?

**Comment by jakllsch** [comment]
Yes, I believe it could and probably should.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks! Feel free to ping the PR whenever you update it, unfortunately github doesn't always send out notifications :(

**Comment by jakllsch** [comment]
Not sure what happened with one of those check suites, but the failure appears unrelated to my changes.

**Comment by alexcrichton** [comment]
@bors: retry

No worries, not your problem!

**Pull request merged**
