### PR TITLE
Add riscv32 support for musl C library based linux platforms

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kanavin** [comment]
ci/build.sh needs to be adjusted, so this is tested properly, as seen here:
https://github.com/rust-lang/libc/pull/2537/commits/cb585ff6f234af729b0dcba113351f2023e9fac4

**Comment by kraj** [comment]
> ci/build.sh needs to be adjusted, so this is tested properly, as seen here: [cb585ff](https://github.com/rust-lang/libc/commit/cb585ff6f234af729b0dcba113351f2023e9fac4)

musl/rv32 support is still in upstreaming process. Once thats done, we will add it to CI

**Comment by kanavin** [comment]
> > ci/build.sh needs to be adjusted, so this is tested properly, as seen here: [cb585ff](https://github.com/rust-lang/libc/commit/cb585ff6f234af729b0dcba113351f2023e9fac4)
> 
> musl/rv32 support is still in upstreaming process. Once thats done, we will add it to CI

Can you link to the merge request please then? I thought the below was enough, is there some other in-progress activity somewhere?
https://github.com/rust-lang/rust/pull/82202

**Comment by Amanieu** [comment]
Style check is failing, can you please fix it?

**Comment by kraj** [comment]
> Style check is failing, can you please fix it?

fixed

**Pull request merged**
