### PR TITLE
Update crate version to 0.2.152

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Could I bother you a bit more to also publish a new version of `libc` please? :)

### CODE REVIEW

**Comment by JohnTitor** [comment]
Sorry but you have to send a PR against the `libc-0.2` branch, the main branch now contains breaking changes for 0.3, see https://github.com/rust-lang/libc#v03-roadmap.

**Comment by GuillaumeGomez** [comment]
Ah indeed. Thanks for changing the base branch!

**Comment by JohnTitor** [comment]
I might be unclear but you need to recreate a PR as changing the base branch would contain unrelated changes :(
And if you want to ship https://github.com/rust-lang/libc/pull/3536 for example, you have to submit the same PR to the libc-0.2 branch too (the main branch is now completely for v0.3)!

**Comment by GuillaumeGomez** [comment]
Indeed I misunderstood. Sending the PRs.

**Pull request closed without merging**
