### PR TITLE
Update android ndk version to latest LTS(r23c)

### PR DESCRIPTION
**Pull request by tiann**
The latest LTS ndk version: https://developer.android.com/ndk/downloads

And the latest stable API version of Android is Android 12 (api=31)

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Seems they removed the arch suffix from the URL.

**Comment by tiann** [comment]
The URL should be correct now.

**Comment by tiann** [comment]
ndk23 remove *-ar, we should use llvm-ar instead: https://github.com/bbqsrc/cargo-ndk/issues/38

**Comment by JohnTitor** [comment]
Hm it doesn't respect AR_arm-linux-androideabi?

**Comment by tiann** [comment]
The Cargo book say that it is deprecated and unused?

https://doc.rust-lang.org/cargo/reference/config.html#target

And the CARGO_TARGET_<triple>_AR seems not exist... https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by tiann** [comment]
Maybe just use plain `AR` env?

https://stackoverflow.com/questions/69161296/link-to-external-object-using-the-right-target-specific-compiler

**Comment by JohnTitor** [comment]
Looks correct, let's try: @bors r+

**Comment by JohnTitor** [comment]
It now returns a valid test failure, `svm_zero` of `sockaddr_vm` has been changed in r23c, it seems.
Could you skip the test for now to avoid a breaking change? You could tweak at:
https://github.com/rust-lang/libc/blob/fc10a373c12fa7aefc97a7cef7a41c0c3008ad78/libc-test/build.rs#L1634-L1643

**Comment by tiann** [comment]
Is this correct ? https://github.com/rust-lang/libc/pull/2832/files#diff-aedce4e8d381f53dae77653609e3174da7ee2a184308251ad33f7a47bebabe14R1789

And could you tell me how can i test it locally or how can i check the main.c?

**Comment by tiann** [comment]
The linux commit: https://github.com/torvalds/linux/commit/dc8eeef73b63ed8988224ba6b5ed19a615163a7f

**Comment by JohnTitor** [comment]
> And could you tell me how can i test it locally or how can i check the main.c?

You could run `cd libc-test && cargo test`, see https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md#test-before-you-commit.
If you want to test like CI, e.g. setting up toolchains etc., you could check the CI config.



> This is the struct of ndk21:
> 
> ```c++
> struct sockaddr_vm {
>   __kernel_sa_family_t svm_family;
>   unsigned short svm_reserved1;
>   unsigned int svm_port;
>   unsigned int svm_cid;
>   unsigned char svm_zero[sizeof(struct sockaddr) - sizeof(sa_family_t) - sizeof(unsigned short) - sizeof(unsigned int) - sizeof(unsigned int)];
> };
> ```
> 
> And the ndk23 version:
> 
> ```c++
> struct sockaddr_vm {
>   __kernel_sa_family_t svm_family;
>   unsigned short svm_reserved1;
>   unsigned int svm_port;
>   unsigned int svm_cid;
>   __u8 svm_flags;
>   unsigned char svm_zero[sizeof(struct sockaddr) - sizeof(sa_family_t) - sizeof(unsigned short) - sizeof(unsigned int) - sizeof(unsigned int) - sizeof(__u8)];
> };
> ```
> 
> A new field: `__u8 svm_flags;` is inserted before svm_zero, but the struct keeps the same size, maybe we should modify: [https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/mod.rs#L511](https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/mod.rs?rgh-link-date=2022-06-22T15%3A17%3A48Z#L511) and [https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/android/mod.rs#L273](https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/android/mod.rs?rgh-link-date=2022-06-22T15%3A17%3A48Z#L273)

Adding `svm_flags` as a private field would be fine but changing `svm_zero` would be a breaking change. We generally don't that to follow semver.

**Comment by JohnTitor** [comment]
Let's see if there's no more failure, @bors r+

**Comment by tiann** [comment]
I skip the field_type and field and run it locally, seems work!

**Comment by JohnTitor** [comment]
Seems arm-linux-androideabi-gcc couldn't fine gcc?

**Comment by tiann** [comment]
https://github.com/bbqsrc/cargo-ndk/issues/22

**Comment by tiann** [comment]
`cargo +nightly test --target arm-linux-androideabi -Zbuild-std` would work, can we do this?

**Comment by tiann** [comment]
this workaround works, i will try it.

**Comment by JohnTitor** [comment]
The style check fails, could you fix it?

**Comment by tiann** [comment]
I checked it on https://www.shellcheck.net/, should be fine now

**Comment by tiann** [comment]
Sorry....the ndk directory is incorrect :)

**Comment by JohnTitor** [comment]
Some items aren't matched between C and Rust on arm-linux-androideabi:
```
bad isalnum function pointer: rust: 2900728801 (0xace59be1) != c 2904805356 (0xad23cfec)
bad isalpha function pointer: rust: 2900728837 (0xace59c05) != c 2904805424 (0xad23d030)
bad iscntrl function pointer: rust: 2900728897 (0xace59c41) != c 2904805544 (0xad23d0a8)
bad isdigit function pointer: rust: 2900728933 (0xace59c65) != c 2904805624 (0xad23d0f8)
bad isgraph function pointer: rust: 2900728969 (0xace59c89) != c 2904805704 (0xad23d148)
bad islower function pointer: rust: 2900729005 (0xace59cad) != c 2904805784 (0xad23d198)
bad isprint function pointer: rust: 2900729041 (0xace59cd1) != c 2904805864 (0xad23d1e8)
bad ispunct function pointer: rust: 2900729077 (0xace59cf5) != c 2904805944 (0xad23d238)
bad isspace function pointer: rust: 2900729113 (0xace59d19) != c 2904806012 (0xad23d27c)
bad isupper function pointer: rust: 2900729149 (0xace59d3d) != c 2904806120 (0xad23d2e8)
bad isxdigit function pointer: rust: 2900729185 (0xace59d61) != c 2904806200 (0xad23d338)
bad isblank function pointer: rust: 2900728873 (0xace59c29) != c 2904806352 (0xad23d3d0)
bad tolower function pointer: rust: 2900729357 (0xace59e0d) != c 2904806432 (0xad23d420)
bad toupper function pointer: rust: 2900729385 (0xace59e29) != c 2904806524 (0xad23d47c)
bad field offset svm_zero of sockaddr_vm: rust: 12 (0xc) != c 13 (0xd)
bad field size svm_zero of sockaddr_vm: rust: 4 (0x4) != c 3 (0x3)
bad IPPROTO_MAX value at byte 0: rust: 0 (0x0) != c 7 (0x7)
bad NFNL_SUBSYS_COUNT value at byte 0: rust: 12 (0xc) != c 13 (0xd)
```

Is this expected?

**Comment by tiann** [comment]
> Some items aren't matched between C and Rust on arm-linux-androideabi:
> 
> ```
> bad isalnum function pointer: rust: 2900728801 (0xace59be1) != c 2904805356 (0xad23cfec)
> bad isalpha function pointer: rust: 2900728837 (0xace59c05) != c 2904805424 (0xad23d030)
> bad iscntrl function pointer: rust: 2900728897 (0xace59c41) != c 2904805544 (0xad23d0a8)
> bad isdigit function pointer: rust: 2900728933 (0xace59c65) != c 2904805624 (0xad23d0f8)
> bad isgraph function pointer: rust: 2900728969 (0xace59c89) != c 2904805704 (0xad23d148)
> bad islower function pointer: rust: 2900729005 (0xace59cad) != c 2904805784 (0xad23d198)
> bad isprint function pointer: rust: 2900729041 (0xace59cd1) != c 2904805864 (0xad23d1e8)
> bad ispunct function pointer: rust: 2900729077 (0xace59cf5) != c 2904805944 (0xad23d238)
> bad isspace function pointer: rust: 2900729113 (0xace59d19) != c 2904806012 (0xad23d27c)
> bad isupper function pointer: rust: 2900729149 (0xace59d3d) != c 2904806120 (0xad23d2e8)
> bad isxdigit function pointer: rust: 2900729185 (0xace59d61) != c 2904806200 (0xad23d338)
> bad isblank function pointer: rust: 2900728873 (0xace59c29) != c 2904806352 (0xad23d3d0)
> bad tolower function pointer: rust: 2900729357 (0xace59e0d) != c 2904806432 (0xad23d420)
> bad toupper function pointer: rust: 2900729385 (0xace59e29) != c 2904806524 (0xad23d47c)
> bad field offset svm_zero of sockaddr_vm: rust: 12 (0xc) != c 13 (0xd)
> bad field size svm_zero of sockaddr_vm: rust: 4 (0x4) != c 3 (0x3)
> bad IPPROTO_MAX value at byte 0: rust: 0 (0x0) != c 7 (0x7)
> bad NFNL_SUBSYS_COUNT value at byte 0: rust: 12 (0xc) != c 13 (0xd)
> ```
> 
> Is this expected?

Could you tell me  how do i check this, any C header or the test code would be helpful.

**Comment by JohnTitor** [comment]
You could compare the actual definitions on C headers with the declarations on Rust. The errors tell they aren't matched.

**Comment by JohnTitor** [comment]
Closing as inactive, feel free to reopen/resubmit if you're still interested in this change. Thank you!

**Pull request closed without merging**
