### PR TITLE
Define additional IPPROTO_* constants.

### PR DESCRIPTION
**Pull request by jack-pappas**
Define additional IPPROTO_* constants, e.g. for DCCP and SCTP. These constants are standard across all system types -- the values are those assigned to the protocol by the IANA:
https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like CI is failing though?

**Comment by jack-pappas** [comment]
Yeah -- I'll fix it. These constants are the same across all platforms so I thought it might be fine to just put them all in the base module. libc-test is strict and only allowing the constants defined on each particular platform though, so I'll need to go back and move some of the constants into the platform-specific modules instead. (Will do that when I have a minute then update the PR.)

**Comment by jack-pappas** [comment]
I've updated the PR, and the build succeeds on my machine and passes most of the travis CI builds now. However, a few of the travis builds are still failing with the latest code and I don't see why that's the case. A couple of them appear to be failing in the C compiler tests with a constant redefinition error, any ideas why that's happening?

**Comment by alexcrichton** [comment]
Some of these constants may not be defined on OSX?

**Comment by jack-pappas** [comment]
Yes -- there were a few constants that'd been removed from the OSX / Darwin headers when they were ported over from FreeBSD, and I'd left them in there by accident. There were also a couple of other places where I'd added a duplicate ``IPPROTO_RAW`` constant in. I've fixed these and updated the PR.

One small note -- I had to disable (comment out) the ``IPPROTO_L2TP`` constant for NetBSD. It's defined in the latest NetBSD source, but it looks as though the docker image used by the CI tests is using an older version of NetBSD which doesn't have that constant defined. The constant was added here:
https://github.com/NetBSD/src/commit/7c6df79fc2d2c616a886db2f5e64951d33d313ef#diff-dab66d274da3dd4ba168b2ba7f3b4374R108

**Comment by alexcrichton** [comment]
@bors: r+

Ok, thanks!

**Pull request merged**
