### PR TITLE
Add ioctl FS_IOC_* version and flag constants

### PR DESCRIPTION
**Pull request by fsavy-tehtris**
This is a tentative to fix https://github.com/rust-lang/libc/pull/3089 because the original author is unlikely to revisit it.

I've added the missing architectures for the constants on Linux, I think they should all be covered now.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
@bors r+
Thanks!

**Comment by fsavy-tehtris** [comment]
I've added the missing `arm` `target_arch` but I was not able to run the Android tests on my machine.

@rustbot review

**Comment by fsavy-tehtris** [comment]
More fixes.
@rustbot review

**Comment by JohnTitor** [comment]
Could you squash commits into one?

**Comment by fsavy-tehtris** [comment]
Done!

**Review by JohnTitor — APPROVED** [review]

**Comment by fsavy-tehtris** [comment]
I _think_ I've fixed the outstanding issues with Android, although the linker does not work in the CI container.
The macOS check broke but I think this is because the related image was updated?

@rustbot review

**Comment by JohnTitor** [comment]
Yeah, the macOS failure is unrelated and has been fixed on main. Let's give another try!
@bors r+

**Pull request merged**
