### PR TITLE
libc-test: remove useless clone in build.rs

### PR DESCRIPTION
**Pull request by chenx97**
To fix recent CI failures

### CODE REVIEW

**Review by asomers — APPROVED** [review]

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Could you also address the above failure?

**Comment by chenx97** [comment]
Hopefully, it won't break again. Testing ahead of approval [here](https://github.com/chenx97/libc/actions/runs/5866153978)

**Comment by chenx97** [comment]
... would it be better to put the detection in the align module instead?

**Pull request merged**
