### PR TITLE
[WIP] Add base definitions for riscv64 + musl

### PR DESCRIPTION
**Pull request by ddevault**

### CODE REVIEW

**Comment by JohnTitor** [comment]
Is there any riscv target that uses musl as `target_env`? Also, it'd be great if you could provide some context.

**Comment by ddevault** [comment]
There will be soon. I am working on porting Alpine Linux to RISC-V. You can follow along with that work here:

https://gitlab.alpinelinux.org/alpine/aports/-/issues/12167

**Comment by JohnTitor** [comment]
Then I'd love to see a target spec as JSON and run CI for it, to make sure the build.

**Comment by ddevault** [comment]
Yeah, I will have something for rust-lang/rust as well. I need to finish bootstrapping the damn thing first, what a miserable process. Can you elaborate on the target spec as JSON issue?

**Comment by JohnTitor** [comment]
> Can you elaborate on the target spec as JSON issue?

We can pass a target spec as JSON, like https://github.com/rust-lang/libc/blob/master/ci/switch.json, to run the build test.

**Comment by protonesso** [comment]
ready to test!

**Comment by jyn514** [comment]
> Yeah, I will have something for rust-lang/rust as well. I need to finish bootstrapping the damn thing first, what a miserable process. Can you elaborate on the target spec as JSON issue?

It might be helpful to see how aarch64 did it: https://github.com/rust-lang/rust/pull/74541/

**Comment by tesuji** [comment]
`riscv{32,64}gc-unknown-linux-musl` has been added in https://github.com/rust-lang/rust/pull/82202

**Comment by JohnTitor** [comment]
> 
> 
> `riscv{32,64}gc-unknown-linux-musl` has been added in [rust-lang/rust#82202](https://github.com/rust-lang/rust/pull/82202)

Great! I'm not sure how difficult to run ctest on that target but at least we should run the build check on CI, as I said before. It can be done easily by tweaking here: https://github.com/rust-lang/libc/blob/master/ci/build.sh

**Comment by JohnTitor** [comment]
I'm going to close as inactive, feel free to rebase and re-open when you get some time :)

**Pull request closed without merging**
