### PR TITLE
Added constants from prctl.h

### PR DESCRIPTION
**Pull request by zethra**
I left in the comment from prctl.h I can remove them if you want.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Looks like CI is failing due to line length limits, and yeah in general it's ok to remove comments from this library as this isn't really the authoritative source for how to use all these values.

**Comment by alexcrichton** [comment]
Looks good to me, but looks like travis failures may be legitimate?

**Comment by zethra** [comment]
@alexcrichton Any idea how to fix the one that failed?  I'm not sure why a few specific constants are having a problem on just android.

**Comment by alexcrichton** [comment]
@zethra you can just move those constants down a level in the module hierarchy to the linux-specific module so they're not picked up on Android.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
