### PR TITLE
Define ip_mreqn on all Linux platforms

### LINKED ISSUE #1558: ip_mreqn roundtrip test fails for mips64 and sparc64
See #1555 .

### PR DESCRIPTION
**Pull request by tamird**
Updates #1558.

### CODE REVIEW

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by tamird** [comment]
Where can I see the failure details?

**Comment by Amanieu** [comment]
The failure details are here: https://github.com/rust-lang/libc/runs/4908786386?check_suite_focus=true

It seems like passing ip_mreqn by value is somehow corrupting the value on sparc64.

@JohnTitor Do you have any idea what could be causing this? I'm stumped.

**Comment by tamird** [comment]
@Amanieu I've suppressed this test on sparc64 for now; can I get another try run?

**Comment by tamird** [comment]
This failure looks unrelated (and strange):
```
    Finished test [unoptimized + debuginfo] target(s) in 1m 47s
     Running test/cmsg.rs (target/arm-unknown-linux-musleabihf/debug/deps/cmsg-0f644353fa7d873a)

running 5 tests
test t::test_cmsg_data ... ok
error: test failed, to rerun pass '--test cmsg'

Caused by:
  process didn't exit successfully: `qemu-arm -L /musl-arm /checkout/target/arm-unknown-linux-musleabihf/debug/deps/cmsg-0f644353fa7d873a` (signal: 11, SIGSEGV: invalid memory reference)
Error: Process completed with exit code 101.
```
https://github.com/rust-lang/libc/runs/4915659168?check_suite_focus=true

Can we retry?

**Pull request merged**
