### PR TITLE
Add missing AArch64 HWCAP_* and HWCAP2_* consts

### PR DESCRIPTION
**Pull request by linkmauve**
Also move `getauxval()` where it should be.

### CODE REVIEW

**Comment by linkmauve** [comment]
Hi, I can’t make sense of the CI failure, it also fails on platforms which have obviously not been touched at all.

**Comment by linkmauve** [comment]
This is now up to date again.

**Comment by JohnTitor** [comment]
Thanks! I'll review later. r? @JohnTitor

**Comment by linkmauve** [comment]
The failure happens to be here, but I can’t figure out where this main.c is generated:
https://dev.azure.com/rust-lang2/libc/_build/results?buildId=1204&view=logs&j=4e3010c9-a20c-593e-068d-9c6cb8dff68a&t=6bb3bdfa-97b8-5f1b-e620-57e5cd6272cb&l=590

**Comment by JohnTitor** [comment]
The problem is CI uses glibc 2.29 and it doesn't have newer consts, I guess. I've attempted to update CI images but encountered a roadblock :/

**Comment by linkmauve** [comment]
I could comment out the too new consts for the time being?  I originally only needed the SHA-1 and SHA-256 extensions (for https://github.com/RustCrypto/hashes/pull/97).

**Comment by JohnTitor** [comment]
Just merged #1669, can you rebase again to check if it resolves CI failure?

**Comment by linkmauve** [comment]
It still failed. :/

https://dev.azure.com/rust-lang2/libc/_build/results?buildId=1259&view=logs&j=4e3010c9-a20c-593e-068d-9c6cb8dff68a&t=6bb3bdfa-97b8-5f1b-e620-57e5cd6272cb&l=578

**Comment by JohnTitor** [comment]
Hm, I just searched dove into glibc source but I couldn't find HWCAP2_* consts.

> I could comment out the too new consts for the time being? I originally only needed the SHA-1 and SHA-256 extensions (for RustCrypto/hashes#97).

Yeah, I'm fine with that if you want :) And it'd be great if you could also leave a FIXME comment.

**Comment by linkmauve** [comment]
On my system, it isn’t provided by glibc but by linux-api-headers: https://archlinuxarm.org/packages/aarch64/linux-api-headers

**Comment by JohnTitor** [comment]
Yeah, I know, just explained why CI had a failure.
If you want to go ahead, you should make CI green by commenting out them for now, skipping the test, or adding a tweak for CI. You said you don't need them right now so I commented as above.

**Comment by linkmauve** [comment]
There, should now be fine and mergeable!

**Pull request merged**
