### PR TITLE
add CI for mips-musl

### PR DESCRIPTION
**Pull request by japaric**
and fix the statvfs struct for this target

r? @alexcrichton 

I didn't really test the CI part but this target now passes libc-test under QEMU

### CODE REVIEW

**Comment by alexcrichton** [comment]
Holy cow. My reaction to this was "surely we don't need to test *both* mips and mipsel, they're so similar!" Of course I'm wrong...

@bors: r+

Thanks @japaric!

**Comment by japaric** [comment]
> "surely we don't need to test both mips and mipsel, they're so similar!" 

#EndiannessMatters

> this target now passes libc-test under QEMU

(Shameless plug) I realized this wasn't working thanks to [smoke](https://github.com/japaric/smoke), which is looking more "green" these days.

**Comment by alexcrichton** [comment]
> which is looking more "green" these days

🎈

**Comment by alexcrichton** [comment]
Looks like the CI failures are legitimate?

**Comment by japaric** [comment]
> Looks like the CI failures are legitimate?

Fixed the SDK install.

Interestingly, glibc doesn't change the order of the f_unused and f_fsid fields according to endianness like musl does but that still works for glibc ... ? (perhaps because of C alignment rules?).

Hiding (making it a private field) f_unused seems to "fix" the problems observed on powerpc. Is that OK? being named __f_unused, I suppose that means the field is supposed to be private by C conventions.

**Comment by alexcrichton** [comment]
Ah yeah hiding it's fine by me!

@bors: r+

**Comment by alexcrichton** [comment]
That one also looks somewhat legitimate?

**Comment by japaric** [comment]
> That one also looks somewhat legitimate?

Yes, I think I stripped too many components and ended up flatteing some directories inside `include`. Will take a look later.

**Comment by japaric** [comment]
OK, that should do it.

**Comment by japaric** [comment]
OK, it's fixed for real this time. (I actually ran the test locally)

**Pull request merged**
