### PR TITLE
Add settimeofday for solaris/illumos

### LINKED ISSUE #1547: Solaris does not expose settimeofday
Solaris/Illumos have a [man page](https://illumos.org/man/3c/settimeofday), describing both get and set version, but currently only the get one is exposed

x86_64-sun-solaris (but probably all Solaris target triple)

### PR DESCRIPTION
**Pull request by GrayJack**
Closes #1547

### CODE REVIEW

**Comment by gnzlbg** [comment]
@mati865 all musl targets are broken on nightly, is this known ?

**Comment by gnzlbg** [comment]
So the PR that broke this has been reverted and the next nightly shouldn't have this issue.

**Comment by mati865** [comment]
Yeah all targets packaging start objects are broken. 
Revert PR has failed multiple times (very unlucky) https://github.com/rust-lang/rust/pull/65342 so it will be fixed tomorrow.

**Comment by GrayJack** [comment]
Is it fixed now?

**Comment by gnzlbg** [comment]
@GrayJack thanks for the ping, yes, it was fixed a couple of hours ago. 

@bors: r+

**Comment by gnzlbg** [comment]
cc @asomers @kinnison - so apparently rustup fails on FreeBSD11 because of some components not being available.

**Comment by mati865** [comment]
^ opened https://github.com/rust-lang/libc/pull/1550

**Comment by kinnison** [comment]
> EDIT: @kinnison this looks like a rustup bug, where it tries to install components that are not available for a target. Can it be that the new profiles do not know that certain targets never have some components ? (I'm not sure if FreeBSD11 sometimes has clippy and rustfmt).

I'm aware of something like this on lower tier platforms yes.  I've a fix in-train which might go out tomorrow for that part.

**Comment by asomers** [comment]
> cc @asomers @kinnison - so apparently rustup fails on FreeBSD11 because of some components not being available.
> 
> EDIT: @kinnison this looks like a rustup bug, where it tries to install components that are not available for a target. Can it be that the new profiles do not know that certain targets never have some components ? (I'm not sure if FreeBSD11 sometimes has clippy and rustfmt).

FreeBSD11 is supposed to have clippy and rustfmt, as should most platforms.  But it hasn't since late May due to this bug: https://github.com/rust-lang/rust/issues/62558 .

**Comment by GrayJack** [comment]
Doesn't seem to have something to do with my changes, only linux-android failed

**Pull request merged**
