### PR TITLE
Complete i686-unknown-linux-musl ucontext_t #2787

### LINKED ISSUE #2787: "cannot find value REG_EIP in crate libc" when targetting i686-unknown-linux-musl
[Trying to build `wasmtime` for the `i686-unknown-linux-musl` target leads to the following error](https://github.com/bytecodealliance/wasmtime/issues/4137):
```
error[E0425]: cannot find value `REG_EIP` in crate `libc`
   --> /Users/victor.paleologue/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-0.33.1/src/traphandlers/unix.rs:173:40
    |
173 |             cx.uc_mcontext.gregs[libc::REG_EIP as usize] as *const u8
    |                                        ^^^^^^^ not found in `libc`

error[E0609]: no field `gregs` on type `mcontext_t`
   --> /Users/victor.paleologue/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-0.33.1/src/traphandlers/unix.rs:173:28
    |
173 |             cx.uc_mcontext.gregs[libc::REG_EIP as usize] as *const u8
    |                            ^^^^^ unknown field
```
It seems `libc` is lacking few elements for this target platform specifically.

### PR DESCRIPTION
**Pull request by victorpaleologue**
Fix #2787

### CODE REVIEW

**Comment by Amanieu** [comment]
Tests are complaining about incomplete types. You probably need to include an additional header file in libc-test/build.rs.

**Comment by JohnTitor** [comment]
Friendly-ping, @victorpaleologue could you address the CI failure?

**Comment by victorpaleologue** [comment]
Sorry I took so long to react.
The logs are not available anymore.
Can someone re-trigger the build so that I can check the error logs?

**Comment by victorpaleologue** [comment]
> @victorpaleologue: 🔑 Insufficient privileges: Not in reviewers

That was worth trying =p

**Comment by JohnTitor** [comment]
Contributors aren't allowed to r+ PRs in general otherwise anyone could push any changes to the master 😆 

@bors try

**Comment by Toover** [comment]
Sorry I'm using an arm64 processor and I don't understand yet how to run the i686 tests on my machine. Would you please trigger the CI again?

**Comment by victorpaleologue** [comment]
Sorry I'm using an arm64 processor and I don't understand yet how to run the i686 tests on my machine. Would you please trigger the CI again?

**Comment by JohnTitor** [comment]
@bors delegate+

You can now use `@bors try`, feel free to use CI for testing. Ping me if it's ready!

**Comment by JohnTitor** [comment]
Also, it'd be great if you could squash commits once it's ready.

**Comment by victorpaleologue** [comment]
The error message metions : "internal error: entered unreachable code" when using `ctest2`. In your experience, is it likely to be an issue in `ctest2`?

**Comment by victorpaleologue** [comment]
I'm a bit stuck with an anonymous struct used in C. I don't know how to declare it and use it correctly in `mod.rs`. I'm considering working it around by fabricating a data structure that would be equivalent in memory.

**Comment by JohnTitor** [comment]
Friendly-ping @victorpaleologue, are you still working on this?

**Comment by victorpaleologue** [comment]
Not really.
I wish I could keep on working on that to get things straight, but as far as I can see, I'm not able to satisfy every platform as I should.
Let's get @bors try again and see if I get inspired by its results. Otherwise I'll have to admit defeat!

**Comment by victorpaleologue** [comment]
I think this is a progress. Something's fishy with the FreeBSD 14 job, the error seems unrelated to my work. Let's ask @bors try again and hope this time it'll be ok. On my end I'll clean my commits.

**Comment by victorpaleologue** [comment]
FreeBSD 14 again. Perhaps I'll come back later to try again.

**Comment by JohnTitor** [comment]
The failure is unrelated to this PR, I'll address next week ;) (I'm on small vacation this week)

**Comment by victorpaleologue** [comment]
Hello, I think I am stuck, I do not know how to go further.
The type `_fpstate` is meant to have an anonymous struct in the field `_st` according to musl's toolchain.
But Rust does not provide a way to declare this, so the generated Rust code is not compatible with that header.

I will close this PR now, but if anyone has an idea, please share!

**Pull request closed without merging**
