### PR TITLE
Feat(Linux): Add new process flags

### PR DESCRIPTION
**Pull request by PaulDance**
# Description

This adds two new/missing `PF_*` task flags to the Linux-like platform module:
 * `PF_BLOCK_TS` that was added relatively recently, in [6.9](https://github.com/torvalds/linux/commit/06b23f92af87a84d70881b2ecaa72e00f7838264);
 * `PF_SUSPEND_TASK` that has been there for a bit more time: [3.11](https://github.com/torvalds/linux/commit/2b44c4db2e2f1765d35163a861d301038e0c8a75);

This would be for fanotify consumption. It should be easily backportable to 0.2.

# Sources

<https://github.com/torvalds/linux/blob/2ba9f676d0a2e408aef14d679984c26373bf37b7/include/linux/sched.h#L1661>

# Checklist

- [x] Relevant tests in `libc-test/semver` have been updated
- [x] No placeholder or unstable values like `*LAST` or `*MAX` are
  included (see [#3131](https://github.com/rust-lang/libc/issues/3131))
- [x] Tested locally (`cd libc-test && cargo test --target mytarget`);
  especially relevant for platforms that may not be checked in CI

### CODE REVIEW

**Comment by PaulDance** [comment]
The error in <https://github.com/rust-lang/libc/actions/runs/12201653969/job/34040533674?pr=4174> seems unrelated to my changes, no?

**Comment by tgross35** [comment]
The changes look good to me but could you update `libc-test/semver/linux.txt`? If you wouldn't mind squashing the first and third commit ("Add new process flags" and " Add PF_BLOCK_TS to libc-test/build.rs") that would also be nice to keep tests passing after each (no worries if not, I can do it before merge).

> The error in https://github.com/rust-lang/libc/actions/runs/12201653969/job/34040533674?pr=4174 seems unrelated to my changes, no?

Indeed, looks like a new lint was added. If you're up to it feel free to add a patch with:

```rust
#[allow(unpredictable_function_pointer_comparisons)] // FIXME(msrv): stabilized in 1.85
```

Otherwise I'll get it at some point before merging this.

@rustbot label +stable-nominated

**Comment by tgross35** [comment]
Fyi I have a fix for the lint in progress

**Comment by PaulDance** [comment]
> The changes look good to me

:+1:

> could you update `libc-test/semver/linux.txt`?

I wanted to as well, but couldn't see any of the previous `PF_*` constants in there, so I thought it was on purpose for some reason. Should I still put them all there or only the ones I added?

> If you wouldn't mind squashing the first and third commit

Can do!

> I have a fix for the lint in progress #4177

I see that, thanks! I'll rebase on top of it once merged.

**Comment by tgross35** [comment]
> I wanted to as well, but couldn't see any of the previous `PF_*` constants in there, so I thought it was on purpose for some reason. Should I still put them all there or only the ones I added?

I can't think of any reason so I would just put them all there, I guess if it causes CI to fail for some reason then I'll change my answer :) thanks for offering.

**Review by tgross35 — APPROVED** [review]
LGTM, thanks for the changes!

**Comment by PaulDance** [comment]
Cool, thanks!

**Pull request merged**
