### PR TITLE
adding LOCAL_CREDS_PERSISTENT for FreeBSD.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
:-) poor bors took (well deserved) days off

**Comment by Amanieu** [comment]
@JohnTitor Any idea what's up with bors?

**Comment by JohnTitor** [comment]
Hmm, approving seems fine but it never starts the auto build, weird, auto-merge issue? I'm totally not sure, but #2316 is fine so maybe re-creating a PR would help. @Amanieu Could you ask infra folks on Zulip, if it doesn't help?

**Pull request closed without merging**
