### PR TITLE
Don't bundle static libc.

### PR DESCRIPTION
**Pull request by hvenev**

### CODE REVIEW

**Comment by gnzlbg** [comment]
Ping me when CI is green.

**Comment by hvenev** [comment]
Ping.

**Comment by alexcrichton** [comment]
This PR would unfortunately break both these targets as distributed with rust-lang/rust. The usage of `static` here is the precise use case for where `static` was designed for, which is updating the artifacts so C library doesn't have to be distributed separately but rather it's bundled with the Rust distribution.

**Comment by alexcrichton** [comment]
Yes, linking with `static` will find `libc.a` and then take all the object files from there and put them in `liblibc.rlib`. With `static-nobundle` that doesn't happen and simply passes `-lc`, which would break cross compilation use cases for musl and wasi support which doesn't require installing the sysroot.

**Comment by gnzlbg** [comment]
So one more thing. How does cross compiling for a `#![no_std]` binary that uses the libc crate from crates.io without the `use_std` feature work ? No `link(name = "c")` attributes are added in that case, so this is just a bare `extern {}` block.

**Comment by alexcrichton** [comment]
I think it just basically doesn't work, building a fully linked binary with `#[no_std]` is pretty unstable and never something we've really optimized for

**Comment by hvenev** [comment]
I don't see how musl is that different from glibc, uclibc, or dietlibc. Shouldn't something like `target_vendor = "rust"` be used to decide whether to bundle `libc` in `liblibc.rlib` versus using the one provided by the C toolchain?

**Comment by gnzlbg** [comment]
> I don't see how musl is that different from glibc

IIUC glibc is dynamically linked, while musl appears to be always statically linked. I suppose that if we were to statically link glibc, then we'd have a similar issue.

**Comment by hvenev** [comment]
Not necessarily. My platform does not support static linking.

**Comment by gnzlbg** [comment]
And when compiling with rustc musl gets dynamically linked? Which target triple is that? (I thought rustc always statically linked musl for the musl targets).

**Comment by hvenev** [comment]
A slightly modified `mips-openwrt-linux-musl`. With this patch applied and a similar change to libunwind in rustc, code compiles and runs just fine. Even unwinding seems to be there (not tested) and backtrace on panic works.

**Comment by gnzlbg** [comment]
@alexcrichton to support that it might make sense to move the logic of whether musl is statically or dynamically linked to the target specification file.

**Comment by hvenev** [comment]
Isn't the `crt-static` target feature supposed to be doing that?

**Comment by alexcrichton** [comment]
Dealing with crt linkage on musl is basically an endless world of pain unfortunately in what we have set up in rustc. It's all workable one way or another but it's very meticulously crafted right now and I would discourage large changes without having a fuller picture of what's happening.

**Comment by hvenev** [comment]
I agree with you. I've opened a new issue at https://github.com/rust-lang/rfcs/issues/2695. I'd like to hear your suggestions about how to deal with this.

**Comment by alexcrichton** [comment]
I can be around to answer questions from time to time, but I do not have the time to help design a new system and or help architect changes.

**Comment by gnzlbg** [comment]
I think that the fix here would be to just set `target_env` to `dynmusl`, such that the target triplet becomes `mips-openwrt-linux-dynmusl`, as proposed here: https://github.com/rust-lang/rust/issues/59302 , at least until a solution for https://github.com/rust-lang/rfcs/issues/2695 would be RFCed and implemented.

**Comment by mati865** [comment]
Such `target_env` has to be implemented first.

**Comment by gnzlbg** [comment]
@hvenev I'm closing this, I think that the next step here is to design a solution in rust-lang/rust for how to support both statically and dynamically-linked musl targets. And then propose a combined set of patches that implements support for this in rustc and libc, without breaking the statically linked musl targets that we already support.

@hvenev it seems that https://github.com/rust-lang/rust/issues/59302 is a good place to discuss and organize work around this.

**Comment by petrochenkov** [comment]
Posted a plan for the fixing this in rustc repo https://github.com/rust-lang/rust/issues/72274.

**Pull request closed without merging**
