### PR TITLE
UTIME_OMIT and UTIME_NOW values are inverted on OpenBSD. correct it

### PR DESCRIPTION
**Pull request by semarie**
unbreak OpenBSD after #1474

### CODE REVIEW

**Comment by lpetre** [comment]
Thanks @semarie , sorry about that inversion

**Comment by semarie** [comment]
Windows failed due to network failure:
```
error: component download failed for rust-std-i686-pc-windows-msvc
info: caused by: could not download file from 'https://static.rust-lang.org/dist/2019-08-21/rust-std-nightly-i686-pc-windows-msvc.tar.xz' to 'C:\Users\VssAdministrator\.rustup\downloads\f254146fc8586a4091576f80c195010e1e8cc284dcdab5e6afe7c3e9667d7344.partial'
info: caused by: failed to make network request
info: caused by: https://static.rust-lang.org/dist/2019-08-21/rust-std-nightly-i686-pc-windows-msvc.tar.xz: connection error: An existing connection was forcibly closed by the remote host. (os error 10054)
##[error]Cmd.exe exited with code '1'.
```

**Pull request merged**
