### PR TITLE
Add Futex Constants FUTEX_WAITERS, FUTEX_OWNER_DIED and FUTEX_TID_MASK to Linux

### PR DESCRIPTION
**Pull request by danielschemmel**
This PR adds three constants from `linux/futex.h`: `FUTEX_WAITERS`, `FUTEX_OWNER_DIED` and `FUTEX_TID_MASK`. These are related to how the kernel indicates certain events to the holders of priority-inheritance futexes (see [man 2 futex](https://man7.org/linux/man-pages/man2/futex.2.html)).

I have intentionally typed those as `u32`, rather than `::c_int`, as they are applied to the futex word (the target of the parameter `uint32_t* uaddr`).

### CODE REVIEW

**Review by tgross35 — APPROVED** [review]
Can you target `main`? We will cherry-pick to stable.

@rustbot label +stable-nominated

**Comment by tgross35** [comment]
Thanks!

**Comment by danielschemmel** [comment]
@tgross35 Thank you for the review. The PR should now target `main`.

**Pull request merged**
