### PR TITLE
Bsd domainname

### LINKED ISSUE #868: bsd: {get,set}domainname are missing
Currently {get,set}domainname are exposed on Linux and emscripten only. However they are implemented on BSDs too so they should be exposed there are as well:
 * https://www.freebsd.org/cgi/man.cgi?sektion=3&query=gethostname
 * https://man.openbsd.org/setdomainname.3
 * http://netbsd.gw.com/cgi-bin/man-cgi?getdomainname+3+NetBSD-current
 * https://www.dragonflybsd.org/cgi/web-man?command=getdomainname&section=3

### PR DESCRIPTION
**Pull request by gnzlbg**
Closes #868 .

### CODE REVIEW

**Comment by gnzlbg** [comment]
These can probably be refactored to an outer level but I just want to see if any of the BSDs breaks because of this first.

**Comment by lucab** [comment]
It looks good on the surface, but I don't have BSD knowledge or a test environment to double-check.
/cc @asomers  and @Susurrus who originally pointed this out.

PS: I tend to add a `Fixes: #868` note in PRs body to cross-reference and ease navigation.

**Comment by gnzlbg** [comment]
> PS: I tend to add a Fixes: #868 note in PRs body to cross-reference and ease navigation.

The second commit has a `Closes #868` so once this PR is squashed and merged, this issue will be automatically closed and the whole thing cross-referenced by github.

**Comment by lucab** [comment]
@gnzlbg it tests *some* BSDs, yup. I think it doesn't cover the whole genealogy, but it is often enough.

And yes, I was specifically mentioning PR body so the bug gets a direct and stable link to here as opposed to the commit (I'm lazy, plus it becomes noisy when rebasing many times). Anyway, I'm going off-topic and it was just a sidenote, don't worry and thanks for the fix!

**Comment by alexcrichton** [comment]
Thanks! Looks like OSX has a failure though?

**Comment by Susurrus** [comment]
`gethostname` is already implemented for all unices, so it can simply be removed from this PR.

**Comment by asomers** [comment]
Looks like the `namelen` argument needs to be of type `int` on FreeBSD, Dragonfly, and OSX.

**Comment by Susurrus** [comment]
And on mac, it's `getdomainname(name: *mut ::c_char, len: ::c_int)` and `etdomainname(name: *const ::c_char, len: ::c_int) -> ::c_int`

**Comment by asomers** [comment]
And unlike the other functions, `gethostname` is actually standardized.  So that can probably go in the unix directory.

**Pull request merged**
