### PR TITLE
Add EPOLLEXCLUSIVE && EPOLLWAKEUP

### PR DESCRIPTION
**Pull request by kolapapa**

### CODE REVIEW

**Comment by JohnTitor** [comment]
I cannot find any definition for these flags on the uclibc source, are they usable actually?

**Comment by kolapapa** [comment]
> I cannot find any definition for these flags on the uclibc source, are they usable actually?


Actually, I didn't find it either.

Compiling Target: `mipsel-unknown-linux-uclibc`
```shell
   Compiling tokio v1.0.1
error[E0425]: cannot find value `EPOLLEXCLUSIVE` in crate `libc`
[package]
   --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/mio-0.7.7/src/sys/unix/selector/epoll.rs:226:19
    |
226 |             libc::EPOLLEXCLUSIVE,
    |                   ^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `EPOLLWAKEUP` in crate `libc`
   --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/mio-0.7.7/src/sys/unix/selector/epoll.rs:228:19
    |
228 |             libc::EPOLLWAKEUP,
    |                   ^^^^^^^^^^^ not found in `libc`

   Compiling clap v2.33.3
   Compiling parking_lot v0.11.1
   Compiling proc-macro-error-attr v1.0.4
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `mio`.
```

image

I have added these two items. There is no error, and the program runs normally.

**Review by JohnTitor — APPROVED** [review]
Thanks for clarifying, then it seems fine to me.

**Comment by skrap** [comment]
Note that this change causes the mipsel target to fail the libc tests:
```
  cargo:warning=/home/skrap/Documents/rust-uclibc/libc/target/mipsel-unknown-linux-uclibc/debug/build/libc-test-f479457f9ef6732b/out/main.c:33476:64: error: ‘EPOLLEXCLUSIVE’ undeclared here (not in a function)
  cargo:warning=33476 |             static const int __test_const_EPOLLEXCLUSIVE_val = EPOLLEXCLUSIVE;
  cargo:warning=      |                                                                ^~~~~~~~~~~~~~
  cargo:warning=/home/skrap/Documents/rust-uclibc/libc/target/mipsel-unknown-linux-uclibc/debug/build/libc-test-f479457f9ef6732b/out/main.c:33482:61: error: ‘EPOLLWAKEUP’ undeclared here (not in a function)
  cargo:warning=33482 |             static const int __test_const_EPOLLWAKEUP_val = EPOLLWAKEUP;
  cargo:warning=      |                                                             ^~~~~~~~~~~
  cargo:warning=cc1: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
  cargo:warning=cc1: all warnings being treated as errors
  exit code: 1
```

Presumably, if we want to include these constants, we should cause them to be skipped by the tests.

**Comment by skrap** [comment]
I will include a fix to this issue in #1975 so I can make sure the libc tests pass on mipsel.

**Pull request merged**
