### PR TITLE
Improve newlib constants

### PR DESCRIPTION
**Pull request by leo60228**
This is necessary to set socket options on the Nintendo Switch, which uses a socket implementation directly ported from FreeBSD. Reopened from #1334 because I accidentally closed that.

### CODE REVIEW

**Comment by leo60228** [comment]
From the person that originally added the constants (not that it matters much, but...):

image

**Comment by mati865** [comment]
Bots failure: https://github.com/rust-lang/libc/issues/1333

**Comment by gnzlbg** [comment]
@leo60228 do you have a link to these definitions in newlib upstream ?

**Comment by gnzlbg** [comment]
Also, the Nintendo Switch libc bindings live here: https://github.com/rust-lang/libc/blob/master/src/switch.rs 

But maybe those aren't necessary anymore and can be deleted ?

---

It would be great if you could add at least a test that builds libc for your target.

**Comment by leo60228** [comment]
@gnzlbg There's two Switch Rust toolchains; one based on newlib, and one based on pure Rust. switch.rs is for the pure Rust one.

**Comment by leo60228** [comment]
Newlib upstream doesn't support sockets beyond copying the headers from Linux when built for Linux. The Switch's sockets are ported directly from FreeBSD, so I copied them over. I could possibly add a cfg flag so that the constants are only used on the Switch?

**Comment by leo60228** [comment]
That .travis.yml says that it's using the dkp linker solely due to the outdated GBA CPU having problems with lld. I've been using dkp's linker for the Switch. Should I try to get it working with lld, or just use dkp's linker like the GBA does?

**Comment by leo60228** [comment]
All of the newlib Switch-specific stuff is in the libnx repo: https://github.com/switchbrew/libnx/tree/master/nx/external/bsd/include/sys

I don't know why it's done this way when newlib includes headers itself for Cygwin and Linux, but...

**Comment by leo60228** [comment]
@gnzlbg The CI seems to work.

**Comment by leo60228** [comment]
#1333 still hasn't been fixed yet. I'm on mobile, but I'm pretty sure that's what's causing Travis to fail.

**Pull request merged**
