### PR TITLE
[uclibc] add more structs to x86_64

### PR DESCRIPTION
**Pull request by humenda**
This adds more structs to the uclibc/x86_64 port.

### CODE REVIEW

**Comment by Susurrus** [comment]
Removing the `in_addr` and `in6_addr` structs is a breaking change and will prevent this PR from being merged. I suggest you remove those changes, either fixing those structs or leaving a comment there like you did stating they may be incorrect, in order to get this PR merged in a timely fashion.

**Comment by alexcrichton** [comment]
This is actually a tier 3 platform so breakage is ok (nothing is automatically verified here). @humenda despite this though was there a reason to remove those structs?

**Comment by humenda** [comment]
L4Re doesn't have networking and this is what I am targeting with uclibc/x86_64.
That made me a bit ignorant and I simply removed the unverified structs. I'll
add them again, since they might be useful on other platforms.

**Comment by alexcrichton** [comment]
Ok, I think you're the main user of uclibc on x86_64 for now, so sounds good!

@bors: r+

**Pull request merged**
