### PR TITLE
Redox target fix

### LINKED ISSUE #1420: Building for x86_64-unknown-redox results in an empty crate
See for example generated [docs](https://rust-lang.github.io/libc/x86_64-unknown-redox/libc/index.html). I think it was overlooked in  #1332 and until rust-lang/rust#60139 lands we should use `#[cfg(any(unix, target_os="redox"))]` [here](https://github.com/rust-lang/libc/blob/master/src/lib.rs#L116).

cc @jackpot51

### PR DESCRIPTION
**Pull request by newpavlov**
Closes #1420

### CODE REVIEW

**Comment by gnzlbg** [comment]
@newpavlov please implement these like #1403 does.

**Comment by newpavlov** [comment]
Looks like some more involved fixes are needed. @jackpot51 can you handle `cfg` fix as part of #1403?

**Comment by gnzlbg** [comment]
@newpavlov I would prefer if that happened in #1403 as well, could you send @jackpot51 a PR with your fix ?

**Comment by newpavlov** [comment]
Done! Closing in favor of the linked PR.

**Pull request closed without merging**
