### PR TITLE
Run build test for `x86_64-unknown-redox`

### LINKED ISSUE #1457: Temporarily disable redox target (tracking issue)
cc @jackpot51 I'm disabling the build tests for the redox target as part of the migration to Azure. It should be re-enabled in the redox PRs that migrate to the unix target.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fix #1457

### CODE REVIEW

**Comment by JohnTitor** [comment]
Okay, we've found that it seems some items in `src/unix/mod.rs` aren't defined in redox actually.
I'd downgrade CI to build testing to avoid breakage for now but we should address at some point.

**Comment by pietroalbini** [comment]
@bors r-

Bors mistakenly thought this didn't fail after a synchronize.

**Pull request merged**
