### PR TITLE
Port #672 and #686 to Android.

### PR DESCRIPTION
**Pull request by marmistrz**
I'd rather avoid the duplication, but this is discussed in #707.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like CI may be failing?

**Comment by alexcrichton** [comment]
Still failing :(

**Comment by marmistrz** [comment]
It looks like some syscalls: `SYS__llseek`, `SYS__sysctl` and `SYS__newselect` are not present in CI. But they seem to be present in the Android sources:
```
sysroot/usr/include/mips64el-linux-android/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
sysroot/usr/include/arm-linux-androideabi/asm/unistd-common.h:#define __NR__llseek (__NR_SYSCALL_BASE + 140)
sysroot/usr/include/mipsel-linux-android/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
sysroot/usr/include/x86_64-linux-android/asm/unistd_32.h:#define __NR__llseek 140
sysroot/usr/include/i686-linux-android/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-9/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-9/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-9/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-9/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-9/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-9/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-13/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-13/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-13/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-13/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-13/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-13/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-26/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-26/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-26/arch-x86_64/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-26/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-26/arch-mips64/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-22/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-22/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-22/arch-x86_64/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-22/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-22/arch-mips64/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-15/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-15/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-15/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-15/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-15/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-15/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-16/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-16/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-16/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-16/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-16/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-16/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-23/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-23/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-23/arch-x86_64/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-23/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-23/arch-mips64/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-17/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-17/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-17/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-17/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-17/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-17/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-14/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-14/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-14/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-14/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-14/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-14/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-21/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-21/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-21/arch-x86_64/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-21/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-21/arch-mips64/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-18/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-18/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-18/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-18/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-18/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-18/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-24/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-24/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-24/arch-x86_64/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-24/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-24/arch-mips64/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-19/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-19/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-19/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-19/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-19/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-19/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
platforms/android-12/arch-mips/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-12/arch-mips/usr/include/asm/unistd.h:#define __NR__llseek (__NR_Linux + 140)
platforms/android-12/arch-arm/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-12/arch-arm/usr/include/asm/unistd.h:#define __NR__llseek (__NR_SYSCALL_BASE+140)
platforms/android-12/arch-x86/usr/include/sys/linux-syscalls.h:#define __NR__llseek                      (__NR_SYSCALL_BASE + 140)
platforms/android-12/arch-x86/usr/include/asm/unistd_32.h:#define __NR__llseek 140
```

**Comment by alexcrichton** [comment]
This'll just need to go green to land!

**Comment by marmistrz** [comment]
@alexcrichton 
I simply have no idea why the `#defines` are not recognized. They should be, since they are here in `asm/unistd_32.h`, the headers look perfectly alright.

Is there any Android expert here?

**Comment by marmistrz** [comment]
Here you are, I just commented these out. I don't have the time to cope with Android's weirdness.

**Pull request merged**
