### PR TITLE
Add sched_get/setparam and sched_get/setscheduler to Solarish

### PR DESCRIPTION
**Pull request by rtzoeller**
Also define scheduling constants for illumos.

### CODE REVIEW

**Comment by rtzoeller** [comment]
It's very likely that the scheduling constants I've added for illumos are also accurate for Solaris. However, I've been unable to verify this myself (the Solaris man pages list the constant names, but not their numeric values).

If someone with more familiarity with Solaris could confirm their numeric values, I'd be happy to promote the constants up a level.

**Comment by devnexen** [comment]
checked on solaris 11 they are the same ;-)

**Comment by rtzoeller** [comment]
Thanks @devnexen!

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Looks good, thanks both!
@bors r+

**Comment by rtzoeller** [comment]
@JohnTitor the build failure looks unrelated to the changes in this PR.

**Comment by JohnTitor** [comment]
Thanks for the ping! I'm on mobile currently and I'll take a look later.

**Pull request merged**
