### PR TITLE
Upgrade crate version to 0.2.86

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Following #2058.

If you could make a release, it'd be awesome! Thanks in advance!

### CODE REVIEW

**Comment by nielx** [comment]
Would it be possible to include 05cc7961aff08b9bb1e6eb55a88dbbf36c3f47e0 ? That would be useful for the Haiku platform and for some changes to downstream crates (backtrace-rs) that would like to do.

**Comment by JohnTitor** [comment]
> 
> 
> Would it be possible to include [05cc796](https://github.com/rust-lang/libc/commit/05cc7961aff08b9bb1e6eb55a88dbbf36c3f47e0) ? That would be useful for the Haiku platform and for some changes to downstream crates (backtrace-rs) that would like to do.

Yeah, it should be included in the next release :)

**Comment by GuillaumeGomez** [comment]
@nielx If it's been merged before this PR, it'll be part of it.

**Comment by nielx** [comment]
Great, thanks!

**Review by JohnTitor — APPROVED** [review]
Let's make a new release :shipit:

**Pull request merged**
