### PR TITLE
several const ioctl() BPF aren't defined on OpenBSD

### PR DESCRIPTION
**Pull request by semarie**
unbreak OpenBSD after #1448

### CODE REVIEW

**Comment by semarie** [comment]
I could do better if I include `net/bpf.h` in `libc-test`

**Comment by semarie** [comment]
@gnzlbg I looked deeper to include `net/bpf.h` in openbsd ci, and redefine what's need.

ioctl not defined on OpenBSD:
- BIOCGSEESENT
- BIOCSSEESENT

ioctl with different value on OpenBSD:
- BIOCGRSIG
- BIOCSRSIG
- BIOCSDLT

**Comment by equal-l2** [comment]
@semarie Thank you for the follow-up!

**Pull request merged**
