### PR TITLE
define `TIMER_ABSTIME` on BSD

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by gnzlbg** [comment]
Looks like this constant is not available on Apple systems.

**Comment by gnzlbg** [comment]
Are you sure its available on all bsd systems? (OpenBSD, DragonflyBSD, NetBSD, FreeBSD, etc.) ?

**Comment by jbeich** [comment]
> Looks like this constant is not available on Apple systems.

Not surprising given Apple rarely if ever updates BSD bits.

> Are you sure that it's available on all bsd systems?

See http://fxr.watson.org/fxr/trackident?i=TIMER_ABSTIME

**Comment by gnzlbg** [comment]
These still need to be omitted from Apple platforms.

**Comment by strake** [comment]
@gnzlbg done

**Pull request merged**
