### PR TITLE
Added MAP_FIXED_NOREPLACE and MAP_SHARED_VALIDATE consts.

### PR DESCRIPTION
**Pull request by ibabushkin**
This addresses #1339 and #1315. I believe the location of the constants is correct as-is, as both flags are linux-specific additions. Let me know if I missed anything.

### CODE REVIEW

**Comment by ibabushkin** [comment]
Unsure why the travis build was canceled, and I don't think I can do anything about it short of a force-push.

**Comment by gnzlbg** [comment]
@ibabushkin I canceled it manually because it was going to fail anyways (CI was temporarily broken due to unrelated issues).

So don't do anything, bors will take care of that (it will run the tests and if everything passes, it will merge this, and if not, it will comment here with what failed).

**Comment by ibabushkin** [comment]
Alright, makes sense!

**Comment by ibabushkin** [comment]
Okay, apparently musl, android and some other platforms do not expose these flags. I'll move the code and fix it.

**Comment by gnzlbg** [comment]
Can you check the musl and android headers for these? Maybe we just have to update the versions that we use of those headers (there is a PR for android open).

**Comment by ibabushkin** [comment]
On 2019-05-16, gnzlbg wrote:
> Can you check the musl and android headers for these? Maybe we just have to update the versions that we use of those headers (there is a PR for android open).
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/rust-lang/libc/pull/1340#issuecomment-493084418

Sure thing, will do!

**Comment by ibabushkin** [comment]
Current musl does not expose `MAP_FIXED_NOREPLACE` for some time now, bumping the version to 1.1.22 should work I think, will test.

The android build failed for some unrelated reason it seems: https://travis-ci.com/rust-lang/libc/jobs/200704897

Same for emscripten: https://travis-ci.com/rust-lang/libc/jobs/200704899 https://travis-ci.com/rust-lang/libc/jobs/200704900

I haven't yet isolated the issues there.

**Comment by gnzlbg** [comment]
Ok, so don't worry about Android and Emscripten for now. The build jobs for these targets are allowed to fail, so as you've noticed, they might fail for unrelated reasons.

**Comment by ibabushkin** [comment]
Alright, I updated musl for most docker containers (sorry for the delay). mips and mipsel use OpenWRT toolchains though, and I haven't yet found musl versions current enough there. Is there a reason for that or does it make sense to try and use an upstream musl there as well? I suppose the issue could be difficulty obtaining a working toolchain, but I don't see that documented anywhere so far.

**Comment by gnzlbg** [comment]
> mips and mipsel use OpenWRT toolchains though, and I haven't yet found musl versions current enough there.

It is possible to update this, but this would probably require doing the update in a synchronized fashion with rust-lang/rust since OpenWRT is used there to create the Rust toolchains for these targets. That is, it would be better to do that in a follow PR, were one branches libc, creates a PR to rust-lang/rust that updates this and uses the branch, makes sure bors: try passes there, and once everything is green in rust-lang/rust, we merge the libc parts here, do a quick release, update the PR upstream to use the released version, and merge that.

**Comment by gnzlbg** [comment]
That is, I think it would be better to not expose these for musl targets here, merge this, and then work on the musl parts later.

**Comment by ibabushkin** [comment]
Alright, I have reverted the mips-related commits. Not the updated musl toolchains for other arches though, I believe that is fine (since I also removed musl support for the two flags for now).

**Comment by ibabushkin** [comment]
Alright, I'll proceed to add musl support separately :)

**Comment by gnzlbg** [comment]
@ibabushkin i had to check the musl support for those targets today, and the musl versions used there are very old, so I think it would be ok to just not provide these constants for musl mips targets.

**Pull request merged**
