### PR TITLE
Revert breaking musl change

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
cc @xen0n - this reverts some of the changes in your PR due to #1483

**Comment by xen0n** [comment]
Ahh, that's unfortunate... Awkward moment.

I'll be investigating this in a few days, currently busy IRL. Sorry for the breakage!

**Comment by gnzlbg** [comment]
0.2.63 was yanked. 0.2.64 has not been published yet, but could publish
tomorrow

**Comment by Osspial** [comment]
When is this going to get published?

**Pull request merged**
