### PR TITLE
Expose unix ECN-related constants

### PR DESCRIPTION
**Pull request by Ralith**
I'm not certain of the correctness of the BSD definition, but I assume that's what CI's for.

### CODE REVIEW

**Comment by gnzlbg** [comment]
@Ralith thank you for the PR! It appears that C failed, could you take a look?

**Comment by semarie** [comment]
> Perhaps it was added recently? https://github.com/openbsd/src/blob/master/sys/netinet/ip.h#L126

oops. It seems my grep pattern on my system was wrong when I quickly
checked. You're right, constants are here (and since 2002).

Sorry about that.

**Comment by Ralith** [comment]
CI failure looks spurious?

**Comment by gnzlbg** [comment]
> but I assume that's what CI's for.

Our CI for the *BSDs is incomplete at best. Do you have links for NetBSD and DragonflyBSD ? Otherwise this looks good to go (I've restarted CI but should be green).

**Comment by Ralith** [comment]
NetBSD has IP_TOS = 3 in [in.h](https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/netinet/in.h), a superset of the ECN defines in [ip.h](https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/netinet/ip.h), and the TCLASS definitions in [in6.h](https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/netinet6/in6.h).

DragonflyBSD has IP_TOS in [in.h](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/master/sys/netinet/in.h), the ECN defines in [ip.h](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/master/sys/netinet/ip.h), and the TCLASS definitions in [in6.h](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/master/sys/netinet6/in6.h) but does not appear to have IP_RECVTOS, so I've moved that down a level.

**Comment by Ralith** [comment]
Looks like I was overly optimistic in placing the `IPTOS_ECN_...` definitions at the top level of `unix`; e.g. solaris (in any form I can find) doesn't supply them. I've narrowed them to notbsd/bsd for now.

**Comment by Ralith** [comment]
What's needed for this to proceed?

**Comment by alexcrichton** [comment]
@bors: r+

Just a notification that it's ready!

**Pull request merged**
