### PR TITLE
Fix build.rs failing with a rustc built from a tarball

### LINKED ISSUE #1601: Build fails with rustc build from tarball
When `rustc` is built from a tarball, it has no git hash in the output of `rustc --version`. This causes our build.rs to fail, which expects a git hash and date to always be present in the version string.

See https://github.com/rust-lang/libc/pull/1536#issuecomment-555982049 for the original discusssion

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #1601

### CODE REVIEW

**Comment by semarie** [comment]
just tested with my local tester on OpenBSD (with rustc built from tarball), and it is fine with it.

**Comment by Aaron1011** [comment]
@gnzlbg: The failure looks spurious.

**Comment by Aaron1011** [comment]
Looks like another spurious failure

**Pull request merged**
