### PR TITLE
Fix ABI compatibility with Emscripten >= 3.1.42

### PR DESCRIPTION
**Pull request by kleisauke**
See:
https://github.com/emscripten-core/emscripten/pull/19569#issuecomment-1605440414

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks! @bors r+

**Comment by JohnTitor** [comment]
Seems we have to early return if rustc version is too old (I think it's fine as the usage rate should be ultimately low).

**Comment by kleisauke** [comment]
I think commit 92db93cf9e756d9ac51115acaa369ebc0cbff83f would fix the build on older Rust versions.

**Comment by JohnTitor** [comment]
Seems good 👍, @bors r+

**Pull request merged**
