### PR TITLE
Add struct `sockaddr_dl` for bsdlike platforms

### PR DESCRIPTION
**Pull request by LuoZijun**
Freebsd: https://github.com/freebsd/freebsd/blob/master/sys/net/if_dl.h#L59
Macos: https://github.com/apple/darwin-xnu/blob/master/bsd/net/if_dl.h#L95

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like the FreeBSD CI builder is failing though?

**Comment by Susurrus** [comment]
@LuoZijun You probably need to add the `sys/net/if_dl.h` header during the build script for FreeBSD builds to make sure this struct is visible (see https://github.com/freebsd/freebsd/blob/82974662ad9f9ece5f8374d2c898e83bd03aece9/sys/net/if_dl.h). You can look through `libc-test/build.rs` for where to do this.

**Comment by LuoZijun** [comment]
@Susurrus okay.

**Comment by LuoZijun** [comment]
@alexcrichton ping ...

**Comment by Susurrus** [comment]
I think the current styling is to have commas after every field in a struct.

**Comment by LuoZijun** [comment]
@Susurrus okay, i have fix that code style.

but `macos` `libc-test` is failure.

i have no idea for that.

**Comment by LuoZijun** [comment]
@Susurrus okay, it's done.

**Comment by LuoZijun** [comment]
@alexcrichton all green.

**Comment by LuoZijun** [comment]
@alexcrichton ping ...

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
