### PR TITLE
add missing socket constants

### PR DESCRIPTION
**Pull request by ndusart**
Add some missing socket constants that are hardcoded by `nix` (nix-rust/nix#647)

I took the opportunity to merge some constants in a upper module when applicable.

### CODE REVIEW

**Comment by ndusart** [comment]
Fixes #655

**Comment by ndusart** [comment]
I've got some problems defining `SO_RESTRICTION` and `SO_RESTRICT_*` constants for apple platforms.

These are defined in `sys/socket.h`: https://github.com/opensource-apple/xnu/blob/dc0628e187c3148723505cf1f1d35bb948d3195b/bsd/sys/socket.h#L188-L190
in a `#ifdef PRIVATE` block, but even when defining it in build.rs (using `cfg.define("PRIVATE", None)`), it fails to get these constants.

@alexcrichton Do I misused the ctest generator for this ?

**Comment by alexcrichton** [comment]
Nah I can see `-DPRIVATE` passed but it looks like that's not working? Maybe these can't be defined for OSX yet?

**Comment by Susurrus** [comment]
Reproducing my comment in nix-rust/nix#647 here:

Those constants don't actually exist on Mac as of 10.11.6 (I have one locally). I did `grep SO_RESTRICT -r /usr/include` and turned up nothing. Additionally I looked through `/usr/include/sys/socket.h` and those constants are gone (though the values aren't reused by other constants).

I think the `PRIVATE` constant is a good hint that these should never have been used by external code anyways, so it's unsurprising that they've removed them. I don't think they should be added to `libc`.

**Comment by ndusart** [comment]
OK it's RTM then.

**Comment by ndusart** [comment]
Just added missing `SOCK_RDM` for linux and android.

Really ready to be merged now :)

**Pull request merged**
