### PR TITLE
Define XATTR flags, and add XATTR functions for OSX

### PR DESCRIPTION
**Pull request by PlasmaPower**
As found in:

http://elixir.free-electrons.com/linux/latest/source/include/uapi/linux/xattr.h

https://opensource.apple.com/source/xnu/xnu-2050.7.9/bsd/sys/xattr.h

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Oh, it looks like we don't have xattr functions for OSX yet. Adding those now.

**Comment by PlasmaPower** [comment]
Done. It should be noted that OSX doesn't have lgetxattr, lsetxattr, etc. but rather uses a flag passed to the base versions of those functions.

**Comment by PlasmaPower** [comment]
It should also be noted that in regards to OSX I'm relying on Travis to test my changes as I don't have an OSX machine. I was hoping this would be a constant only change.

**Comment by PlasmaPower** [comment]
Ok, Travis is passing so it looks like my function signatures are finally correct.

**Comment by alexcrichton** [comment]
Looks great to me, thanks!

@bors: r+

**Pull request merged**
