### PR TITLE
netbsd siginfo_t si_status accessor

### LINKED ISSUE #2265: siginfo_t is missing si_status() on NetBSD
I'm attempting to build [process_control](https://github.com/dylni/process_control) on NetBSD and get the following build error: 
`no method named `si_status` found for struct `siginfo_t` in the current scope` ([source](https://github.com/dylni/process_control/blob/60184e1521d58ba1482afd9913eb4718e2faf071/src/unix.rs#L171)).

This relates in particular to calling `waitid()`, support for which was kindly [added recently](https://github.com/rust-lang/libc/issues/2243) (thanks!).

I can see that `siginfo_t` is missing `si_status()` on NetBSD (`*-*-netbsd`), although I see `si_status` is a member of `siginfo_t` on NetBSD. 

References:
* [siginfo(2)](https://man.netbsd.org/siginfo.2)
* [siginfo.h](https://github.com/NetBSD/src/blob/trunk/sys/sys/siginfo.h)

### PR DESCRIPTION
**Pull request by devnexen**
closes #2265

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
It should be unrelated/spurious, @bors retry

**Comment by JohnTitor** [comment]
Ugh, this PR is CURSED. @bors retry

**Comment by devnexen** [comment]
thanks for your patience :-)

**Pull request merged**
