### PR TITLE
fix(freebsd): incorrect constant type from ttycom.h

### PR DESCRIPTION
**Pull request by nanpuyue**
ref: https://github.com/rust-lang/libc/pull/493

the value and type of the constant are obtained by executing the following script

ttycom.sh:
```
#/bin/sh

cat <<EOF
#include <stdio.h>
#include <sys/ttycom.h>
#include <sys/time.h>
#include <termios.h>

void main() {
EOF

grep -o TIOC[A-Z_]* /usr/include/sys/ttycom.h | sort -u |\
 xargs -I{} echo '    printf("pub const {}: u%lu = 0x%lx;\n", sizeof({})*8, {});'

echo '}'
```

```
./ttycom.sh > main.c
clang main.c
./a.out
```

### CODE REVIEW

**Comment by nanpuyue** [comment]
sorted diff of `freebsdlike/mod.rs`:

```diff
--- mod.rs        2022-01-06 02:22:19.066990653 +0800
+++ mod.rs       2022-01-06 02:23:13.746856345 +0800
@@ -1,56 +1,58 @@
-pub const TIOCCDTR: ::c_uint = 0x20007478;
+pub const TIOCCBRK: ::c_ulong = 0x2000747a;
+pub const TIOCCDTR: ::c_ulong = 0x20007478;
 pub const TIOCCONS: ::c_ulong = 0x80047462;
-pub const TIOCDRAIN: ::c_uint = 0x2000745e;
-pub const TIOCEXCL: ::c_uint = 0x2000740d;
+pub const TIOCDRAIN: ::c_ulong = 0x2000745e;
+pub const TIOCEXCL: ::c_ulong = 0x2000740d;
 pub const TIOCEXT: ::c_ulong = 0x80047460;
 pub const TIOCFLUSH: ::c_ulong = 0x80047410;
-pub const TIOCGDRAINWAIT: ::c_uint = 0x40047456;
-pub const TIOCGETA: ::c_uint = 0x402c7413;
-pub const TIOCGETD: ::c_uint = 0x4004741a;
-pub const TIOCGPGRP: ::c_uint = 0x40047477;
-pub const TIOCGSID: ::c_uint = 0x40047463;
-pub const TIOCGWINSZ: ::c_uint = 0x40087468;
+pub const TIOCGDRAINWAIT: ::c_ulong = 0x40047456;
+pub const TIOCGETA: ::c_ulong = 0x402c7413;
+pub const TIOCGETD: ::c_ulong = 0x4004741a;
+pub const TIOCGPGRP: ::c_ulong = 0x40047477;
+pub const TIOCGSID: ::c_ulong = 0x40047463;
+pub const TIOCGWINSZ: ::c_ulong = 0x40087468;
 pub const TIOCMBIC: ::c_ulong = 0x8004746b;
 pub const TIOCMBIS: ::c_ulong = 0x8004746c;
-pub const TIOCM_CAR: ::c_int = 0x40;
-pub const TIOCM_CD: ::c_int = 0x40;
-pub const TIOCM_CTS: ::c_int = 0x20;
-pub const TIOCM_DSR: ::c_int = 0x100;
-pub const TIOCM_DTR: ::c_int = 0x2;
-pub const TIOCMGDTRWAIT: ::c_uint = 0x4004745a;
-pub const TIOCMGET: ::c_uint = 0x4004746a;
-pub const TIOCM_LE: ::c_int = 0x1;
-pub const TIOCM_RI: ::c_int = 0x80;
-pub const TIOCM_RNG: ::c_int = 0x80;
-pub const TIOCM_RTS: ::c_int = 0x4;
+pub const TIOCM_CAR: ::c_uint = 0x40;
+pub const TIOCM_CD: ::c_uint = 0x40;
+pub const TIOCM_CTS: ::c_uint = 0x20;
+pub const TIOCM_DSR: ::c_uint = 0x100;
+pub const TIOCM_DTR: ::c_uint = 0x2;
+pub const TIOCMGDTRWAIT: ::c_ulong = 0x4004745a;
+pub const TIOCMGET: ::c_ulong = 0x4004746a;
+pub const TIOCM_LE: ::c_uint = 0x1;
+pub const TIOCM_RI: ::c_uint = 0x80;
+pub const TIOCM_RNG: ::c_uint = 0x80;
+pub const TIOCM_RTS: ::c_uint = 0x4;
 pub const TIOCMSDTRWAIT: ::c_ulong = 0x8004745b;
 pub const TIOCMSET: ::c_ulong = 0x8004746d;
-pub const TIOCM_SR: ::c_int = 0x10;
-pub const TIOCM_ST: ::c_int = 0x8;
-pub const TIOCNOTTY: ::c_uint = 0x20007471;
-pub const TIOCNXCL: ::c_uint = 0x2000740e;
-pub const TIOCOUTQ: ::c_uint = 0x40047473;
+pub const TIOCM_SR: ::c_uint = 0x10;
+pub const TIOCM_ST: ::c_uint = 0x8;
+pub const TIOCNOTTY: ::c_ulong = 0x20007471;
+pub const TIOCNXCL: ::c_ulong = 0x2000740e;
+pub const TIOCOUTQ: ::c_ulong = 0x40047473;
 pub const TIOCPKT: ::c_ulong = 0x80047470;
-pub const TIOCPKT_DATA: ::c_int = 0x0;
-pub const TIOCPKT_DOSTOP: ::c_int = 0x20;
-pub const TIOCPKT_FLUSHREAD: ::c_int = 0x1;
-pub const TIOCPKT_FLUSHWRITE: ::c_int = 0x2;
-pub const TIOCPKT_IOCTL: ::c_int = 0x40;
-pub const TIOCPKT_NOSTOP: ::c_int = 0x10;
-pub const TIOCPKT_START: ::c_int = 0x8;
-pub const TIOCPKT_STOP: ::c_int = 0x4;
-pub const TIOCSCTTY: ::c_uint = 0x20007461;
+pub const TIOCPKT_DATA: ::c_uint = 0x0;
+pub const TIOCPKT_DOSTOP: ::c_uint = 0x20;
+pub const TIOCPKT_FLUSHREAD: ::c_uint = 0x1;
+pub const TIOCPKT_FLUSHWRITE: ::c_uint = 0x2;
+pub const TIOCPKT_IOCTL: ::c_uint = 0x40;
+pub const TIOCPKT_NOSTOP: ::c_uint = 0x10;
+pub const TIOCPKT_START: ::c_uint = 0x8;
+pub const TIOCPKT_STOP: ::c_uint = 0x4;
+pub const TIOCSBRK: ::c_ulong = 0x2000747b;
+pub const TIOCSCTTY: ::c_ulong = 0x20007461;
 pub const TIOCSDRAINWAIT: ::c_ulong = 0x80047457;
-pub const TIOCSDTR: ::c_uint = 0x20007479;
+pub const TIOCSDTR: ::c_ulong = 0x20007479;
 pub const TIOCSETA: ::c_ulong = 0x802c7414;
 pub const TIOCSETAF: ::c_ulong = 0x802c7416;
 pub const TIOCSETAW: ::c_ulong = 0x802c7415;
 pub const TIOCSETD: ::c_ulong = 0x8004741b;
 pub const TIOCSPGRP: ::c_ulong = 0x80047476;
-pub const TIOCSTART: ::c_uint = 0x2000746e;
-pub const TIOCSTAT: ::c_uint = 0x20007465;
+pub const TIOCSTART: ::c_ulong = 0x2000746e;
+pub const TIOCSTAT: ::c_ulong = 0x20007465;
 pub const TIOCSTI: ::c_ulong = 0x80017472;
-pub const TIOCSTOP: ::c_uint = 0x2000746f;
+pub const TIOCSTOP: ::c_ulong = 0x2000746f;
 pub const TIOCSWINSZ: ::c_ulong = 0x80087467;
-pub const TIOCTIMESTAMP: ::c_uint = 0x40107459;
+pub const TIOCTIMESTAMP: ::c_ulong = 0x40107459;
 pub const TIOCUCNTL: ::c_ulong = 0x80047466;
```

**Comment by Amanieu** [comment]
cc @asomers

**Review by asomers — APPROVED** [review]
LGTM.  These should all be `unsigned long` in Rust, because while in C they're defined typelessly, their main function is to be passed to `ioctl`, which expects an `unsigned long`.

**Pull request merged**
