### PR TITLE
Upgrade Travis to using Xenial environment

### LINKED ISSUE #1148: Docker build issues on Travis
Seeing this for various builds on #1130 and #1146 and probably some other PRs. Errors vary, but some examples are:
* https://travis-ci.org/rust-lang/libc/jobs/459072481
```
Step 1/4 : FROM ubuntu:18.04
error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
```
* https://travis-ci.org/rust-lang/libc/jobs/459075930
```
Step 1/14 : FROM ubuntu:16.04
unauthorized: authentication required
```
* https://travis-ci.org/rust-lang/libc/jobs/459075937
```
Step 1/5 : FROM ubuntu:17.10
17.10: Pulling from library/ubuntu
age configuration: unknown blob
```

None of them AFAIK have anything to do with the PRs in question, but are making testing/merging much harder.

### PR DESCRIPTION
**Pull request by palfrey**
One part "lets use the latest things", to several parts "might this fix #1148"

### CODE REVIEW

**Comment by palfrey** [comment]
Well, it didn't fix #1148 (see https://travis-ci.org/rust-lang/libc/jobs/459211639). OTOH once Travis fix whatever #1148 actually is in their underlying infrastructure, this would then be worth merging still

**Comment by alexcrichton** [comment]
@bors: r+

Maybe Travis/docker had a bad weekend?

**Comment by palfrey** [comment]
This appears to have broken for different reasons:
* arm-linux-androideabi: `Warning: An error occurred while preparing SDK package ARM EABI v7a System Image: archive is not a ZIP archive.`
* sparc64-unknown-linux-gnu: `curl: (7) Failed to connect to caesar.ftp.acc.umu.se port 443: Connection timed out`

Not entirely sure either of those are Xenial-related given the earlier working build

**Comment by alexcrichton** [comment]
@bors: retry

Yeah looks spurious!

**Pull request merged**
