### PR TITLE
Open 'val' field in 'fsid_t' to the public

### PR DESCRIPTION
**Pull request by alesharik**

### CODE REVIEW

**Comment by gnzlbg** [comment]
This doesn't "open" the `val` field (it is still private). It's unclear to me what the motivation for this is.

**Comment by alesharik** [comment]
Oops, sorry. The reason to '"open" `val` field is to compare `fsid_t` structs, because `extra_traits` feature doesn't work.
This dependency config: 
```toml
[dependencies]
libc = { git = "https://github.com/rust-lang/libc", features = ["extra_traits"] }
```
Produces this error:
```
the package depends on `libc`, with features: `extra_traits` but `libc` does not have these features.
```

**Comment by gnzlbg** [comment]
What `libc` commit are you getting from git? And what does `cargo update` report ?

**Comment by alesharik** [comment]
Thanks, `cargo update` solved this issue. Sorry for the wasted time.

**Comment by gnzlbg** [comment]
No problem, and thank you for the PR nevertheless.

**Pull request closed without merging**
