### PR TITLE
Add struct and constants for mount_setattr syscall

### PR DESCRIPTION
**Pull request by pcc**
# Description

Adds struct and constants for mount_setattr syscall.

# Sources

https://github.com/torvalds/linux/blob/master/include/uapi/linux/mount.h

# Checklist

- [X] Relevant tests in `libc-test/semver` have been updated
- [X] No placeholder or unstable values like `*LAST` or `*MAX` are
  included (see [#3131](https://github.com/rust-lang/libc/issues/3131))
- [X] Tested locally (`cd libc-test && cargo test --target mytarget`);
  especially relevant for platforms that may not be checked in CI

### CODE REVIEW

**Review by tgross35 — APPROVED** [review]

**Review by tgross35 — CHANGES_REQUESTED** [review]
Ah, you might need to update build.rs if this isn't available on musl

**Comment by tgross35** [comment]
@pcc we just updated the linux headers on musl, could you rebase? The tests might start to pass.

**Comment by pcc** [comment]
> @pcc we just updated the linux headers on musl, could you rebase? The tests might start to pass.

Done

**Review by tgross35 — APPROVED** [review]
Thanks!

**Pull request merged**
