### PR TITLE
Reduce appveyor churn

### PR DESCRIPTION
**Pull request by gnzlbg**
This should reduce the Appveyorn churn for other projects a bit more.

Please let me know if there is anything else that can be done. Maybe the infra team could discuss whether to document some general guidelines for rust-lang and rust-lang-nursery projects, and write them down somewhere. I would be willing to help.

cc @RalfJung @Mark-Simulacrum

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks a lot!

Another thing you could do is not run the full AppVeyor test suite on every push to every PR. Currently that's about 15min each time. Maybe running one of the 4 jobs is representative enough that the rest can be covered by bors (including try builds if you want pre-landing testing)?

**Comment by gnzlbg** [comment]
> Maybe running one of the 4 jobs is representative enough that the rest can be covered by bors (including try builds if you want pre-landing testing)?

Sadly this isn't the case - the only thing we test here is the system ABI, and that's completely different for each of the targets running on appveyor. 

What we could do is move those jobs to Azure Pipelines, once we get a green light to land #1376 .

**Comment by RalfJung** [comment]
I was thinking the same for Miri (re: moving to Azure). ;)

So, how long until we'll have congestion there? :D Do you know how many runners we collectively have there?

**Comment by gnzlbg** [comment]
> So, how long until we'll have congestion there? :D Do you know how many runners we collectively have there?

No idea, but if rust-lang/rust ends up completely switching to Azure, I suppose the infra team will make an announcement about what their plan is, and what to do with the other repos in the org.

**Pull request merged**
