### PR TITLE
Define DCCP constants

### PR DESCRIPTION
**Pull request by jack-pappas**
This PR defines constants needed to utilize [DCCP](https://en.wikipedia.org/wiki/Datagram_Congestion_Control_Protocol) in Linux and NetBSD.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by jack-pappas** [comment]
I removed redundant definition of a couple of constants from the NetBSD module which was causing some build failures.

On the Linux side -- the C program generated by ``libc-test`` is failing because it can't find the definitions of some constants. The C program would need to include ``uapi/linux/dccp.h`` -- is there a way to tell if it's doing that, and if not, add the header to what it pulls in for the tests?

**Comment by alexcrichton** [comment]
You'll probably need to edit `libc-test/build.rs` to include the various headers I think

**Comment by jack-pappas** [comment]
I've fixed ``build.rs`` to include the needed additional headers and made a few tweaks to the constant definitions, and the changes are passing the CI tests now.

**Pull request merged**
