### PR TITLE
Add missing net/if.h and net/if_mib.h items

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I don't understand the error:

```
error: function is never used: `if_freenameindex`
    --> src/unix/bsd/freebsdlike/freebsd/mod.rs:3302:5
     |
3302 |     pub fn if_freenameindex(arg: *mut if_nameindex);
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
note: the lint level is defined here
    --> src/lib.rs:18:38
     |
18   | #![cfg_attr(libc_deny_warnings, deny(warnings))]
     |                                      ^^^^^^^^
     = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`
error: function is never used: `if_indextoname`
    --> src/unix/bsd/freebsdlike/freebsd/mod.rs:3303:5
     |
3303 |     pub fn if_indextoname(arg1: ::c_uint, arg2: *mut ::c_char) -> *mut ::c_char;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: function is never used: `if_nameindex`
    --> src/unix/bsd/freebsdlike/freebsd/mod.rs:3304:5
     |
3304 |     pub fn if_nameindex() -> *mut if_nameindex;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: function is never used: `if_nametoindex`
    --> src/unix/bsd/freebsdlike/freebsd/mod.rs:3305:5
     |
3305 |     pub fn if_nametoindex(arg: *const ::c_char) -> ::c_uint;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Some other functions from the same extern block are reexported without issues. What am I missing here?

**Comment by JohnTitor** [comment]
They're already declared:

https://github.com/rust-lang/libc/blob/e1eb9721dc4534cea84e9e3bf591e7cb257e679c/src/unix/bsd/mod.rs#L631-L632

**Comment by GuillaumeGomez** [comment]
Nice!

**Comment by GuillaumeGomez** [comment]
CI passed! \o/

**Comment by GuillaumeGomez** [comment]
I updated the debug and the checks by using slices (would have been much simpler if `as_slice` was implemented much earlier in rust T_T).

**Pull request merged**
