### PR TITLE
Implement utmp for solarish targets

### PR DESCRIPTION
**Pull request by GrayJack**
I followed these references:

https://github.com/illumos/illumos-gate/blob/4e0c5eff9af325c80994e9527b7cb8b3a1ffd1d4/usr/src/head/utmpx.h
https://github.com/illumos/illumos-gate/blob/4e0c5eff9af325c80994e9527b7cb8b3a1ffd1d4/usr/src/head/utmp.h

### CODE REVIEW

**Comment by glaubitz** [comment]
@GrayJack Can you fix the spelling error "solarish" => "solaris"?

**Comment by GrayJack** [comment]
@glaubitz I did used that intentionally, since internally the module is called `solarish`, probably because there more than one platform that have the same base (Oracle Solaris and Illumos).

I think there was a discussion to have a illumos target for Rust, probably cause there is enough differences between both nowadays.

But if that is really gonna be a problem, sure, I can change

**Comment by gnzlbg** [comment]
cc @jasonbking @bgermann

**Comment by jasonbking** [comment]
Another community member coined the term -- while there's a common heritage between illumos and Solaris, they've been separate projects for well over a decade now and have diverged in some areas so it's similar to the BSDs in that sense (a lot of things in common, and a number of things that are different). As to the change itself, it looks good to me.

**Comment by bgermann** [comment]
Looks good to me, too.

**Pull request merged**
