### PR TITLE
PIDFD_NONBLOCK addition into uclibc.

### LINKED ISSUE #3026: `PIDFD_NONBLOCK` missing from Linux armv7 uclibceabihf
https://github.com/nix-rust/nix/pull/1868/checks?check_run_id=9877370516

### PR DESCRIPTION
**Pull request by devnexen**
closes #3026.

### CODE REVIEW

**Comment by JonathanWoollett-Light** [comment]
@JohnTitor What reference are you looking for?

**Comment by JohnTitor** [comment]
> What reference are you looking for?

A declaration document or source would help my review :)

**Comment by devnexen** [comment]
[here](https://github.com/torvalds/linux/blob/6feb57c2fd7c787aecf2846a535248899e7b70fa/include/uapi/linux/pidfd.h#L10)

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thank you :) @bors r+

**Comment by JonathanWoollett-Light** [comment]
@JohnTitor  @devnexen  It looks like an anomalous failure in the CI, can you re-run it please.

**Comment by JohnTitor** [comment]
The failure is now fixed on master, @bors retry

**Pull request merged**
